#!/usr/bin/env python3
# generate_timer.py - Generate all outputs from timer.rdl.
#
# Tries to use PeakRDL for generation; if PeakRDL is unavailable the script
# falls back to hand-writing all output files with identical content.
#
# Outputs produced:
#   design/rtl/verilog/timer_reg_pkg.sv   - SV package: offsets, masks, resets
#   design/rtl/verilog/timer_regfile.sv   - Synthesizable SV register-file
#   design/rtl/vhdl/timer_reg_pkg.vhd     - VHDL-2008 package equivalent
#   design/rtl/vhdl/timer_regfile.vhd     - Synthesizable VHDL-2008 register-file
#   firmware/include/timer_regs.h         - C header with #define macros
#   doc/timer_regs.html                   - HTML register documentation

import argparse
import os
import sys


# ---------------------------------------------------------------------------
# Environment guard
# ---------------------------------------------------------------------------
def _require_env():
    # type: () -> str
    timer_path = os.environ.get("CLAUDE_TIMER_PATH")
    if not timer_path:
        print("ERROR: CLAUDE_TIMER_PATH is not set.")
        print("       Please run:  source timer/setup.sh")
        sys.exit(1)
    return timer_path


# ---------------------------------------------------------------------------
# Register model (mirrors timer.rdl exactly)
# ---------------------------------------------------------------------------

# Address offsets (byte)
CTRL_OFFSET   = 0x00
STATUS_OFFSET = 0x04
LOAD_OFFSET   = 0x08
COUNT_OFFSET  = 0x0C

# CTRL field bit positions
CTRL_EN_BIT       = 0
CTRL_MODE_BIT     = 1
CTRL_INTR_EN_BIT  = 2
CTRL_TRIG_EN_BIT  = 3
CTRL_PRESCALE_LSB = 4
CTRL_PRESCALE_MSB = 11
CTRL_PRESCALE_WIDTH = 8

# STATUS field bit positions
STATUS_INTR_BIT   = 0
STATUS_ACTIVE_BIT = 1

# Reset values
CTRL_RESET   = 0x00000000
STATUS_RESET = 0x00000000
LOAD_RESET   = 0x00000000
COUNT_RESET  = 0x00000000


def _mask(msb, lsb):
    # type: (int, int) -> int
    """Return a bitmask covering bits [msb:lsb]."""
    width = msb - lsb + 1
    return ((1 << width) - 1) << lsb


# ---------------------------------------------------------------------------
# Hand-generate: SystemVerilog package
# ---------------------------------------------------------------------------
SV_PKG = (
    "// timer_reg_pkg.sv - Timer IP register-file package.\n"
    "// Auto-generated by generate_timer.py - do not edit by hand.\n"
    "// Single source of truth: design/systemrdl/timer.rdl\n"
    "\n"
    "`ifndef TIMER_REG_PKG_SV\n"
    "`define TIMER_REG_PKG_SV\n"
    "\n"
    "package timer_reg_pkg;\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // Address offsets (word address = byte_offset >> 2)\n"
    "  // -----------------------------------------------------------------------\n"
    "  parameter logic [3:0] TIMER_CTRL_OFFSET   = 4'h0; // 0x00\n"
    "  parameter logic [3:0] TIMER_STATUS_OFFSET = 4'h1; // 0x04\n"
    "  parameter logic [3:0] TIMER_LOAD_OFFSET   = 4'h2; // 0x08\n"
    "  parameter logic [3:0] TIMER_COUNT_OFFSET  = 4'h3; // 0x0C\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // CTRL register (byte offset 0x00, word offset 0x0)\n"
    "  // -----------------------------------------------------------------------\n"
    "  parameter logic [31:0] TIMER_CTRL_RESET        = 32'h0000_0000;\n"
    "  parameter logic [31:0] TIMER_CTRL_EN_MASK       = 32'h0000_0001; // bit  0\n"
    "  parameter logic [31:0] TIMER_CTRL_MODE_MASK     = 32'h0000_0002; // bit  1\n"
    "  parameter logic [31:0] TIMER_CTRL_INTR_EN_MASK  = 32'h0000_0004; // bit  2\n"
    "  parameter logic [31:0] TIMER_CTRL_TRIG_EN_MASK  = 32'h0000_0008; // bit  3\n"
    "  parameter logic [31:0] TIMER_CTRL_PRESCALE_MASK = 32'h0000_0FF0; // bits 11:4\n"
    "  parameter int unsigned TIMER_CTRL_EN_BIT        = 0;\n"
    "  parameter int unsigned TIMER_CTRL_MODE_BIT      = 1;\n"
    "  parameter int unsigned TIMER_CTRL_INTR_EN_BIT   = 2;\n"
    "  parameter int unsigned TIMER_CTRL_TRIG_EN_BIT   = 3;\n"
    "  parameter int unsigned TIMER_CTRL_PRESCALE_LSB  = 4;\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // STATUS register (byte offset 0x04, word offset 0x1)\n"
    "  // -----------------------------------------------------------------------\n"
    "  parameter logic [31:0] TIMER_STATUS_RESET       = 32'h0000_0000;\n"
    "  parameter logic [31:0] TIMER_STATUS_INTR_MASK   = 32'h0000_0001; // bit  0\n"
    "  parameter logic [31:0] TIMER_STATUS_ACTIVE_MASK = 32'h0000_0002; // bit  1\n"
    "  parameter int unsigned TIMER_STATUS_INTR_BIT    = 0;\n"
    "  parameter int unsigned TIMER_STATUS_ACTIVE_BIT  = 1;\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // LOAD register (byte offset 0x08, word offset 0x2)\n"
    "  // -----------------------------------------------------------------------\n"
    "  parameter logic [31:0] TIMER_LOAD_RESET = 32'h0000_0000;\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // COUNT register (byte offset 0x0C, word offset 0x3)\n"
    "  // -----------------------------------------------------------------------\n"
    "  parameter logic [31:0] TIMER_COUNT_RESET = 32'h0000_0000;\n"
    "\n"
    "endpackage : timer_reg_pkg\n"
    "\n"
    "`endif // TIMER_REG_PKG_SV\n"
)


# ---------------------------------------------------------------------------
# Hand-generate: SystemVerilog register-file module
# ---------------------------------------------------------------------------
SV_REGFILE = (
    "// timer_regfile.sv - Timer IP synthesizable register file.\n"
    "// Auto-generated by generate_timer.py - do not edit by hand.\n"
    "// Single source of truth: design/systemrdl/timer.rdl\n"
    "//\n"
    "// Interface (bus-agnostic, flat ports - no SV interface constructs):\n"
    "//\n"
    "//   Clock / reset:\n"
    "//     clk       : input  - system clock (rising edge active)\n"
    "//     rst_n     : input  - synchronous active-low reset\n"
    "//\n"
    "//   Write channel:\n"
    "//     wr_en     : input  - write enable (pulse)\n"
    "//     wr_addr   : input  [3:0]  - word address (byte_addr >> 2)\n"
    "//     wr_data   : input  [31:0] - write data\n"
    "//     wr_strb   : input  [3:0]  - byte write strobes\n"
    "//\n"
    "//   Read channel:\n"
    "//     rd_en     : input  - read enable (pulse)\n"
    "//     rd_addr   : input  [3:0]  - word address (byte_addr >> 2)\n"
    "//     rd_data   : output [31:0] - read data (registered, valid next cycle)\n"
    "//\n"
    "//   Hardware update ports (driven by timer_core):\n"
    "//     hw_count_val : input  [31:0] - current count value for COUNT register\n"
    "//     hw_intr_set  : input         - set STATUS.INTR when asserted\n"
    "//     hw_active    : input         - reflects running state to STATUS.ACTIVE\n"
    "//\n"
    "//   Output to core:\n"
    "//     ctrl_en       : output        - CTRL.EN field\n"
    "//     ctrl_mode     : output        - CTRL.MODE field\n"
    "//     ctrl_intr_en  : output        - CTRL.INTR_EN field\n"
    "//     ctrl_trig_en  : output        - CTRL.TRIG_EN field\n"
    "//     ctrl_prescale : output [7:0]  - CTRL.PRESCALE field\n"
    "//     load_val      : output [31:0] - LOAD.VALUE field\n"
    "\n"
    "module timer_regfile\n"
    "  import timer_reg_pkg::*;\n"
    "(\n"
    "  // Clock and synchronous active-low reset\n"
    "  input  logic        clk,\n"
    "  input  logic        rst_n,\n"
    "\n"
    "  // Write channel\n"
    "  input  logic        wr_en,\n"
    "  input  logic [3:0]  wr_addr,\n"
    "  input  logic [31:0] wr_data,\n"
    "  input  logic [3:0]  wr_strb,\n"
    "\n"
    "  // Read channel\n"
    "  input  logic        rd_en,\n"
    "  input  logic [3:0]  rd_addr,\n"
    "  output logic [31:0] rd_data,\n"
    "\n"
    "  // Hardware update ports (from timer_core)\n"
    "  input  logic [31:0] hw_count_val,\n"
    "  input  logic        hw_intr_set,\n"
    "  input  logic        hw_active,\n"
    "\n"
    "  // Output to timer_core\n"
    "  output logic        ctrl_en,\n"
    "  output logic        ctrl_mode,\n"
    "  output logic        ctrl_intr_en,\n"
    "  output logic        ctrl_trig_en,\n"
    "  output logic [7:0]  ctrl_prescale,\n"
    "  output logic [31:0] load_val\n"
    ");\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // Internal register storage\n"
    "  // -----------------------------------------------------------------------\n"
    "  logic [31:0] ctrl_q;\n"
    "  logic [31:0] status_q;\n"
    "  logic [31:0] load_q;\n"
    "  logic [31:0] count_q;  // mirror of hw_count_val, captured each cycle\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // Byte-enable merge helper: apply wr_strb to current register value\n"
    "  // -----------------------------------------------------------------------\n"
    "  function automatic logic [31:0] apply_strb(\n"
    "    input logic [31:0] current,\n"
    "    input logic [31:0] wdata,\n"
    "    input logic [3:0]  strb\n"
    "  );\n"
    "    logic [31:0] result;\n"
    "    result[7:0]   = strb[0] ? wdata[7:0]   : current[7:0];\n"
    "    result[15:8]  = strb[1] ? wdata[15:8]  : current[15:8];\n"
    "    result[23:16] = strb[2] ? wdata[23:16] : current[23:16];\n"
    "    result[31:24] = strb[3] ? wdata[31:24] : current[31:24];\n"
    "    return result;\n"
    "  endfunction\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // CTRL register - RW, reset 0x0\n"
    "  // Fields: EN[0], MODE[1], INTR_EN[2], TRIG_EN[3], PRESCALE[11:4]\n"
    "  // Reserved bits [31:12] always read as zero and ignore writes.\n"
    "  // -----------------------------------------------------------------------\n"
    "  always_ff @(posedge clk) begin\n"
    "    if (!rst_n) begin\n"
    "      ctrl_q <= TIMER_CTRL_RESET;\n"
    "    end else if (wr_en && (wr_addr == TIMER_CTRL_OFFSET)) begin\n"
    "      // Write only to defined fields; reserved bits are masked to zero.\n"
    "      ctrl_q <= apply_strb(ctrl_q, wr_data, wr_strb) & 32'h0000_0FFF;\n"
    "    end\n"
    "  end\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // STATUS register - INTR is W1C (write-1-to-clear), ACTIVE is RO from hw.\n"
    "  // -----------------------------------------------------------------------\n"
    "  always_ff @(posedge clk) begin\n"
    "    if (!rst_n) begin\n"
    "      status_q <= TIMER_STATUS_RESET;\n"
    "    end else begin\n"
    "      // ACTIVE tracks the hw_active signal directly.\n"
    "      status_q[TIMER_STATUS_ACTIVE_BIT] <= hw_active;\n"
    "\n"
    "      // INTR: set by hw_intr_set; cleared by writing 1 to bit 0.\n"
    "      if (hw_intr_set) begin\n"
    "        status_q[TIMER_STATUS_INTR_BIT] <= 1'b1;\n"
    "      end else if (wr_en && (wr_addr == TIMER_STATUS_OFFSET) &&\n"
    "                   wr_strb[0] && wr_data[TIMER_STATUS_INTR_BIT]) begin\n"
    "        status_q[TIMER_STATUS_INTR_BIT] <= 1'b0;\n"
    "      end\n"
    "\n"
    "      // Reserved bits stay zero\n"
    "      status_q[31:2] <= 30'h0;\n"
    "    end\n"
    "  end\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // LOAD register - fully RW, reset 0x0\n"
    "  // -----------------------------------------------------------------------\n"
    "  always_ff @(posedge clk) begin\n"
    "    if (!rst_n) begin\n"
    "      load_q <= TIMER_LOAD_RESET;\n"
    "    end else if (wr_en && (wr_addr == TIMER_LOAD_OFFSET)) begin\n"
    "      load_q <= apply_strb(load_q, wr_data, wr_strb);\n"
    "    end\n"
    "  end\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // COUNT register - RO mirror of hw_count_val, updated every cycle\n"
    "  // -----------------------------------------------------------------------\n"
    "  always_ff @(posedge clk) begin\n"
    "    if (!rst_n) begin\n"
    "      count_q <= TIMER_COUNT_RESET;\n"
    "    end else begin\n"
    "      count_q <= hw_count_val;\n"
    "    end\n"
    "  end\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // Read path - registered (valid the cycle after rd_en)\n"
    "  // -----------------------------------------------------------------------\n"
    "  always_ff @(posedge clk) begin\n"
    "    if (!rst_n) begin\n"
    "      rd_data <= 32'h0000_0000;\n"
    "    end else if (rd_en) begin\n"
    "      unique case (rd_addr)\n"
    "        TIMER_CTRL_OFFSET:   rd_data <= ctrl_q;\n"
    "        TIMER_STATUS_OFFSET: rd_data <= status_q;\n"
    "        TIMER_LOAD_OFFSET:   rd_data <= load_q;\n"
    "        TIMER_COUNT_OFFSET:  rd_data <= count_q;\n"
    "        default:             rd_data <= 32'h0000_0000;\n"
    "      endcase\n"
    "    end\n"
    "  end\n"
    "\n"
    "  // -----------------------------------------------------------------------\n"
    "  // Output assignments to timer_core\n"
    "  // -----------------------------------------------------------------------\n"
    "  assign ctrl_en       = ctrl_q[TIMER_CTRL_EN_BIT];\n"
    "  assign ctrl_mode     = ctrl_q[TIMER_CTRL_MODE_BIT];\n"
    "  assign ctrl_intr_en  = ctrl_q[TIMER_CTRL_INTR_EN_BIT];\n"
    "  assign ctrl_trig_en  = ctrl_q[TIMER_CTRL_TRIG_EN_BIT];\n"
    "  assign ctrl_prescale = ctrl_q[TIMER_CTRL_PRESCALE_LSB +: 8];\n"
    "  assign load_val      = load_q;\n"
    "\n"
    "endmodule : timer_regfile\n"
)


# ---------------------------------------------------------------------------
# Hand-generate: VHDL-2008 package
# ---------------------------------------------------------------------------
VHD_PKG = (
    "-- timer_reg_pkg.vhd - Timer IP register-file package (VHDL-2008).\n"
    "-- Auto-generated by generate_timer.py - do not edit by hand.\n"
    "-- Single source of truth: design/systemrdl/timer.rdl\n"
    "\n"
    "library ieee;\n"
    "use ieee.std_logic_1164.all;\n"
    "use ieee.numeric_std.all;\n"
    "\n"
    "package timer_reg_pkg is\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- Address offsets (word address = byte_offset / 4)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  constant TIMER_CTRL_OFFSET   : std_ulogic_vector(3 downto 0) := x\"0\"; -- 0x00\n"
    "  constant TIMER_STATUS_OFFSET : std_ulogic_vector(3 downto 0) := x\"1\"; -- 0x04\n"
    "  constant TIMER_LOAD_OFFSET   : std_ulogic_vector(3 downto 0) := x\"2\"; -- 0x08\n"
    "  constant TIMER_COUNT_OFFSET  : std_ulogic_vector(3 downto 0) := x\"3\"; -- 0x0C\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- CTRL register (byte offset 0x00)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  constant TIMER_CTRL_RESET         : std_ulogic_vector(31 downto 0) := x\"00000000\";\n"
    "  constant TIMER_CTRL_EN_MASK       : std_ulogic_vector(31 downto 0) := x\"00000001\"; -- bit  0\n"
    "  constant TIMER_CTRL_MODE_MASK     : std_ulogic_vector(31 downto 0) := x\"00000002\"; -- bit  1\n"
    "  constant TIMER_CTRL_INTR_EN_MASK  : std_ulogic_vector(31 downto 0) := x\"00000004\"; -- bit  2\n"
    "  constant TIMER_CTRL_TRIG_EN_MASK  : std_ulogic_vector(31 downto 0) := x\"00000008\"; -- bit  3\n"
    "  constant TIMER_CTRL_PRESCALE_MASK : std_ulogic_vector(31 downto 0) := x\"00000FF0\"; -- bits 11:4\n"
    "  constant TIMER_CTRL_EN_BIT        : integer := 0;\n"
    "  constant TIMER_CTRL_MODE_BIT      : integer := 1;\n"
    "  constant TIMER_CTRL_INTR_EN_BIT   : integer := 2;\n"
    "  constant TIMER_CTRL_TRIG_EN_BIT   : integer := 3;\n"
    "  constant TIMER_CTRL_PRESCALE_LSB  : integer := 4;\n"
    "  constant TIMER_CTRL_PRESCALE_MSB  : integer := 11;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- STATUS register (byte offset 0x04)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  constant TIMER_STATUS_RESET        : std_ulogic_vector(31 downto 0) := x\"00000000\";\n"
    "  constant TIMER_STATUS_INTR_MASK    : std_ulogic_vector(31 downto 0) := x\"00000001\"; -- bit  0\n"
    "  constant TIMER_STATUS_ACTIVE_MASK  : std_ulogic_vector(31 downto 0) := x\"00000002\"; -- bit  1\n"
    "  constant TIMER_STATUS_INTR_BIT     : integer := 0;\n"
    "  constant TIMER_STATUS_ACTIVE_BIT   : integer := 1;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- LOAD register (byte offset 0x08)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  constant TIMER_LOAD_RESET  : std_ulogic_vector(31 downto 0) := x\"00000000\";\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- COUNT register (byte offset 0x0C)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  constant TIMER_COUNT_RESET : std_ulogic_vector(31 downto 0) := x\"00000000\";\n"
    "\n"
    "end package timer_reg_pkg;\n"
)


# ---------------------------------------------------------------------------
# Hand-generate: VHDL-2008 register-file entity
# ---------------------------------------------------------------------------
VHD_REGFILE = (
    "-- timer_regfile.vhd - Timer IP synthesizable register file (VHDL-2008).\n"
    "-- Auto-generated by generate_timer.py - do not edit by hand.\n"
    "-- Single source of truth: design/systemrdl/timer.rdl\n"
    "--\n"
    "-- Port list is port-for-port equivalent to timer_regfile.sv.\n"
    "\n"
    "library ieee;\n"
    "use ieee.std_logic_1164.all;\n"
    "use ieee.numeric_std.all;\n"
    "\n"
    "library work;\n"
    "use work.timer_reg_pkg.all;\n"
    "\n"
    "entity timer_regfile is\n"
    "  port (\n"
    "    -- Clock and synchronous active-low reset\n"
    "    clk          : in  std_ulogic;\n"
    "    rst_n        : in  std_ulogic;\n"
    "\n"
    "    -- Write channel\n"
    "    wr_en        : in  std_ulogic;\n"
    "    wr_addr      : in  std_ulogic_vector(3 downto 0);\n"
    "    wr_data      : in  std_ulogic_vector(31 downto 0);\n"
    "    wr_strb      : in  std_ulogic_vector(3 downto 0);\n"
    "\n"
    "    -- Read channel\n"
    "    rd_en        : in  std_ulogic;\n"
    "    rd_addr      : in  std_ulogic_vector(3 downto 0);\n"
    "    rd_data      : out std_ulogic_vector(31 downto 0);\n"
    "\n"
    "    -- Hardware update ports (from timer_core)\n"
    "    hw_count_val : in  std_ulogic_vector(31 downto 0);\n"
    "    hw_intr_set  : in  std_ulogic;\n"
    "    hw_active    : in  std_ulogic;\n"
    "\n"
    "    -- Output to timer_core\n"
    "    ctrl_en       : out std_ulogic;\n"
    "    ctrl_mode     : out std_ulogic;\n"
    "    ctrl_intr_en  : out std_ulogic;\n"
    "    ctrl_trig_en  : out std_ulogic;\n"
    "    ctrl_prescale : out std_ulogic_vector(7 downto 0);\n"
    "    load_val      : out std_ulogic_vector(31 downto 0)\n"
    "  );\n"
    "end entity timer_regfile;\n"
    "\n"
    "architecture rtl of timer_regfile is\n"
    "\n"
    "  -- Internal register storage\n"
    "  signal ctrl_q   : std_ulogic_vector(31 downto 0);\n"
    "  signal status_q : std_ulogic_vector(31 downto 0);\n"
    "  signal load_q   : std_ulogic_vector(31 downto 0);\n"
    "  signal count_q  : std_ulogic_vector(31 downto 0);\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- Byte-enable merge: apply wr_strb to current register value\n"
    "  -- -----------------------------------------------------------------------\n"
    "  function apply_strb (\n"
    "    current : std_ulogic_vector(31 downto 0);\n"
    "    wdata   : std_ulogic_vector(31 downto 0);\n"
    "    strb    : std_ulogic_vector(3 downto 0)\n"
    "  ) return std_ulogic_vector is\n"
    "    variable result : std_ulogic_vector(31 downto 0);\n"
    "  begin\n"
    "    result(7 downto 0)   := wdata(7 downto 0)   when strb(0) = '1' else current(7 downto 0);\n"
    "    result(15 downto 8)  := wdata(15 downto 8)  when strb(1) = '1' else current(15 downto 8);\n"
    "    result(23 downto 16) := wdata(23 downto 16) when strb(2) = '1' else current(23 downto 16);\n"
    "    result(31 downto 24) := wdata(31 downto 24) when strb(3) = '1' else current(31 downto 24);\n"
    "    return result;\n"
    "  end function apply_strb;\n"
    "\n"
    "begin\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- CTRL register - RW, reset 0x0\n"
    "  -- Reserved bits [31:12] are always zero.\n"
    "  -- -----------------------------------------------------------------------\n"
    "  p_ctrl : process (clk) is\n"
    "  begin\n"
    "    if rising_edge(clk) then\n"
    "      if rst_n = '0' then\n"
    "        ctrl_q <= TIMER_CTRL_RESET;\n"
    "      elsif wr_en = '1' and wr_addr = TIMER_CTRL_OFFSET then\n"
    "        -- Mask to defined fields only; reserved bits stay zero.\n"
    "        ctrl_q <= apply_strb(ctrl_q, wr_data, wr_strb)\n"
    "                  and x\"00000FFF\";\n"
    "      end if;\n"
    "    end if;\n"
    "  end process p_ctrl;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- STATUS register\n"
    "  --   INTR  (bit 0) : W1C - hw sets; write-1 to clear.\n"
    "  --   ACTIVE(bit 1) : RO  - hw drives directly.\n"
    "  -- -----------------------------------------------------------------------\n"
    "  p_status : process (clk) is\n"
    "  begin\n"
    "    if rising_edge(clk) then\n"
    "      if rst_n = '0' then\n"
    "        status_q <= TIMER_STATUS_RESET;\n"
    "      else\n"
    "        -- ACTIVE tracks hw_active\n"
    "        status_q(TIMER_STATUS_ACTIVE_BIT) <= hw_active;\n"
    "\n"
    "        -- INTR: set by hw; cleared by W1C\n"
    "        if hw_intr_set = '1' then\n"
    "          status_q(TIMER_STATUS_INTR_BIT) <= '1';\n"
    "        elsif wr_en = '1'\n"
    "              and wr_addr = TIMER_STATUS_OFFSET\n"
    "              and wr_strb(0) = '1'\n"
    "              and wr_data(TIMER_STATUS_INTR_BIT) = '1' then\n"
    "          status_q(TIMER_STATUS_INTR_BIT) <= '0';\n"
    "        end if;\n"
    "\n"
    "        -- Reserved bits stay zero\n"
    "        status_q(31 downto 2) <= (others => '0');\n"
    "      end if;\n"
    "    end if;\n"
    "  end process p_status;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- LOAD register - fully RW, reset 0x0\n"
    "  -- -----------------------------------------------------------------------\n"
    "  p_load : process (clk) is\n"
    "  begin\n"
    "    if rising_edge(clk) then\n"
    "      if rst_n = '0' then\n"
    "        load_q <= TIMER_LOAD_RESET;\n"
    "      elsif wr_en = '1' and wr_addr = TIMER_LOAD_OFFSET then\n"
    "        load_q <= apply_strb(load_q, wr_data, wr_strb);\n"
    "      end if;\n"
    "    end if;\n"
    "  end process p_load;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- COUNT register - RO mirror of hw_count_val\n"
    "  -- -----------------------------------------------------------------------\n"
    "  p_count : process (clk) is\n"
    "  begin\n"
    "    if rising_edge(clk) then\n"
    "      if rst_n = '0' then\n"
    "        count_q <= TIMER_COUNT_RESET;\n"
    "      else\n"
    "        count_q <= hw_count_val;\n"
    "      end if;\n"
    "    end if;\n"
    "  end process p_count;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- Read path - registered (valid cycle after rd_en)\n"
    "  -- -----------------------------------------------------------------------\n"
    "  p_read : process (clk) is\n"
    "  begin\n"
    "    if rising_edge(clk) then\n"
    "      if rst_n = '0' then\n"
    "        rd_data <= (others => '0');\n"
    "      elsif rd_en = '1' then\n"
    "        case rd_addr is\n"
    "          when TIMER_CTRL_OFFSET   => rd_data <= ctrl_q;\n"
    "          when TIMER_STATUS_OFFSET => rd_data <= status_q;\n"
    "          when TIMER_LOAD_OFFSET   => rd_data <= load_q;\n"
    "          when TIMER_COUNT_OFFSET  => rd_data <= count_q;\n"
    "          when others              => rd_data <= (others => '0');\n"
    "        end case;\n"
    "      end if;\n"
    "    end if;\n"
    "  end process p_read;\n"
    "\n"
    "  -- -----------------------------------------------------------------------\n"
    "  -- Output assignments to timer_core\n"
    "  -- -----------------------------------------------------------------------\n"
    "  ctrl_en       <= ctrl_q(TIMER_CTRL_EN_BIT);\n"
    "  ctrl_mode     <= ctrl_q(TIMER_CTRL_MODE_BIT);\n"
    "  ctrl_intr_en  <= ctrl_q(TIMER_CTRL_INTR_EN_BIT);\n"
    "  ctrl_trig_en  <= ctrl_q(TIMER_CTRL_TRIG_EN_BIT);\n"
    "  ctrl_prescale <= ctrl_q(TIMER_CTRL_PRESCALE_MSB downto TIMER_CTRL_PRESCALE_LSB);\n"
    "  load_val      <= load_q;\n"
    "\n"
    "end architecture rtl;\n"
)


# ---------------------------------------------------------------------------
# Hand-generate: C header
# ---------------------------------------------------------------------------
C_HEADER = (
    "/* timer_regs.h - Timer IP register definitions (C99).\n"
    " * Auto-generated by generate_timer.py - do not edit by hand.\n"
    " * Single source of truth: design/systemrdl/timer.rdl\n"
    " */\n"
    "\n"
    "#ifndef TIMER_REGS_H\n"
    "#define TIMER_REGS_H\n"
    "\n"
    "#include <stdint.h>\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * Base address placeholder - override before including this header.\n"
    " * -------------------------------------------------------------------------*/\n"
    "#ifndef TIMER_BASE_ADDR\n"
    "#  define TIMER_BASE_ADDR  (0x00000000UL)\n"
    "#endif\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * Register byte offsets\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_CTRL_OFFSET    (0x00U)\n"
    "#define TIMER_STATUS_OFFSET  (0x04U)\n"
    "#define TIMER_LOAD_OFFSET    (0x08U)\n"
    "#define TIMER_COUNT_OFFSET   (0x0CU)\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * Register absolute addresses\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_CTRL_ADDR    ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_CTRL_OFFSET))\n"
    "#define TIMER_STATUS_ADDR  ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_STATUS_OFFSET))\n"
    "#define TIMER_LOAD_ADDR    ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_LOAD_OFFSET))\n"
    "#define TIMER_COUNT_ADDR   ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_COUNT_OFFSET))\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * CTRL register fields (byte offset 0x00)\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_CTRL_RESET           (0x00000000UL)\n"
    "\n"
    "/** EN - Timer enable (bit 0) */\n"
    "#define TIMER_CTRL_EN_BIT          (0U)\n"
    "#define TIMER_CTRL_EN_MASK         (0x00000001UL)\n"
    "#define TIMER_CTRL_EN_GET(reg)     (((reg) & TIMER_CTRL_EN_MASK) >> TIMER_CTRL_EN_BIT)\n"
    "#define TIMER_CTRL_EN_SET(reg, v)  (((reg) & ~TIMER_CTRL_EN_MASK) | \\\n"
    "                                    (((uint32_t)(v) << TIMER_CTRL_EN_BIT) & TIMER_CTRL_EN_MASK))\n"
    "\n"
    "/** MODE - Operating mode (bit 1): 0=repeat/free-run, 1=one-shot */\n"
    "#define TIMER_CTRL_MODE_BIT        (1U)\n"
    "#define TIMER_CTRL_MODE_MASK       (0x00000002UL)\n"
    "#define TIMER_CTRL_MODE_REPEAT     (0U)\n"
    "#define TIMER_CTRL_MODE_ONESHOT    (1U)\n"
    "#define TIMER_CTRL_MODE_GET(reg)   (((reg) & TIMER_CTRL_MODE_MASK) >> TIMER_CTRL_MODE_BIT)\n"
    "#define TIMER_CTRL_MODE_SET(reg, v)(((reg) & ~TIMER_CTRL_MODE_MASK) | \\\n"
    "                                    (((uint32_t)(v) << TIMER_CTRL_MODE_BIT) \\\n"
    "                                      & TIMER_CTRL_MODE_MASK))\n"
    "\n"
    "/** INTR_EN - Interrupt enable (bit 2) */\n"
    "#define TIMER_CTRL_INTR_EN_BIT         (2U)\n"
    "#define TIMER_CTRL_INTR_EN_MASK        (0x00000004UL)\n"
    "#define TIMER_CTRL_INTR_EN_GET(reg)    (((reg) & TIMER_CTRL_INTR_EN_MASK) \\\n"
    "                                         >> TIMER_CTRL_INTR_EN_BIT)\n"
    "#define TIMER_CTRL_INTR_EN_SET(reg, v) (((reg) & ~TIMER_CTRL_INTR_EN_MASK) | \\\n"
    "                                        (((uint32_t)(v) << TIMER_CTRL_INTR_EN_BIT) \\\n"
    "                                          & TIMER_CTRL_INTR_EN_MASK))\n"
    "\n"
    "/** TRIG_EN - Trigger output enable (bit 3) */\n"
    "#define TIMER_CTRL_TRIG_EN_BIT         (3U)\n"
    "#define TIMER_CTRL_TRIG_EN_MASK        (0x00000008UL)\n"
    "#define TIMER_CTRL_TRIG_EN_GET(reg)    (((reg) & TIMER_CTRL_TRIG_EN_MASK) \\\n"
    "                                         >> TIMER_CTRL_TRIG_EN_BIT)\n"
    "#define TIMER_CTRL_TRIG_EN_SET(reg, v) (((reg) & ~TIMER_CTRL_TRIG_EN_MASK) | \\\n"
    "                                        (((uint32_t)(v) << TIMER_CTRL_TRIG_EN_BIT) \\\n"
    "                                          & TIMER_CTRL_TRIG_EN_MASK))\n"
    "\n"
    "/** PRESCALE - Clock prescale (bits 11:4); divide ratio = PRESCALE + 1 */\n"
    "#define TIMER_CTRL_PRESCALE_LSB        (4U)\n"
    "#define TIMER_CTRL_PRESCALE_MASK       (0x00000FF0UL)\n"
    "#define TIMER_CTRL_PRESCALE_GET(reg)   (((reg) & TIMER_CTRL_PRESCALE_MASK) \\\n"
    "                                         >> TIMER_CTRL_PRESCALE_LSB)\n"
    "#define TIMER_CTRL_PRESCALE_SET(reg, v)(((reg) & ~TIMER_CTRL_PRESCALE_MASK) | \\\n"
    "                                        (((uint32_t)(v) << TIMER_CTRL_PRESCALE_LSB) \\\n"
    "                                          & TIMER_CTRL_PRESCALE_MASK))\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * STATUS register fields (byte offset 0x04)\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_STATUS_RESET          (0x00000000UL)\n"
    "\n"
    "/** INTR - Interrupt pending (bit 0); W1C - write 1 to clear */\n"
    "#define TIMER_STATUS_INTR_BIT       (0U)\n"
    "#define TIMER_STATUS_INTR_MASK      (0x00000001UL)\n"
    "#define TIMER_STATUS_INTR_GET(reg)  (((reg) & TIMER_STATUS_INTR_MASK) \\\n"
    "                                      >> TIMER_STATUS_INTR_BIT)\n"
    "#define TIMER_STATUS_INTR_CLR       (TIMER_STATUS_INTR_MASK)\n"
    "\n"
    "/** ACTIVE - Timer running (bit 1); read-only */\n"
    "#define TIMER_STATUS_ACTIVE_BIT     (1U)\n"
    "#define TIMER_STATUS_ACTIVE_MASK    (0x00000002UL)\n"
    "#define TIMER_STATUS_ACTIVE_GET(reg)(((reg) & TIMER_STATUS_ACTIVE_MASK) \\\n"
    "                                      >> TIMER_STATUS_ACTIVE_BIT)\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * LOAD register (byte offset 0x08) - reload / initial count value\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_LOAD_RESET            (0x00000000UL)\n"
    "#define TIMER_LOAD_VALUE_MASK       (0xFFFFFFFFUL)\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * COUNT register (byte offset 0x0C) - current counter value (read-only)\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_COUNT_RESET           (0x00000000UL)\n"
    "#define TIMER_COUNT_VALUE_MASK      (0xFFFFFFFFUL)\n"
    "\n"
    "/* -------------------------------------------------------------------------\n"
    " * Convenience accessor macros (assumes TIMER_BASE_ADDR is defined)\n"
    " * -------------------------------------------------------------------------*/\n"
    "#define TIMER_REG_READ(offset)       \\\n"
    "    (*((volatile uint32_t *)(TIMER_BASE_ADDR + (offset))))\n"
    "#define TIMER_REG_WRITE(offset, val) \\\n"
    "    (*((volatile uint32_t *)(TIMER_BASE_ADDR + (offset))) = (uint32_t)(val))\n"
    "\n"
    "#endif /* TIMER_REGS_H */\n"
)


# ---------------------------------------------------------------------------
# Hand-generate: HTML documentation
# ---------------------------------------------------------------------------
HTML_DOC = (
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>Timer IP Register Map</title>\n"
    "  <style>\n"
    "    body { font-family: Arial, sans-serif; margin: 2em; color: #222; }\n"
    "    h1   { color: #003366; }\n"
    "    h2   { color: #005599; border-bottom: 2px solid #005599; }\n"
    "    h3   { color: #336699; }\n"
    "    table {\n"
    "      border-collapse: collapse;\n"
    "      width: 100%;\n"
    "      margin-bottom: 1.5em;\n"
    "    }\n"
    "    th, td {\n"
    "      border: 1px solid #aaa;\n"
    "      padding: 6px 10px;\n"
    "      text-align: left;\n"
    "      vertical-align: top;\n"
    "    }\n"
    "    th   { background-color: #dce8f5; }\n"
    "    tr:nth-child(even) { background-color: #f5f9ff; }\n"
    "    .mono { font-family: monospace; }\n"
    "    .ro   { color: #880000; }\n"
    "    .rw   { color: #005500; }\n"
    "    .w1c  { color: #aa5500; }\n"
    "    .note { font-size: 0.9em; color: #555; }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<h1>Timer IP Register Map</h1>\n"
    "<p>Auto-generated by <code>generate_timer.py</code>. Single source of truth:\n"
    "<code>design/systemrdl/timer.rdl</code>.</p>\n"
    "<p>Base address: configured at integration time. All registers are 32-bit,\n"
    "byte-addressable. Register accesses are word-aligned.</p>\n"
    "\n"
    "<h2>Register Summary</h2>\n"
    "<table>\n"
    "  <tr><th>Offset</th><th>Name</th><th>Access</th><th>Reset</th>"
    "<th>Description</th></tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0x00</td>\n"
    "    <td class=\"mono\">CTRL</td>\n"
    "    <td>RW</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>Control register</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0x04</td>\n"
    "    <td class=\"mono\">STATUS</td>\n"
    "    <td>RO / W1C</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>Status register</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0x08</td>\n"
    "    <td class=\"mono\">LOAD</td>\n"
    "    <td>RW</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>Reload / initial count value</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0x0C</td>\n"
    "    <td class=\"mono\">COUNT</td>\n"
    "    <td>RO</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>Current counter value (hw-updated)</td>\n"
    "  </tr>\n"
    "</table>\n"
    "\n"
    "<h2>Register Detail</h2>\n"
    "\n"
    "<!-- ------------------------------------------------------------------ -->\n"
    "<h3>CTRL - Control Register (offset 0x00)</h3>\n"
    "<table>\n"
    "  <tr>\n"
    "    <th>Bits</th><th>Field</th><th>Access</th><th>Reset</th>"
    "<th>Description</th>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">31:12</td>\n"
    "    <td>reserved</td>\n"
    "    <td>-</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Reserved; read-as-zero, ignore on write.</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">11:4</td>\n"
    "    <td class=\"mono rw\">PRESCALE[7:0]</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0x00</td>\n"
    "    <td>Clock pre-scale value. Divide ratio = PRESCALE + 1. "
    "Value 0 means divide-by-1 (no division).</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">3</td>\n"
    "    <td class=\"mono rw\">TRIG_EN</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>External trigger output enable. When set, the trigger output is\n"
    "        asserted for one clock cycle when the counter reaches 0.</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">2</td>\n"
    "    <td class=\"mono rw\">INTR_EN</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Interrupt enable. Gates STATUS.INTR to the interrupt output.</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">1</td>\n"
    "    <td class=\"mono rw\">MODE</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Operating mode. 0 = repeat/free-run (auto-reload on underflow). "
    "1 = one-shot (stop after first underflow).</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td class=\"mono rw\">EN</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Timer enable. 1 = timer counting; 0 = timer halted.</td>\n"
    "  </tr>\n"
    "</table>\n"
    "\n"
    "<!-- ------------------------------------------------------------------ -->\n"
    "<h3>STATUS - Status Register (offset 0x04)</h3>\n"
    "<table>\n"
    "  <tr>\n"
    "    <th>Bits</th><th>Field</th><th>Access</th><th>Reset</th>"
    "<th>Description</th>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">31:2</td>\n"
    "    <td>reserved</td>\n"
    "    <td>-</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Reserved; read-as-zero.</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">1</td>\n"
    "    <td class=\"mono ro\">ACTIVE</td>\n"
    "    <td class=\"ro\">RO</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Timer is running. Set/cleared by hardware; reflects\n"
    "        <code>CTRL.EN</code> qualified by one-shot completion state.</td>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td class=\"mono w1c\">INTR</td>\n"
    "    <td class=\"w1c\">W1C</td>\n"
    "    <td class=\"mono\">0</td>\n"
    "    <td>Interrupt pending. Set by hardware when the counter reaches 0.\n"
    "        Clear by writing 1 to this bit. Raw interrupt - not gated by\n"
    "        <code>CTRL.INTR_EN</code>.</td>\n"
    "  </tr>\n"
    "</table>\n"
    "\n"
    "<!-- ------------------------------------------------------------------ -->\n"
    "<h3>LOAD - Load Register (offset 0x08)</h3>\n"
    "<table>\n"
    "  <tr>\n"
    "    <th>Bits</th><th>Field</th><th>Access</th><th>Reset</th>"
    "<th>Description</th>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">31:0</td>\n"
    "    <td class=\"mono rw\">VALUE[31:0]</td>\n"
    "    <td class=\"rw\">RW</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>32-bit reload value. Loaded into the counter when the timer is\n"
    "        enabled and, in repeat mode, on every underflow.</td>\n"
    "  </tr>\n"
    "</table>\n"
    "\n"
    "<!-- ------------------------------------------------------------------ -->\n"
    "<h3>COUNT - Count Register (offset 0x0C)</h3>\n"
    "<table>\n"
    "  <tr>\n"
    "    <th>Bits</th><th>Field</th><th>Access</th><th>Reset</th>"
    "<th>Description</th>\n"
    "  </tr>\n"
    "  <tr>\n"
    "    <td class=\"mono\">31:0</td>\n"
    "    <td class=\"mono ro\">VALUE[31:0]</td>\n"
    "    <td class=\"ro\">RO</td>\n"
    "    <td class=\"mono\">0x0000_0000</td>\n"
    "    <td>Current value of the 32-bit down-counter. Updated by hardware every\n"
    "        prescaled clock cycle. Writes are ignored.</td>\n"
    "  </tr>\n"
    "</table>\n"
    "\n"
    "<hr>\n"
    "<p class=\"note\">Generated by <code>generate_timer.py</code> on behalf of the\n"
    "Claude_IP project. Timer IP register file version 1.0.</p>\n"
    "\n"
    "</body>\n"
    "</html>\n"
)


# ---------------------------------------------------------------------------
# Write helper
# ---------------------------------------------------------------------------
def _write_file(path, content):
    # type: (str, str) -> None
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write(content)
    print("  wrote " + path)


# ---------------------------------------------------------------------------
# PeakRDL path (attempted first)
# ---------------------------------------------------------------------------
def _try_peakrdl(rdl_file, outdir_sv, outdir_vhdl, outdir_c, outdir_html):
    # type: (str, str, str, str, str) -> bool
    """Attempt to generate outputs via PeakRDL. Returns True on success."""
    try:
        import peakrdl  # noqa: F401 - probe only
        from peakrdl.core import RDLCompiler  # noqa: F401
    except ImportError:
        return False

    try:
        import subprocess
        cmds = [
            ["peakrdl", "regblock", rdl_file, "-o", outdir_sv, "--type", "sv"],
            ["peakrdl", "regblock", rdl_file, "-o", outdir_vhdl, "--type", "vhdl"],
            ["peakrdl", "c-header", rdl_file, "-o", outdir_c],
            ["peakrdl", "html",     rdl_file, "-o", outdir_html],
        ]
        for cmd in cmds:
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                print("WARNING: PeakRDL command failed: " + " ".join(cmd))
                print(result.stderr)
                return False
        return True
    except Exception as exc:  # noqa: BLE001
        print("WARNING: PeakRDL generation failed: " + str(exc))
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    # type: () -> None
    timer_path = _require_env()

    parser = argparse.ArgumentParser(
        description="Generate timer outputs from SystemRDL source."
    )
    parser.add_argument(
        "--rdl",
        default=os.path.join(timer_path, "design", "systemrdl", "timer.rdl"),
        help="Path to the SystemRDL source file (default: %(default)s)",
    )
    parser.add_argument(
        "--outdir-sv",
        default=os.path.join(timer_path, "design", "rtl", "verilog"),
        help="Output directory for generated SystemVerilog (default: %(default)s)",
    )
    parser.add_argument(
        "--outdir-vhdl",
        default=os.path.join(timer_path, "design", "rtl", "vhdl"),
        help="Output directory for generated VHDL-2008 (default: %(default)s)",
    )
    parser.add_argument(
        "--outdir-c",
        default=os.path.join(timer_path, "firmware", "include"),
        help="Output directory for generated C header (default: %(default)s)",
    )
    parser.add_argument(
        "--outdir-html",
        default=os.path.join(timer_path, "doc"),
        help="Output directory for generated HTML documentation (default: %(default)s)",
    )
    args = parser.parse_args()

    print("generate_timer.py: generating all outputs ...")

    # Try PeakRDL first; fall back to hand-generation if unavailable.
    used_peakrdl = _try_peakrdl(
        args.rdl,
        args.outdir_sv,
        args.outdir_vhdl,
        args.outdir_c,
        args.outdir_html,
    )

    if used_peakrdl:
        print("  PeakRDL generation successful.")
    else:
        print("  PeakRDL not available - using hand-generation fallback.")
        _write_file(os.path.join(args.outdir_sv,   "timer_reg_pkg.sv"),  SV_PKG)
        _write_file(os.path.join(args.outdir_sv,   "timer_regfile.sv"),  SV_REGFILE)
        _write_file(os.path.join(args.outdir_vhdl, "timer_reg_pkg.vhd"), VHD_PKG)
        _write_file(os.path.join(args.outdir_vhdl, "timer_regfile.vhd"), VHD_REGFILE)
        _write_file(os.path.join(args.outdir_c,    "timer_regs.h"),      C_HEADER)
        _write_file(os.path.join(args.outdir_html, "timer_regs.html"),   HTML_DOC)

    print("generate_timer.py: done.")


if __name__ == "__main__":
    main()
