/* Generated by Yosys 0.60+36 (git sha1 2833a4450, clang++ 18.1.8 -fPIC -O3) */

module timer_apb(PCLK, PRESETn, PSEL, PENABLE, PADDR, PWRITE, PWDATA, PSTRB, PRDATA, PREADY, PSLVERR, irq, trigger_out);
  input PCLK;
  wire PCLK;
  input PRESETn;
  wire PRESETn;
  input PSEL;
  wire PSEL;
  input PENABLE;
  wire PENABLE;
  input [11:0] PADDR;
  wire [11:0] PADDR;
  input PWRITE;
  wire PWRITE;
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  input [3:0] PSTRB;
  wire [3:0] PSTRB;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  output PREADY;
  wire PREADY;
  output PSLVERR;
  wire PSLVERR;
  output irq;
  wire irq;
  output trigger_out;
  wire trigger_out;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire [31:0] _0430_;
  wire ctrl_en;
  wire ctrl_intr_en;
  wire ctrl_mode;
  wire [7:0] ctrl_prescale;
  wire ctrl_trig_en;
  wire hw_active;
  wire [31:0] hw_count_val;
  wire hw_intr_set;
  wire [3:0] if_rd_addr;
  wire [31:0] if_rd_data;
  wire if_rd_en;
  wire [3:0] if_wr_addr;
  wire [31:0] if_wr_data;
  wire [3:0] if_wr_strb;
  wire [31:0] load_val;
  wire status_intr;
  wire [11:0] \u_apb_if.PADDR ;
  wire \u_apb_if.PCLK ;
  wire \u_apb_if.PENABLE ;
  wire [31:0] \u_apb_if.PRDATA ;
  wire \u_apb_if.PREADY ;
  wire \u_apb_if.PRESETn ;
  wire \u_apb_if.PSEL ;
  wire \u_apb_if.PSLVERR ;
  wire [3:0] \u_apb_if.PSTRB ;
  wire [31:0] \u_apb_if.PWDATA ;
  wire \u_apb_if.PWRITE ;
  wire [3:0] \u_apb_if.rd_addr ;
  wire [31:0] \u_apb_if.rd_data ;
  wire \u_apb_if.rd_en ;
  wire [3:0] \u_apb_if.wr_addr ;
  wire [31:0] \u_apb_if.wr_data ;
  wire [3:0] \u_apb_if.wr_strb ;
  reg \u_core.active_q ;
  wire \u_core.clk ;
  reg [31:0] \u_core.count_q ;
  wire \u_core.ctrl_en ;
  wire \u_core.ctrl_intr_en ;
  wire \u_core.ctrl_mode ;
  wire [7:0] \u_core.ctrl_prescale ;
  wire \u_core.ctrl_trig_en ;
  reg \u_core.en_prev_q ;
  wire \u_core.hw_active ;
  wire [31:0] \u_core.hw_count_val ;
  reg \u_core.hw_intr_set ;
  wire \u_core.irq ;
  wire [31:0] \u_core.load_val ;
  reg [7:0] \u_core.prescale_cnt_q ;
  wire \u_core.rst_n ;
  wire \u_core.status_intr ;
  reg \u_core.trigger_out ;
  wire \u_core.underflow ;
  wire \u_regfile.clk ;
  reg [31:0] \u_regfile.count_q ;
  wire \u_regfile.ctrl_en ;
  wire \u_regfile.ctrl_intr_en ;
  wire \u_regfile.ctrl_mode ;
  wire [7:0] \u_regfile.ctrl_prescale ;
  wire [31:0] \u_regfile.ctrl_q ;
  wire \u_regfile.ctrl_trig_en ;
  wire \u_regfile.hw_active ;
  wire [31:0] \u_regfile.hw_count_val ;
  wire \u_regfile.hw_intr_set ;
  reg [31:0] \u_regfile.load_q ;
  wire [31:0] \u_regfile.load_val ;
  wire [3:0] \u_regfile.rd_addr ;
  reg [31:0] \u_regfile.rd_data ;
  wire \u_regfile.rd_en ;
  wire \u_regfile.rst_n ;
  wire \u_regfile.status_intr ;
  wire [31:0] \u_regfile.status_q ;
  wire [3:0] \u_regfile.wr_addr ;
  wire [31:0] \u_regfile.wr_data ;
  wire [3:0] \u_regfile.wr_strb ;
  assign _0051_ = ~PWRITE;
  assign _0052_ = PENABLE | ~(PSEL);
  assign if_rd_en = _0051_ & ~(_0052_);
  assign _0053_ = ~(\u_core.prescale_cnt_q [0] | \u_core.prescale_cnt_q [1]);
  assign _0054_ = ~(\u_core.prescale_cnt_q [2] | \u_core.prescale_cnt_q [3]);
  assign _0055_ = _0054_ & _0053_;
  assign _0056_ = ~(\u_core.prescale_cnt_q [4] | \u_core.prescale_cnt_q [5]);
  assign _0057_ = ~(\u_core.prescale_cnt_q [7] | \u_core.prescale_cnt_q [6]);
  assign _0058_ = ~(_0057_ & _0056_);
  assign _0059_ = _0055_ & ~(_0058_);
  assign _0060_ = ~(_0059_ & \u_regfile.ctrl_q [0]);
  assign _0061_ = \u_core.active_q  & ~(_0060_);
  assign _0062_ = _0061_ & ~(\u_regfile.ctrl_q [1]);
  assign _0063_ = \u_regfile.ctrl_q [0] & ~(\u_core.en_prev_q );
  assign _0010_ = _0063_ | _0062_;
  assign irq = \u_regfile.ctrl_q [2] & \u_regfile.status_q [0];
  assign _0064_ = ~(\u_core.count_q [0] | \u_core.count_q [1]);
  assign _0065_ = ~(\u_core.count_q [3] | \u_core.count_q [2]);
  assign _0066_ = _0065_ & _0064_;
  assign _0067_ = ~(\u_core.count_q [5] | \u_core.count_q [4]);
  assign _0068_ = ~(\u_core.count_q [7] | \u_core.count_q [6]);
  assign _0069_ = _0068_ & _0067_;
  assign _0070_ = _0069_ & _0066_;
  assign _0071_ = \u_core.count_q [9] | \u_core.count_q [8];
  assign _0072_ = \u_core.count_q [11] | \u_core.count_q [10];
  assign _0073_ = _0072_ | _0071_;
  assign _0074_ = \u_core.count_q [13] | \u_core.count_q [12];
  assign _0075_ = ~(\u_core.count_q [15] | \u_core.count_q [14]);
  assign _0076_ = _0074_ | ~(_0075_);
  assign _0077_ = _0076_ | _0073_;
  assign _0078_ = _0070_ & ~(_0077_);
  assign _0079_ = ~(\u_core.count_q [17] | \u_core.count_q [16]);
  assign _0080_ = ~(\u_core.count_q [19] | \u_core.count_q [18]);
  assign _0081_ = _0080_ & _0079_;
  assign _0082_ = \u_core.count_q [21] | \u_core.count_q [20];
  assign _0083_ = ~(\u_core.count_q [23] | \u_core.count_q [22]);
  assign _0084_ = _0082_ | ~(_0083_);
  assign _0085_ = _0081_ & ~(_0084_);
  assign _0086_ = ~(\u_core.count_q [25] | \u_core.count_q [24]);
  assign _0087_ = ~(\u_core.count_q [27] | \u_core.count_q [26]);
  assign _0088_ = _0087_ & _0086_;
  assign _0089_ = ~(\u_core.count_q [29] | \u_core.count_q [28]);
  assign _0090_ = ~(\u_core.count_q [31] | \u_core.count_q [30]);
  assign _0091_ = _0090_ & _0089_;
  assign _0092_ = _0091_ & _0088_;
  assign _0093_ = ~(_0092_ & _0085_);
  assign _0094_ = _0078_ & ~(_0093_);
  assign \u_core.underflow  = _0094_ & _0061_;
  assign _0009_ = \u_core.underflow  & \u_regfile.ctrl_q [3];
  assign _0095_ = ~(PENABLE & PSEL);
  assign _0096_ = _0095_ | _0051_;
  assign _0097_ = PADDR[2] & ~(PADDR[3]);
  assign _0098_ = PADDR[5] | PADDR[4];
  assign _0099_ = _0097_ & ~(_0098_);
  assign _0100_ = _0099_ & ~(_0096_);
  assign _0101_ = ~(_0100_ & PSTRB[0]);
  assign _0102_ = PWDATA[0] & ~(_0101_);
  assign _0001_ = _0102_ | \u_core.hw_intr_set ;
  assign _0000_ = _0063_ | _0061_;
  assign _0103_ = _0094_ | ~(_0061_);
  assign _0104_ = _0103_ | _0063_;
  assign _0105_ = ~\u_regfile.ctrl_q [0];
  assign _0106_ = _0061_ | _0105_;
  assign _0107_ = ~(_0106_ | _0063_);
  assign _0008_ = _0104_ & ~(_0107_);
  assign _0108_ = PADDR[2] | ~(PADDR[3]);
  assign _0109_ = _0108_ | _0098_;
  assign _0110_ = _0109_ | _0096_;
  assign _0007_ = PSTRB[3] & ~(_0110_);
  assign _0006_ = PSTRB[2] & ~(_0110_);
  assign _0005_ = PSTRB[1] & ~(_0110_);
  assign _0004_ = PSTRB[0] & ~(_0110_);
  assign _0111_ = PADDR[3] | PADDR[2];
  assign _0112_ = ~(_0111_ | _0098_);
  assign _0113_ = _0096_ | ~(_0112_);
  assign _0003_ = PSTRB[1] & ~(_0113_);
  assign _0002_ = PSTRB[0] & ~(_0113_);
  assign _0114_ = ~\u_core.prescale_cnt_q [0];
  assign _0115_ = _0059_ ? \u_regfile.ctrl_q [4] : _0114_;
  assign _0043_ = \u_regfile.ctrl_q [0] ? _0115_ : \u_regfile.ctrl_q [4];
  assign _0116_ = ~(\u_core.prescale_cnt_q [0] ^ \u_core.prescale_cnt_q [1]);
  assign _0117_ = _0059_ ? \u_regfile.ctrl_q [5] : _0116_;
  assign _0044_ = \u_regfile.ctrl_q [0] ? _0117_ : \u_regfile.ctrl_q [5];
  assign _0118_ = _0053_ ^ \u_core.prescale_cnt_q [2];
  assign _0119_ = _0059_ ? \u_regfile.ctrl_q [6] : _0118_;
  assign _0045_ = \u_regfile.ctrl_q [0] ? _0119_ : \u_regfile.ctrl_q [6];
  assign _0120_ = _0053_ & ~(\u_core.prescale_cnt_q [2]);
  assign _0121_ = _0120_ ^ \u_core.prescale_cnt_q [3];
  assign _0122_ = _0059_ ? \u_regfile.ctrl_q [7] : _0121_;
  assign _0046_ = \u_regfile.ctrl_q [0] ? _0122_ : \u_regfile.ctrl_q [7];
  assign _0123_ = _0054_ & ~(_0053_);
  assign _0124_ = _0054_ & ~(_0123_);
  assign _0125_ = _0124_ ^ \u_core.prescale_cnt_q [4];
  assign _0126_ = _0059_ ? \u_regfile.ctrl_q [8] : _0125_;
  assign _0047_ = \u_regfile.ctrl_q [0] ? _0126_ : \u_regfile.ctrl_q [8];
  assign _0127_ = _0124_ & ~(\u_core.prescale_cnt_q [4]);
  assign _0128_ = _0127_ ^ \u_core.prescale_cnt_q [5];
  assign _0129_ = _0059_ ? \u_regfile.ctrl_q [9] : _0128_;
  assign _0048_ = \u_regfile.ctrl_q [0] ? _0129_ : \u_regfile.ctrl_q [9];
  assign _0130_ = _0056_ & ~(_0124_);
  assign _0131_ = _0056_ & ~(_0130_);
  assign _0132_ = _0131_ ^ \u_core.prescale_cnt_q [6];
  assign _0133_ = _0059_ ? \u_regfile.ctrl_q [10] : _0132_;
  assign _0049_ = \u_regfile.ctrl_q [0] ? _0133_ : \u_regfile.ctrl_q [10];
  assign _0134_ = _0131_ & ~(\u_core.prescale_cnt_q [6]);
  assign _0135_ = _0134_ ^ \u_core.prescale_cnt_q [7];
  assign _0136_ = _0059_ ? \u_regfile.ctrl_q [11] : _0135_;
  assign _0050_ = \u_regfile.ctrl_q [0] ? _0136_ : \u_regfile.ctrl_q [11];
  assign _0137_ = ~\u_core.count_q [0];
  assign _0138_ = \u_regfile.load_q [0] & ~(\u_regfile.ctrl_q [1]);
  assign _0139_ = _0094_ ? _0138_ : _0137_;
  assign _0011_ = _0063_ ? \u_regfile.load_q [0] : _0139_;
  assign _0140_ = \u_regfile.load_q [1] & ~(\u_regfile.ctrl_q [1]);
  assign _0141_ = ~(\u_core.count_q [0] ^ \u_core.count_q [1]);
  assign _0142_ = _0094_ ? _0140_ : _0141_;
  assign _0022_ = _0063_ ? \u_regfile.load_q [1] : _0142_;
  assign _0143_ = \u_regfile.load_q [2] & ~(\u_regfile.ctrl_q [1]);
  assign _0144_ = _0064_ ^ \u_core.count_q [2];
  assign _0145_ = _0094_ ? _0143_ : _0144_;
  assign _0033_ = _0063_ ? \u_regfile.load_q [2] : _0145_;
  assign _0146_ = \u_regfile.load_q [3] & ~(\u_regfile.ctrl_q [1]);
  assign _0147_ = _0064_ & ~(\u_core.count_q [2]);
  assign _0148_ = _0147_ ^ \u_core.count_q [3];
  assign _0149_ = _0094_ ? _0146_ : _0148_;
  assign _0036_ = _0063_ ? \u_regfile.load_q [3] : _0149_;
  assign _0150_ = \u_regfile.load_q [4] & ~(\u_regfile.ctrl_q [1]);
  assign _0151_ = _0065_ & ~(_0064_);
  assign _0152_ = _0065_ & ~(_0151_);
  assign _0153_ = _0152_ ^ \u_core.count_q [4];
  assign _0154_ = _0094_ ? _0150_ : _0153_;
  assign _0037_ = _0063_ ? \u_regfile.load_q [4] : _0154_;
  assign _0155_ = \u_regfile.load_q [5] & ~(\u_regfile.ctrl_q [1]);
  assign _0156_ = _0152_ & ~(\u_core.count_q [4]);
  assign _0157_ = _0156_ ^ \u_core.count_q [5];
  assign _0158_ = _0094_ ? _0155_ : _0157_;
  assign _0038_ = _0063_ ? \u_regfile.load_q [5] : _0158_;
  assign _0159_ = \u_regfile.load_q [6] & ~(\u_regfile.ctrl_q [1]);
  assign _0160_ = _0067_ & ~(_0152_);
  assign _0161_ = _0067_ & ~(_0160_);
  assign _0162_ = _0161_ ^ \u_core.count_q [6];
  assign _0163_ = _0094_ ? _0159_ : _0162_;
  assign _0039_ = _0063_ ? \u_regfile.load_q [6] : _0163_;
  assign _0164_ = \u_regfile.load_q [7] & ~(\u_regfile.ctrl_q [1]);
  assign _0165_ = _0161_ & ~(\u_core.count_q [6]);
  assign _0166_ = _0165_ ^ \u_core.count_q [7];
  assign _0167_ = _0094_ ? _0164_ : _0166_;
  assign _0040_ = _0063_ ? \u_regfile.load_q [7] : _0167_;
  assign _0168_ = \u_regfile.load_q [8] & ~(\u_regfile.ctrl_q [1]);
  assign _0169_ = _0068_ & ~(_0067_);
  assign _0170_ = _0068_ & ~(_0169_);
  assign _0171_ = _0069_ & ~(_0152_);
  assign _0172_ = _0170_ & ~(_0171_);
  assign _0173_ = _0172_ ^ \u_core.count_q [8];
  assign _0174_ = _0094_ ? _0168_ : _0173_;
  assign _0041_ = _0063_ ? \u_regfile.load_q [8] : _0174_;
  assign _0175_ = \u_regfile.load_q [9] & ~(\u_regfile.ctrl_q [1]);
  assign _0176_ = _0172_ & ~(\u_core.count_q [8]);
  assign _0177_ = _0176_ ^ \u_core.count_q [9];
  assign _0178_ = _0094_ ? _0175_ : _0177_;
  assign _0042_ = _0063_ ? \u_regfile.load_q [9] : _0178_;
  assign _0179_ = \u_regfile.load_q [10] & ~(\u_regfile.ctrl_q [1]);
  assign _0180_ = ~(\u_core.count_q [9] | \u_core.count_q [8]);
  assign _0181_ = ~(_0172_ | _0071_);
  assign _0182_ = _0180_ & ~(_0181_);
  assign _0183_ = _0182_ ^ \u_core.count_q [10];
  assign _0184_ = _0094_ ? _0179_ : _0183_;
  assign _0012_ = _0063_ ? \u_regfile.load_q [10] : _0184_;
  assign _0185_ = \u_regfile.load_q [11] & ~(\u_regfile.ctrl_q [1]);
  assign _0186_ = _0182_ & ~(\u_core.count_q [10]);
  assign _0187_ = _0186_ ^ \u_core.count_q [11];
  assign _0188_ = _0094_ ? _0185_ : _0187_;
  assign _0013_ = _0063_ ? \u_regfile.load_q [11] : _0188_;
  assign _0189_ = \u_regfile.load_q [12] & ~(\u_regfile.ctrl_q [1]);
  assign _0190_ = ~(\u_core.count_q [11] | \u_core.count_q [10]);
  assign _0191_ = ~(_0180_ | _0072_);
  assign _0192_ = _0190_ & ~(_0191_);
  assign _0193_ = ~(_0172_ | _0073_);
  assign _0194_ = _0192_ & ~(_0193_);
  assign _0195_ = _0194_ ^ \u_core.count_q [12];
  assign _0196_ = _0094_ ? _0189_ : _0195_;
  assign _0014_ = _0063_ ? \u_regfile.load_q [12] : _0196_;
  assign _0197_ = \u_regfile.load_q [13] & ~(\u_regfile.ctrl_q [1]);
  assign _0198_ = _0194_ & ~(\u_core.count_q [12]);
  assign _0199_ = _0198_ ^ \u_core.count_q [13];
  assign _0200_ = _0094_ ? _0197_ : _0199_;
  assign _0015_ = _0063_ ? \u_regfile.load_q [13] : _0200_;
  assign _0201_ = \u_regfile.load_q [14] & ~(\u_regfile.ctrl_q [1]);
  assign _0202_ = ~\u_core.count_q [14];
  assign _0203_ = ~(\u_core.count_q [13] | \u_core.count_q [12]);
  assign _0204_ = ~(_0194_ | _0074_);
  assign _0205_ = _0204_ | ~(_0203_);
  assign _0206_ = _0205_ ^ _0202_;
  assign _0207_ = _0094_ ? _0201_ : _0206_;
  assign _0016_ = _0063_ ? \u_regfile.load_q [14] : _0207_;
  assign _0208_ = \u_regfile.load_q [15] & ~(\u_regfile.ctrl_q [1]);
  assign _0209_ = _0202_ & ~(_0205_);
  assign _0210_ = _0209_ ^ \u_core.count_q [15];
  assign _0211_ = _0094_ ? _0208_ : _0210_;
  assign _0017_ = _0063_ ? \u_regfile.load_q [15] : _0211_;
  assign _0212_ = \u_regfile.load_q [16] & ~(\u_regfile.ctrl_q [1]);
  assign _0213_ = _0075_ & ~(_0203_);
  assign _0214_ = _0075_ & ~(_0213_);
  assign _0215_ = ~(_0192_ | _0076_);
  assign _0216_ = _0214_ & ~(_0215_);
  assign _0217_ = ~(_0172_ | _0077_);
  assign _0218_ = _0216_ & ~(_0217_);
  assign _0219_ = _0218_ ^ \u_core.count_q [16];
  assign _0220_ = _0094_ ? _0212_ : _0219_;
  assign _0018_ = _0063_ ? \u_regfile.load_q [16] : _0220_;
  assign _0221_ = \u_regfile.load_q [17] & ~(\u_regfile.ctrl_q [1]);
  assign _0222_ = _0218_ & ~(\u_core.count_q [16]);
  assign _0223_ = _0222_ ^ \u_core.count_q [17];
  assign _0224_ = _0094_ ? _0221_ : _0223_;
  assign _0019_ = _0063_ ? \u_regfile.load_q [17] : _0224_;
  assign _0225_ = \u_regfile.load_q [18] & ~(\u_regfile.ctrl_q [1]);
  assign _0226_ = ~\u_core.count_q [18];
  assign _0227_ = _0079_ & ~(_0218_);
  assign _0228_ = _0227_ | ~(_0079_);
  assign _0229_ = _0228_ ^ _0226_;
  assign _0230_ = _0094_ ? _0225_ : _0229_;
  assign _0020_ = _0063_ ? \u_regfile.load_q [18] : _0230_;
  assign _0231_ = \u_regfile.load_q [19] & ~(\u_regfile.ctrl_q [1]);
  assign _0232_ = _0226_ & ~(_0228_);
  assign _0233_ = _0232_ ^ \u_core.count_q [19];
  assign _0234_ = _0094_ ? _0231_ : _0233_;
  assign _0021_ = _0063_ ? \u_regfile.load_q [19] : _0234_;
  assign _0235_ = \u_regfile.load_q [20] & ~(\u_regfile.ctrl_q [1]);
  assign _0236_ = _0080_ & ~(_0079_);
  assign _0237_ = _0080_ & ~(_0236_);
  assign _0238_ = _0081_ & ~(_0218_);
  assign _0239_ = _0237_ & ~(_0238_);
  assign _0240_ = _0239_ ^ \u_core.count_q [20];
  assign _0241_ = _0094_ ? _0235_ : _0240_;
  assign _0023_ = _0063_ ? \u_regfile.load_q [20] : _0241_;
  assign _0242_ = \u_regfile.load_q [21] & ~(\u_regfile.ctrl_q [1]);
  assign _0243_ = _0239_ & ~(\u_core.count_q [20]);
  assign _0244_ = _0243_ ^ \u_core.count_q [21];
  assign _0245_ = _0094_ ? _0242_ : _0244_;
  assign _0024_ = _0063_ ? \u_regfile.load_q [21] : _0245_;
  assign _0246_ = \u_regfile.load_q [22] & ~(\u_regfile.ctrl_q [1]);
  assign _0247_ = ~\u_core.count_q [22];
  assign _0248_ = ~(\u_core.count_q [21] | \u_core.count_q [20]);
  assign _0249_ = ~(_0239_ | _0082_);
  assign _0250_ = _0249_ | ~(_0248_);
  assign _0251_ = _0250_ ^ _0247_;
  assign _0252_ = _0094_ ? _0246_ : _0251_;
  assign _0025_ = _0063_ ? \u_regfile.load_q [22] : _0252_;
  assign _0253_ = \u_regfile.load_q [23] & ~(\u_regfile.ctrl_q [1]);
  assign _0254_ = _0247_ & ~(_0250_);
  assign _0255_ = _0254_ ^ \u_core.count_q [23];
  assign _0256_ = _0094_ ? _0253_ : _0255_;
  assign _0026_ = _0063_ ? \u_regfile.load_q [23] : _0256_;
  assign _0257_ = \u_regfile.load_q [24] & ~(\u_regfile.ctrl_q [1]);
  assign _0258_ = _0083_ & ~(_0248_);
  assign _0259_ = _0083_ & ~(_0258_);
  assign _0260_ = ~(_0237_ | _0084_);
  assign _0261_ = _0259_ & ~(_0260_);
  assign _0262_ = _0085_ & ~(_0218_);
  assign _0263_ = _0261_ & ~(_0262_);
  assign _0264_ = _0263_ ^ \u_core.count_q [24];
  assign _0265_ = _0094_ ? _0257_ : _0264_;
  assign _0027_ = _0063_ ? \u_regfile.load_q [24] : _0265_;
  assign _0266_ = \u_regfile.load_q [25] & ~(\u_regfile.ctrl_q [1]);
  assign _0267_ = _0263_ & ~(\u_core.count_q [24]);
  assign _0268_ = _0267_ ^ \u_core.count_q [25];
  assign _0269_ = _0094_ ? _0266_ : _0268_;
  assign _0028_ = _0063_ ? \u_regfile.load_q [25] : _0269_;
  assign _0270_ = \u_regfile.load_q [26] & ~(\u_regfile.ctrl_q [1]);
  assign _0271_ = ~\u_core.count_q [26];
  assign _0272_ = _0086_ & ~(_0263_);
  assign _0273_ = _0272_ | ~(_0086_);
  assign _0274_ = _0273_ ^ _0271_;
  assign _0275_ = _0094_ ? _0270_ : _0274_;
  assign _0029_ = _0063_ ? \u_regfile.load_q [26] : _0275_;
  assign _0276_ = \u_regfile.load_q [27] & ~(\u_regfile.ctrl_q [1]);
  assign _0277_ = _0271_ & ~(_0273_);
  assign _0278_ = _0277_ ^ \u_core.count_q [27];
  assign _0279_ = _0094_ ? _0276_ : _0278_;
  assign _0030_ = _0063_ ? \u_regfile.load_q [27] : _0279_;
  assign _0280_ = \u_regfile.load_q [28] & ~(\u_regfile.ctrl_q [1]);
  assign _0281_ = _0087_ & ~(_0086_);
  assign _0282_ = _0087_ & ~(_0281_);
  assign _0283_ = _0088_ & ~(_0263_);
  assign _0284_ = _0282_ & ~(_0283_);
  assign _0285_ = _0284_ ^ \u_core.count_q [28];
  assign _0286_ = _0094_ ? _0280_ : _0285_;
  assign _0031_ = _0063_ ? \u_regfile.load_q [28] : _0286_;
  assign _0287_ = \u_regfile.load_q [29] & ~(\u_regfile.ctrl_q [1]);
  assign _0288_ = _0284_ & ~(\u_core.count_q [28]);
  assign _0289_ = _0288_ ^ \u_core.count_q [29];
  assign _0290_ = _0094_ ? _0287_ : _0289_;
  assign _0032_ = _0063_ ? \u_regfile.load_q [29] : _0290_;
  assign _0291_ = \u_regfile.load_q [30] & ~(\u_regfile.ctrl_q [1]);
  assign _0292_ = ~\u_core.count_q [30];
  assign _0293_ = _0089_ & ~(_0284_);
  assign _0294_ = _0293_ | ~(_0089_);
  assign _0295_ = _0294_ ^ _0292_;
  assign _0296_ = _0094_ ? _0291_ : _0295_;
  assign _0034_ = _0063_ ? \u_regfile.load_q [30] : _0296_;
  assign _0297_ = \u_regfile.load_q [31] & ~(\u_regfile.ctrl_q [1]);
  assign _0298_ = _0292_ & ~(_0294_);
  assign _0299_ = _0298_ ^ \u_core.count_q [31];
  assign _0300_ = _0094_ ? _0297_ : _0299_;
  assign _0035_ = _0063_ ? \u_regfile.load_q [31] : _0300_;
  assign _0301_ = ~(PADDR[3] & PADDR[2]);
  assign _0302_ = _0301_ | _0098_;
  assign _0303_ = \u_regfile.count_q [0] & ~(_0302_);
  assign _0304_ = \u_regfile.load_q [0] & ~(_0109_);
  assign _0305_ = _0304_ | _0303_;
  assign _0306_ = _0099_ & \u_regfile.status_q [0];
  assign _0307_ = _0112_ & ~(_0105_);
  assign _0308_ = _0307_ | _0306_;
  assign _0309_ = _0308_ | _0305_;
  assign _0310_ = ~(_0302_ & _0109_);
  assign _0311_ = _0112_ | _0099_;
  assign _0312_ = _0311_ | _0310_;
  assign _0430_[0] = _0312_ & _0309_;
  assign _0313_ = _0302_ | ~(\u_regfile.count_q [1]);
  assign _0314_ = \u_regfile.load_q [1] & ~(_0109_);
  assign _0315_ = _0313_ & ~(_0314_);
  assign _0316_ = _0099_ & \u_regfile.status_q [1];
  assign _0317_ = _0112_ & \u_regfile.ctrl_q [1];
  assign _0318_ = _0317_ | _0316_;
  assign _0319_ = _0315_ & ~(_0318_);
  assign _0430_[1] = _0312_ & ~(_0319_);
  assign _0320_ = _0302_ | ~(\u_regfile.count_q [2]);
  assign _0321_ = \u_regfile.load_q [2] & ~(_0109_);
  assign _0322_ = _0320_ & ~(_0321_);
  assign _0323_ = _0112_ & \u_regfile.ctrl_q [2];
  assign _0324_ = _0322_ & ~(_0323_);
  assign _0430_[2] = _0312_ & ~(_0324_);
  assign _0325_ = _0302_ | ~(\u_regfile.count_q [3]);
  assign _0326_ = \u_regfile.load_q [3] & ~(_0109_);
  assign _0327_ = _0325_ & ~(_0326_);
  assign _0328_ = _0112_ & \u_regfile.ctrl_q [3];
  assign _0329_ = _0327_ & ~(_0328_);
  assign _0430_[3] = _0312_ & ~(_0329_);
  assign _0330_ = _0302_ | ~(\u_regfile.count_q [4]);
  assign _0331_ = \u_regfile.load_q [4] & ~(_0109_);
  assign _0332_ = _0330_ & ~(_0331_);
  assign _0333_ = _0112_ & \u_regfile.ctrl_q [4];
  assign _0334_ = _0332_ & ~(_0333_);
  assign _0430_[4] = _0312_ & ~(_0334_);
  assign _0335_ = _0302_ | ~(\u_regfile.count_q [5]);
  assign _0336_ = \u_regfile.load_q [5] & ~(_0109_);
  assign _0337_ = _0335_ & ~(_0336_);
  assign _0338_ = _0112_ & \u_regfile.ctrl_q [5];
  assign _0339_ = _0337_ & ~(_0338_);
  assign _0430_[5] = _0312_ & ~(_0339_);
  assign _0340_ = _0302_ | ~(\u_regfile.count_q [6]);
  assign _0341_ = \u_regfile.load_q [6] & ~(_0109_);
  assign _0342_ = _0340_ & ~(_0341_);
  assign _0343_ = _0112_ & \u_regfile.ctrl_q [6];
  assign _0344_ = _0342_ & ~(_0343_);
  assign _0430_[6] = _0312_ & ~(_0344_);
  assign _0345_ = _0302_ | ~(\u_regfile.count_q [7]);
  assign _0346_ = \u_regfile.load_q [7] & ~(_0109_);
  assign _0347_ = _0345_ & ~(_0346_);
  assign _0348_ = _0112_ & \u_regfile.ctrl_q [7];
  assign _0349_ = _0347_ & ~(_0348_);
  assign _0430_[7] = _0312_ & ~(_0349_);
  assign _0350_ = _0302_ | ~(\u_regfile.count_q [8]);
  assign _0351_ = \u_regfile.load_q [8] & ~(_0109_);
  assign _0352_ = _0350_ & ~(_0351_);
  assign _0353_ = _0112_ & \u_regfile.ctrl_q [8];
  assign _0354_ = _0352_ & ~(_0353_);
  assign _0430_[8] = _0312_ & ~(_0354_);
  assign _0355_ = _0302_ | ~(\u_regfile.count_q [9]);
  assign _0356_ = \u_regfile.load_q [9] & ~(_0109_);
  assign _0357_ = _0355_ & ~(_0356_);
  assign _0358_ = _0112_ & \u_regfile.ctrl_q [9];
  assign _0359_ = _0357_ & ~(_0358_);
  assign _0430_[9] = _0312_ & ~(_0359_);
  assign _0360_ = _0302_ | ~(\u_regfile.count_q [10]);
  assign _0361_ = \u_regfile.load_q [10] & ~(_0109_);
  assign _0362_ = _0360_ & ~(_0361_);
  assign _0363_ = _0112_ & \u_regfile.ctrl_q [10];
  assign _0364_ = _0362_ & ~(_0363_);
  assign _0430_[10] = _0312_ & ~(_0364_);
  assign _0365_ = _0302_ | ~(\u_regfile.count_q [11]);
  assign _0366_ = \u_regfile.load_q [11] & ~(_0109_);
  assign _0367_ = _0365_ & ~(_0366_);
  assign _0368_ = _0112_ & \u_regfile.ctrl_q [11];
  assign _0369_ = _0367_ & ~(_0368_);
  assign _0430_[11] = _0312_ & ~(_0369_);
  assign _0370_ = _0302_ | ~(\u_regfile.count_q [12]);
  assign _0371_ = \u_regfile.load_q [12] & ~(_0109_);
  assign _0372_ = _0370_ & ~(_0371_);
  assign _0430_[12] = _0312_ & ~(_0372_);
  assign _0373_ = _0302_ | ~(\u_regfile.count_q [13]);
  assign _0374_ = \u_regfile.load_q [13] & ~(_0109_);
  assign _0375_ = _0373_ & ~(_0374_);
  assign _0430_[13] = _0312_ & ~(_0375_);
  assign _0376_ = _0302_ | ~(\u_regfile.count_q [14]);
  assign _0377_ = \u_regfile.load_q [14] & ~(_0109_);
  assign _0378_ = _0376_ & ~(_0377_);
  assign _0430_[14] = _0312_ & ~(_0378_);
  assign _0379_ = _0302_ | ~(\u_regfile.count_q [15]);
  assign _0380_ = \u_regfile.load_q [15] & ~(_0109_);
  assign _0381_ = _0379_ & ~(_0380_);
  assign _0430_[15] = _0312_ & ~(_0381_);
  assign _0382_ = _0302_ | ~(\u_regfile.count_q [16]);
  assign _0383_ = \u_regfile.load_q [16] & ~(_0109_);
  assign _0384_ = _0382_ & ~(_0383_);
  assign _0430_[16] = _0312_ & ~(_0384_);
  assign _0385_ = _0302_ | ~(\u_regfile.count_q [17]);
  assign _0386_ = \u_regfile.load_q [17] & ~(_0109_);
  assign _0387_ = _0385_ & ~(_0386_);
  assign _0430_[17] = _0312_ & ~(_0387_);
  assign _0388_ = _0302_ | ~(\u_regfile.count_q [18]);
  assign _0389_ = \u_regfile.load_q [18] & ~(_0109_);
  assign _0390_ = _0388_ & ~(_0389_);
  assign _0430_[18] = _0312_ & ~(_0390_);
  assign _0391_ = _0302_ | ~(\u_regfile.count_q [19]);
  assign _0392_ = \u_regfile.load_q [19] & ~(_0109_);
  assign _0393_ = _0391_ & ~(_0392_);
  assign _0430_[19] = _0312_ & ~(_0393_);
  assign _0394_ = _0302_ | ~(\u_regfile.count_q [20]);
  assign _0395_ = \u_regfile.load_q [20] & ~(_0109_);
  assign _0396_ = _0394_ & ~(_0395_);
  assign _0430_[20] = _0312_ & ~(_0396_);
  assign _0397_ = _0302_ | ~(\u_regfile.count_q [21]);
  assign _0398_ = \u_regfile.load_q [21] & ~(_0109_);
  assign _0399_ = _0397_ & ~(_0398_);
  assign _0430_[21] = _0312_ & ~(_0399_);
  assign _0400_ = _0302_ | ~(\u_regfile.count_q [22]);
  assign _0401_ = \u_regfile.load_q [22] & ~(_0109_);
  assign _0402_ = _0400_ & ~(_0401_);
  assign _0430_[22] = _0312_ & ~(_0402_);
  assign _0403_ = _0302_ | ~(\u_regfile.count_q [23]);
  assign _0404_ = \u_regfile.load_q [23] & ~(_0109_);
  assign _0405_ = _0403_ & ~(_0404_);
  assign _0430_[23] = _0312_ & ~(_0405_);
  assign _0406_ = _0302_ | ~(\u_regfile.count_q [24]);
  assign _0407_ = \u_regfile.load_q [24] & ~(_0109_);
  assign _0408_ = _0406_ & ~(_0407_);
  assign _0430_[24] = _0312_ & ~(_0408_);
  assign _0409_ = _0302_ | ~(\u_regfile.count_q [25]);
  assign _0410_ = \u_regfile.load_q [25] & ~(_0109_);
  assign _0411_ = _0409_ & ~(_0410_);
  assign _0430_[25] = _0312_ & ~(_0411_);
  assign _0412_ = _0302_ | ~(\u_regfile.count_q [26]);
  assign _0413_ = \u_regfile.load_q [26] & ~(_0109_);
  assign _0414_ = _0412_ & ~(_0413_);
  assign _0430_[26] = _0312_ & ~(_0414_);
  assign _0415_ = _0302_ | ~(\u_regfile.count_q [27]);
  assign _0416_ = \u_regfile.load_q [27] & ~(_0109_);
  assign _0417_ = _0415_ & ~(_0416_);
  assign _0430_[27] = _0312_ & ~(_0417_);
  assign _0418_ = _0302_ | ~(\u_regfile.count_q [28]);
  assign _0419_ = \u_regfile.load_q [28] & ~(_0109_);
  assign _0420_ = _0418_ & ~(_0419_);
  assign _0430_[28] = _0312_ & ~(_0420_);
  assign _0421_ = _0302_ | ~(\u_regfile.count_q [29]);
  assign _0422_ = \u_regfile.load_q [29] & ~(_0109_);
  assign _0423_ = _0421_ & ~(_0422_);
  assign _0430_[29] = _0312_ & ~(_0423_);
  assign _0424_ = _0302_ | ~(\u_regfile.count_q [30]);
  assign _0425_ = \u_regfile.load_q [30] & ~(_0109_);
  assign _0426_ = _0424_ & ~(_0425_);
  assign _0430_[30] = _0312_ & ~(_0426_);
  assign _0427_ = _0302_ | ~(\u_regfile.count_q [31]);
  assign _0428_ = \u_regfile.load_q [31] & ~(_0109_);
  assign _0429_ = _0427_ & ~(_0428_);
  assign _0430_[31] = _0312_ & ~(_0429_);
  reg \u_regfile.status_q_reg[1] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.status_q_reg[1]  <= 1'h0;
    else \u_regfile.status_q_reg[1]  <= \u_core.active_q ;
  assign \u_regfile.status_q [1] = \u_regfile.status_q_reg[1] ;
  reg \u_regfile.status_q_reg[0] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.status_q_reg[0]  <= 1'h0;
    else if (_0001_) \u_regfile.status_q_reg[0]  <= \u_core.hw_intr_set ;
  assign \u_regfile.status_q [0] = \u_regfile.status_q_reg[0] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.trigger_out  <= 1'h0;
    else \u_core.trigger_out  <= _0009_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.hw_intr_set  <= 1'h0;
    else \u_core.hw_intr_set  <= \u_core.underflow ;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [0] <= 1'h0;
    else if (_0000_) \u_core.count_q [0] <= _0011_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [1] <= 1'h0;
    else if (_0000_) \u_core.count_q [1] <= _0022_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [2] <= 1'h0;
    else if (_0000_) \u_core.count_q [2] <= _0033_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [3] <= 1'h0;
    else if (_0000_) \u_core.count_q [3] <= _0036_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [4] <= 1'h0;
    else if (_0000_) \u_core.count_q [4] <= _0037_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [5] <= 1'h0;
    else if (_0000_) \u_core.count_q [5] <= _0038_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [6] <= 1'h0;
    else if (_0000_) \u_core.count_q [6] <= _0039_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [7] <= 1'h0;
    else if (_0000_) \u_core.count_q [7] <= _0040_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [8] <= 1'h0;
    else if (_0000_) \u_core.count_q [8] <= _0041_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [9] <= 1'h0;
    else if (_0000_) \u_core.count_q [9] <= _0042_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [10] <= 1'h0;
    else if (_0000_) \u_core.count_q [10] <= _0012_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [11] <= 1'h0;
    else if (_0000_) \u_core.count_q [11] <= _0013_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [12] <= 1'h0;
    else if (_0000_) \u_core.count_q [12] <= _0014_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [13] <= 1'h0;
    else if (_0000_) \u_core.count_q [13] <= _0015_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [14] <= 1'h0;
    else if (_0000_) \u_core.count_q [14] <= _0016_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [15] <= 1'h0;
    else if (_0000_) \u_core.count_q [15] <= _0017_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [16] <= 1'h0;
    else if (_0000_) \u_core.count_q [16] <= _0018_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [17] <= 1'h0;
    else if (_0000_) \u_core.count_q [17] <= _0019_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [18] <= 1'h0;
    else if (_0000_) \u_core.count_q [18] <= _0020_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [19] <= 1'h0;
    else if (_0000_) \u_core.count_q [19] <= _0021_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [20] <= 1'h0;
    else if (_0000_) \u_core.count_q [20] <= _0023_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [21] <= 1'h0;
    else if (_0000_) \u_core.count_q [21] <= _0024_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [22] <= 1'h0;
    else if (_0000_) \u_core.count_q [22] <= _0025_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [23] <= 1'h0;
    else if (_0000_) \u_core.count_q [23] <= _0026_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [24] <= 1'h0;
    else if (_0000_) \u_core.count_q [24] <= _0027_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [25] <= 1'h0;
    else if (_0000_) \u_core.count_q [25] <= _0028_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [26] <= 1'h0;
    else if (_0000_) \u_core.count_q [26] <= _0029_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [27] <= 1'h0;
    else if (_0000_) \u_core.count_q [27] <= _0030_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [28] <= 1'h0;
    else if (_0000_) \u_core.count_q [28] <= _0031_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [29] <= 1'h0;
    else if (_0000_) \u_core.count_q [29] <= _0032_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [30] <= 1'h0;
    else if (_0000_) \u_core.count_q [30] <= _0034_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.count_q [31] <= 1'h0;
    else if (_0000_) \u_core.count_q [31] <= _0035_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.active_q  <= 1'h0;
    else if (_0008_) \u_core.active_q  <= _0010_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [0] <= 1'h0;
    else \u_core.prescale_cnt_q [0] <= _0043_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [1] <= 1'h0;
    else \u_core.prescale_cnt_q [1] <= _0044_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [2] <= 1'h0;
    else \u_core.prescale_cnt_q [2] <= _0045_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [3] <= 1'h0;
    else \u_core.prescale_cnt_q [3] <= _0046_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [4] <= 1'h0;
    else \u_core.prescale_cnt_q [4] <= _0047_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [5] <= 1'h0;
    else \u_core.prescale_cnt_q [5] <= _0048_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [6] <= 1'h0;
    else \u_core.prescale_cnt_q [6] <= _0049_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.prescale_cnt_q [7] <= 1'h0;
    else \u_core.prescale_cnt_q [7] <= _0050_;
  always @(posedge PCLK)
    if (!PRESETn) \u_core.en_prev_q  <= 1'h0;
    else \u_core.en_prev_q  <= \u_regfile.ctrl_q [0];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [0] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [0] <= _0430_[0];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [1] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [1] <= _0430_[1];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [2] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [2] <= _0430_[2];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [3] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [3] <= _0430_[3];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [4] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [4] <= _0430_[4];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [5] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [5] <= _0430_[5];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [6] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [6] <= _0430_[6];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [7] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [7] <= _0430_[7];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [8] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [8] <= _0430_[8];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [9] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [9] <= _0430_[9];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [10] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [10] <= _0430_[10];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [11] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [11] <= _0430_[11];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [12] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [12] <= _0430_[12];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [13] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [13] <= _0430_[13];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [14] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [14] <= _0430_[14];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [15] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [15] <= _0430_[15];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [16] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [16] <= _0430_[16];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [17] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [17] <= _0430_[17];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [18] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [18] <= _0430_[18];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [19] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [19] <= _0430_[19];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [20] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [20] <= _0430_[20];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [21] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [21] <= _0430_[21];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [22] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [22] <= _0430_[22];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [23] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [23] <= _0430_[23];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [24] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [24] <= _0430_[24];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [25] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [25] <= _0430_[25];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [26] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [26] <= _0430_[26];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [27] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [27] <= _0430_[27];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [28] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [28] <= _0430_[28];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [29] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [29] <= _0430_[29];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [30] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [30] <= _0430_[30];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.rd_data [31] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [31] <= _0430_[31];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [0] <= 1'h0;
    else \u_regfile.count_q [0] <= \u_core.count_q [0];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [1] <= 1'h0;
    else \u_regfile.count_q [1] <= \u_core.count_q [1];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [2] <= 1'h0;
    else \u_regfile.count_q [2] <= \u_core.count_q [2];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [3] <= 1'h0;
    else \u_regfile.count_q [3] <= \u_core.count_q [3];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [4] <= 1'h0;
    else \u_regfile.count_q [4] <= \u_core.count_q [4];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [5] <= 1'h0;
    else \u_regfile.count_q [5] <= \u_core.count_q [5];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [6] <= 1'h0;
    else \u_regfile.count_q [6] <= \u_core.count_q [6];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [7] <= 1'h0;
    else \u_regfile.count_q [7] <= \u_core.count_q [7];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [8] <= 1'h0;
    else \u_regfile.count_q [8] <= \u_core.count_q [8];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [9] <= 1'h0;
    else \u_regfile.count_q [9] <= \u_core.count_q [9];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [10] <= 1'h0;
    else \u_regfile.count_q [10] <= \u_core.count_q [10];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [11] <= 1'h0;
    else \u_regfile.count_q [11] <= \u_core.count_q [11];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [12] <= 1'h0;
    else \u_regfile.count_q [12] <= \u_core.count_q [12];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [13] <= 1'h0;
    else \u_regfile.count_q [13] <= \u_core.count_q [13];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [14] <= 1'h0;
    else \u_regfile.count_q [14] <= \u_core.count_q [14];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [15] <= 1'h0;
    else \u_regfile.count_q [15] <= \u_core.count_q [15];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [16] <= 1'h0;
    else \u_regfile.count_q [16] <= \u_core.count_q [16];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [17] <= 1'h0;
    else \u_regfile.count_q [17] <= \u_core.count_q [17];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [18] <= 1'h0;
    else \u_regfile.count_q [18] <= \u_core.count_q [18];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [19] <= 1'h0;
    else \u_regfile.count_q [19] <= \u_core.count_q [19];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [20] <= 1'h0;
    else \u_regfile.count_q [20] <= \u_core.count_q [20];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [21] <= 1'h0;
    else \u_regfile.count_q [21] <= \u_core.count_q [21];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [22] <= 1'h0;
    else \u_regfile.count_q [22] <= \u_core.count_q [22];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [23] <= 1'h0;
    else \u_regfile.count_q [23] <= \u_core.count_q [23];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [24] <= 1'h0;
    else \u_regfile.count_q [24] <= \u_core.count_q [24];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [25] <= 1'h0;
    else \u_regfile.count_q [25] <= \u_core.count_q [25];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [26] <= 1'h0;
    else \u_regfile.count_q [26] <= \u_core.count_q [26];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [27] <= 1'h0;
    else \u_regfile.count_q [27] <= \u_core.count_q [27];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [28] <= 1'h0;
    else \u_regfile.count_q [28] <= \u_core.count_q [28];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [29] <= 1'h0;
    else \u_regfile.count_q [29] <= \u_core.count_q [29];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [30] <= 1'h0;
    else \u_regfile.count_q [30] <= \u_core.count_q [30];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.count_q [31] <= 1'h0;
    else \u_regfile.count_q [31] <= \u_core.count_q [31];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [24] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [24] <= PWDATA[24];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [25] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [25] <= PWDATA[25];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [26] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [26] <= PWDATA[26];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [27] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [27] <= PWDATA[27];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [28] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [28] <= PWDATA[28];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [29] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [29] <= PWDATA[29];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [30] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [30] <= PWDATA[30];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [31] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [31] <= PWDATA[31];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [16] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [16] <= PWDATA[16];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [17] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [17] <= PWDATA[17];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [18] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [18] <= PWDATA[18];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [19] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [19] <= PWDATA[19];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [20] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [20] <= PWDATA[20];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [21] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [21] <= PWDATA[21];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [22] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [22] <= PWDATA[22];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [23] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [23] <= PWDATA[23];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [8] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [8] <= PWDATA[8];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [9] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [9] <= PWDATA[9];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [10] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [10] <= PWDATA[10];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [11] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [11] <= PWDATA[11];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [12] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [12] <= PWDATA[12];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [13] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [13] <= PWDATA[13];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [14] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [14] <= PWDATA[14];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [15] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [15] <= PWDATA[15];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [0] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [0] <= PWDATA[0];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [1] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [1] <= PWDATA[1];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [2] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [2] <= PWDATA[2];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [3] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [3] <= PWDATA[3];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [4] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [4] <= PWDATA[4];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [5] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [5] <= PWDATA[5];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [6] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [6] <= PWDATA[6];
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.load_q [7] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [7] <= PWDATA[7];
  reg \u_regfile.ctrl_q_reg[8] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[8]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[8]  <= PWDATA[8];
  assign \u_regfile.ctrl_q [8] = \u_regfile.ctrl_q_reg[8] ;
  reg \u_regfile.ctrl_q_reg[9] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[9]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[9]  <= PWDATA[9];
  assign \u_regfile.ctrl_q [9] = \u_regfile.ctrl_q_reg[9] ;
  reg \u_regfile.ctrl_q_reg[10] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[10]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[10]  <= PWDATA[10];
  assign \u_regfile.ctrl_q [10] = \u_regfile.ctrl_q_reg[10] ;
  reg \u_regfile.ctrl_q_reg[11] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[11]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[11]  <= PWDATA[11];
  assign \u_regfile.ctrl_q [11] = \u_regfile.ctrl_q_reg[11] ;
  reg \u_regfile.ctrl_q_reg[0] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[0]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[0]  <= PWDATA[0];
  assign \u_regfile.ctrl_q [0] = \u_regfile.ctrl_q_reg[0] ;
  reg \u_regfile.ctrl_q_reg[1] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[1]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[1]  <= PWDATA[1];
  assign \u_regfile.ctrl_q [1] = \u_regfile.ctrl_q_reg[1] ;
  reg \u_regfile.ctrl_q_reg[2] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[2]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[2]  <= PWDATA[2];
  assign \u_regfile.ctrl_q [2] = \u_regfile.ctrl_q_reg[2] ;
  reg \u_regfile.ctrl_q_reg[3] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[3]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[3]  <= PWDATA[3];
  assign \u_regfile.ctrl_q [3] = \u_regfile.ctrl_q_reg[3] ;
  reg \u_regfile.ctrl_q_reg[4] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[4]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[4]  <= PWDATA[4];
  assign \u_regfile.ctrl_q [4] = \u_regfile.ctrl_q_reg[4] ;
  reg \u_regfile.ctrl_q_reg[5] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[5]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[5]  <= PWDATA[5];
  assign \u_regfile.ctrl_q [5] = \u_regfile.ctrl_q_reg[5] ;
  reg \u_regfile.ctrl_q_reg[6] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[6]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[6]  <= PWDATA[6];
  assign \u_regfile.ctrl_q [6] = \u_regfile.ctrl_q_reg[6] ;
  reg \u_regfile.ctrl_q_reg[7] ;
  always @(posedge PCLK)
    if (!PRESETn) \u_regfile.ctrl_q_reg[7]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[7]  <= PWDATA[7];
  assign \u_regfile.ctrl_q [7] = \u_regfile.ctrl_q_reg[7] ;
  assign PRDATA = \u_regfile.rd_data ;
  assign PREADY = 1'h1;
  assign PSLVERR = 1'h0;
  assign ctrl_en = \u_regfile.ctrl_q [0];
  assign ctrl_intr_en = \u_regfile.ctrl_q [2];
  assign ctrl_mode = \u_regfile.ctrl_q [1];
  assign ctrl_prescale = \u_regfile.ctrl_q [11:4];
  assign ctrl_trig_en = \u_regfile.ctrl_q [3];
  assign hw_active = \u_core.active_q ;
  assign hw_count_val = \u_core.count_q ;
  assign hw_intr_set = \u_core.hw_intr_set ;
  assign if_rd_addr = PADDR[5:2];
  assign if_rd_data = \u_regfile.rd_data ;
  assign if_wr_addr = PADDR[5:2];
  assign if_wr_data = PWDATA;
  assign if_wr_strb = PSTRB;
  assign load_val = \u_regfile.load_q ;
  assign status_intr = \u_regfile.status_q [0];
  assign trigger_out = \u_core.trigger_out ;
  assign \u_apb_if.PADDR  = PADDR;
  assign \u_apb_if.PCLK  = PCLK;
  assign \u_apb_if.PENABLE  = PENABLE;
  assign \u_apb_if.PRDATA  = \u_regfile.rd_data ;
  assign \u_apb_if.PREADY  = 1'h1;
  assign \u_apb_if.PRESETn  = PRESETn;
  assign \u_apb_if.PSEL  = PSEL;
  assign \u_apb_if.PSLVERR  = 1'h0;
  assign \u_apb_if.PSTRB  = PSTRB;
  assign \u_apb_if.PWDATA  = PWDATA;
  assign \u_apb_if.PWRITE  = PWRITE;
  assign \u_apb_if.rd_addr  = PADDR[5:2];
  assign \u_apb_if.rd_data  = \u_regfile.rd_data ;
  assign \u_apb_if.rd_en  = if_rd_en;
  assign \u_apb_if.wr_addr  = PADDR[5:2];
  assign \u_apb_if.wr_data  = PWDATA;
  assign \u_apb_if.wr_strb  = PSTRB;
  assign \u_core.clk  = PCLK;
  assign \u_core.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_core.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_core.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_core.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_core.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_core.hw_active  = \u_core.active_q ;
  assign \u_core.hw_count_val  = \u_core.count_q ;
  assign \u_core.irq  = irq;
  assign \u_core.load_val  = \u_regfile.load_q ;
  assign \u_core.rst_n  = PRESETn;
  assign \u_core.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.clk  = PCLK;
  assign \u_regfile.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_regfile.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_regfile.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_regfile.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_regfile.ctrl_q [31:12] = 20'h00000;
  assign \u_regfile.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_regfile.hw_active  = \u_core.active_q ;
  assign \u_regfile.hw_count_val  = \u_core.count_q ;
  assign \u_regfile.hw_intr_set  = \u_core.hw_intr_set ;
  assign \u_regfile.load_val  = \u_regfile.load_q ;
  assign \u_regfile.rd_addr  = PADDR[5:2];
  assign \u_regfile.rd_en  = if_rd_en;
  assign \u_regfile.rst_n  = PRESETn;
  assign \u_regfile.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.status_q [31:2] = 30'h00000000;
  assign \u_regfile.wr_addr  = PADDR[5:2];
  assign \u_regfile.wr_data  = PWDATA;
  assign \u_regfile.wr_strb  = PSTRB;
endmodule
