/* Generated by Yosys 0.60+36 (git sha1 2833a4450, clang++ 18.1.8 -fPIC -O3) */

module timer_ahb(HCLK, HRESETn, HSEL, HADDR, HTRANS, HWRITE, HWDATA, HWSTRB, HRDATA, HREADY, HRESP, irq, trigger_out);
  input HCLK;
  wire HCLK;
  input HRESETn;
  wire HRESETn;
  input HSEL;
  wire HSEL;
  input [11:0] HADDR;
  wire [11:0] HADDR;
  input [1:0] HTRANS;
  wire [1:0] HTRANS;
  input HWRITE;
  wire HWRITE;
  input [31:0] HWDATA;
  wire [31:0] HWDATA;
  input [3:0] HWSTRB;
  wire [3:0] HWSTRB;
  output [31:0] HRDATA;
  wire [31:0] HRDATA;
  output HREADY;
  wire HREADY;
  output HRESP;
  wire HRESP;
  output irq;
  wire irq;
  output trigger_out;
  wire trigger_out;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire [31:0] _0429_;
  wire ctrl_en;
  wire ctrl_intr_en;
  wire ctrl_mode;
  wire [7:0] ctrl_prescale;
  wire ctrl_trig_en;
  wire hw_active;
  wire [31:0] hw_count_val;
  wire hw_intr_set;
  wire [3:0] if_rd_addr;
  wire [31:0] if_rd_data;
  wire if_rd_en;
  wire [3:0] if_wr_addr;
  wire [31:0] if_wr_data;
  wire [3:0] if_wr_strb;
  wire [31:0] load_val;
  wire status_intr;
  wire [11:0] \u_ahb_if.HADDR ;
  wire \u_ahb_if.HCLK ;
  wire [31:0] \u_ahb_if.HRDATA ;
  wire \u_ahb_if.HREADY ;
  wire \u_ahb_if.HRESETn ;
  wire \u_ahb_if.HRESP ;
  wire \u_ahb_if.HSEL ;
  wire [1:0] \u_ahb_if.HTRANS ;
  wire [31:0] \u_ahb_if.HWDATA ;
  wire \u_ahb_if.HWRITE ;
  wire [3:0] \u_ahb_if.HWSTRB ;
  reg [3:0] \u_ahb_if.dphase_addr_q ;
  reg \u_ahb_if.dphase_valid_q ;
  reg \u_ahb_if.dphase_write_q ;
  wire [3:0] \u_ahb_if.rd_addr ;
  wire [31:0] \u_ahb_if.rd_data ;
  wire \u_ahb_if.rd_en ;
  wire [3:0] \u_ahb_if.wr_addr ;
  wire [31:0] \u_ahb_if.wr_data ;
  wire [3:0] \u_ahb_if.wr_strb ;
  reg \u_core.active_q ;
  wire \u_core.clk ;
  reg [31:0] \u_core.count_q ;
  wire \u_core.ctrl_en ;
  wire \u_core.ctrl_intr_en ;
  wire \u_core.ctrl_mode ;
  wire [7:0] \u_core.ctrl_prescale ;
  wire \u_core.ctrl_trig_en ;
  reg \u_core.en_prev_q ;
  wire \u_core.hw_active ;
  wire [31:0] \u_core.hw_count_val ;
  reg \u_core.hw_intr_set ;
  wire \u_core.irq ;
  wire [31:0] \u_core.load_val ;
  reg [7:0] \u_core.prescale_cnt_q ;
  wire \u_core.rst_n ;
  wire \u_core.status_intr ;
  reg \u_core.trigger_out ;
  wire \u_core.underflow ;
  wire \u_regfile.clk ;
  reg [31:0] \u_regfile.count_q ;
  wire \u_regfile.ctrl_en ;
  wire \u_regfile.ctrl_intr_en ;
  wire \u_regfile.ctrl_mode ;
  wire [7:0] \u_regfile.ctrl_prescale ;
  wire [31:0] \u_regfile.ctrl_q ;
  wire \u_regfile.ctrl_trig_en ;
  wire \u_regfile.hw_active ;
  wire [31:0] \u_regfile.hw_count_val ;
  wire \u_regfile.hw_intr_set ;
  reg [31:0] \u_regfile.load_q ;
  wire [31:0] \u_regfile.load_val ;
  wire [3:0] \u_regfile.rd_addr ;
  reg [31:0] \u_regfile.rd_data ;
  wire \u_regfile.rd_en ;
  wire \u_regfile.rst_n ;
  wire \u_regfile.status_intr ;
  wire [31:0] \u_regfile.status_q ;
  wire [3:0] \u_regfile.wr_addr ;
  wire [31:0] \u_regfile.wr_data ;
  wire [3:0] \u_regfile.wr_strb ;
  assign if_rd_en = \u_ahb_if.dphase_valid_q  & ~(\u_ahb_if.dphase_write_q );
  assign _0052_ = ~(\u_core.prescale_cnt_q [0] | \u_core.prescale_cnt_q [1]);
  assign _0053_ = ~(\u_core.prescale_cnt_q [2] | \u_core.prescale_cnt_q [3]);
  assign _0054_ = _0053_ & _0052_;
  assign _0055_ = ~(\u_core.prescale_cnt_q [4] | \u_core.prescale_cnt_q [5]);
  assign _0056_ = ~(\u_core.prescale_cnt_q [7] | \u_core.prescale_cnt_q [6]);
  assign _0057_ = ~(_0056_ & _0055_);
  assign _0058_ = _0054_ & ~(_0057_);
  assign _0059_ = ~(_0058_ & \u_regfile.ctrl_q [0]);
  assign _0060_ = \u_core.active_q  & ~(_0059_);
  assign _0061_ = _0060_ & ~(\u_regfile.ctrl_q [1]);
  assign _0062_ = \u_regfile.ctrl_q [0] & ~(\u_core.en_prev_q );
  assign _0011_ = _0062_ | _0061_;
  assign irq = \u_regfile.ctrl_q [2] & \u_regfile.status_q [0];
  assign _0063_ = ~(\u_core.count_q [0] | \u_core.count_q [1]);
  assign _0064_ = ~(\u_core.count_q [3] | \u_core.count_q [2]);
  assign _0065_ = _0064_ & _0063_;
  assign _0066_ = ~(\u_core.count_q [5] | \u_core.count_q [4]);
  assign _0067_ = ~(\u_core.count_q [7] | \u_core.count_q [6]);
  assign _0068_ = _0067_ & _0066_;
  assign _0069_ = _0068_ & _0065_;
  assign _0070_ = \u_core.count_q [9] | \u_core.count_q [8];
  assign _0071_ = \u_core.count_q [11] | \u_core.count_q [10];
  assign _0072_ = _0071_ | _0070_;
  assign _0073_ = \u_core.count_q [13] | \u_core.count_q [12];
  assign _0074_ = ~(\u_core.count_q [15] | \u_core.count_q [14]);
  assign _0075_ = _0073_ | ~(_0074_);
  assign _0076_ = _0075_ | _0072_;
  assign _0077_ = _0069_ & ~(_0076_);
  assign _0078_ = ~(\u_core.count_q [17] | \u_core.count_q [16]);
  assign _0079_ = ~(\u_core.count_q [19] | \u_core.count_q [18]);
  assign _0080_ = _0079_ & _0078_;
  assign _0081_ = \u_core.count_q [21] | \u_core.count_q [20];
  assign _0082_ = ~(\u_core.count_q [23] | \u_core.count_q [22]);
  assign _0083_ = _0081_ | ~(_0082_);
  assign _0084_ = _0080_ & ~(_0083_);
  assign _0085_ = ~(\u_core.count_q [25] | \u_core.count_q [24]);
  assign _0086_ = ~(\u_core.count_q [27] | \u_core.count_q [26]);
  assign _0087_ = _0086_ & _0085_;
  assign _0088_ = ~(\u_core.count_q [29] | \u_core.count_q [28]);
  assign _0089_ = ~(\u_core.count_q [31] | \u_core.count_q [30]);
  assign _0090_ = _0089_ & _0088_;
  assign _0091_ = _0090_ & _0087_;
  assign _0092_ = ~(_0091_ & _0084_);
  assign _0093_ = _0077_ & ~(_0092_);
  assign \u_core.underflow  = _0093_ & _0060_;
  assign _0010_ = \u_core.underflow  & \u_regfile.ctrl_q [3];
  assign _0094_ = ~(\u_ahb_if.dphase_write_q  & \u_ahb_if.dphase_valid_q );
  assign _0095_ = \u_ahb_if.dphase_addr_q [0] & ~(\u_ahb_if.dphase_addr_q [1]);
  assign _0096_ = \u_ahb_if.dphase_addr_q [3] | \u_ahb_if.dphase_addr_q [2];
  assign _0097_ = _0095_ & ~(_0096_);
  assign _0098_ = _0097_ & ~(_0094_);
  assign _0099_ = ~(_0098_ & HWSTRB[0]);
  assign _0100_ = HWDATA[0] & ~(_0099_);
  assign _0001_ = _0100_ | \u_core.hw_intr_set ;
  assign _0000_ = _0062_ | _0060_;
  assign _0101_ = _0093_ | ~(_0060_);
  assign _0102_ = _0101_ | _0062_;
  assign _0103_ = ~\u_regfile.ctrl_q [0];
  assign _0104_ = _0060_ | _0103_;
  assign _0105_ = ~(_0104_ | _0062_);
  assign _0008_ = _0102_ & ~(_0105_);
  assign _0106_ = \u_ahb_if.dphase_addr_q [0] | ~(\u_ahb_if.dphase_addr_q [1]);
  assign _0107_ = _0106_ | _0096_;
  assign _0108_ = _0107_ | _0094_;
  assign _0007_ = HWSTRB[3] & ~(_0108_);
  assign _0006_ = HWSTRB[2] & ~(_0108_);
  assign _0005_ = HWSTRB[1] & ~(_0108_);
  assign _0004_ = HWSTRB[0] & ~(_0108_);
  assign _0109_ = \u_ahb_if.dphase_addr_q [1] | \u_ahb_if.dphase_addr_q [0];
  assign _0110_ = ~(_0109_ | _0096_);
  assign _0111_ = _0094_ | ~(_0110_);
  assign _0003_ = HWSTRB[1] & ~(_0111_);
  assign _0002_ = HWSTRB[0] & ~(_0111_);
  assign _0112_ = HTRANS[0] | ~(HTRANS[1]);
  assign _0009_ = HSEL & ~(_0112_);
  assign _0113_ = ~(\u_ahb_if.dphase_addr_q [1] & \u_ahb_if.dphase_addr_q [0]);
  assign _0114_ = _0113_ | _0096_;
  assign _0115_ = \u_regfile.count_q [16] & ~(_0114_);
  assign _0116_ = \u_regfile.load_q [16] & ~(_0107_);
  assign _0117_ = _0116_ | _0115_;
  assign _0118_ = ~(_0114_ & _0107_);
  assign _0119_ = _0110_ | _0097_;
  assign _0120_ = _0119_ | _0118_;
  assign _0429_[16] = _0120_ & _0117_;
  assign _0121_ = _0114_ | ~(\u_regfile.count_q [17]);
  assign _0122_ = \u_regfile.load_q [17] & ~(_0107_);
  assign _0123_ = _0121_ & ~(_0122_);
  assign _0429_[17] = _0120_ & ~(_0123_);
  assign _0124_ = _0114_ | ~(\u_regfile.count_q [18]);
  assign _0125_ = \u_regfile.load_q [18] & ~(_0107_);
  assign _0126_ = _0124_ & ~(_0125_);
  assign _0429_[18] = _0120_ & ~(_0126_);
  assign _0127_ = _0114_ | ~(\u_regfile.count_q [19]);
  assign _0128_ = \u_regfile.load_q [19] & ~(_0107_);
  assign _0129_ = _0127_ & ~(_0128_);
  assign _0429_[19] = _0120_ & ~(_0129_);
  assign _0130_ = _0114_ | ~(\u_regfile.count_q [20]);
  assign _0131_ = \u_regfile.load_q [20] & ~(_0107_);
  assign _0132_ = _0130_ & ~(_0131_);
  assign _0429_[20] = _0120_ & ~(_0132_);
  assign _0133_ = _0114_ | ~(\u_regfile.count_q [21]);
  assign _0134_ = \u_regfile.load_q [21] & ~(_0107_);
  assign _0135_ = _0133_ & ~(_0134_);
  assign _0429_[21] = _0120_ & ~(_0135_);
  assign _0136_ = _0114_ | ~(\u_regfile.count_q [22]);
  assign _0137_ = \u_regfile.load_q [22] & ~(_0107_);
  assign _0138_ = _0136_ & ~(_0137_);
  assign _0429_[22] = _0120_ & ~(_0138_);
  assign _0139_ = _0114_ | ~(\u_regfile.count_q [23]);
  assign _0140_ = \u_regfile.load_q [23] & ~(_0107_);
  assign _0141_ = _0139_ & ~(_0140_);
  assign _0429_[23] = _0120_ & ~(_0141_);
  assign _0142_ = _0114_ | ~(\u_regfile.count_q [24]);
  assign _0143_ = \u_regfile.load_q [24] & ~(_0107_);
  assign _0144_ = _0142_ & ~(_0143_);
  assign _0429_[24] = _0120_ & ~(_0144_);
  assign _0145_ = _0114_ | ~(\u_regfile.count_q [25]);
  assign _0146_ = \u_regfile.load_q [25] & ~(_0107_);
  assign _0147_ = _0145_ & ~(_0146_);
  assign _0429_[25] = _0120_ & ~(_0147_);
  assign _0148_ = _0114_ | ~(\u_regfile.count_q [26]);
  assign _0149_ = \u_regfile.load_q [26] & ~(_0107_);
  assign _0150_ = _0148_ & ~(_0149_);
  assign _0429_[26] = _0120_ & ~(_0150_);
  assign _0151_ = _0114_ | ~(\u_regfile.count_q [27]);
  assign _0152_ = \u_regfile.load_q [27] & ~(_0107_);
  assign _0153_ = _0151_ & ~(_0152_);
  assign _0429_[27] = _0120_ & ~(_0153_);
  assign _0154_ = _0114_ | ~(\u_regfile.count_q [28]);
  assign _0155_ = \u_regfile.load_q [28] & ~(_0107_);
  assign _0156_ = _0154_ & ~(_0155_);
  assign _0429_[28] = _0120_ & ~(_0156_);
  assign _0157_ = _0114_ | ~(\u_regfile.count_q [29]);
  assign _0158_ = \u_regfile.load_q [29] & ~(_0107_);
  assign _0159_ = _0157_ & ~(_0158_);
  assign _0429_[29] = _0120_ & ~(_0159_);
  assign _0160_ = _0114_ | ~(\u_regfile.count_q [30]);
  assign _0161_ = \u_regfile.load_q [30] & ~(_0107_);
  assign _0162_ = _0160_ & ~(_0161_);
  assign _0429_[30] = _0120_ & ~(_0162_);
  assign _0163_ = _0114_ | ~(\u_regfile.count_q [31]);
  assign _0164_ = \u_regfile.load_q [31] & ~(_0107_);
  assign _0165_ = _0163_ & ~(_0164_);
  assign _0429_[31] = _0120_ & ~(_0165_);
  assign _0166_ = ~\u_core.prescale_cnt_q [0];
  assign _0167_ = _0058_ ? \u_regfile.ctrl_q [4] : _0166_;
  assign _0044_ = \u_regfile.ctrl_q [0] ? _0167_ : \u_regfile.ctrl_q [4];
  assign _0168_ = ~(\u_core.prescale_cnt_q [0] ^ \u_core.prescale_cnt_q [1]);
  assign _0169_ = _0058_ ? \u_regfile.ctrl_q [5] : _0168_;
  assign _0045_ = \u_regfile.ctrl_q [0] ? _0169_ : \u_regfile.ctrl_q [5];
  assign _0170_ = _0052_ ^ \u_core.prescale_cnt_q [2];
  assign _0171_ = _0058_ ? \u_regfile.ctrl_q [6] : _0170_;
  assign _0046_ = \u_regfile.ctrl_q [0] ? _0171_ : \u_regfile.ctrl_q [6];
  assign _0172_ = _0052_ & ~(\u_core.prescale_cnt_q [2]);
  assign _0173_ = _0172_ ^ \u_core.prescale_cnt_q [3];
  assign _0174_ = _0058_ ? \u_regfile.ctrl_q [7] : _0173_;
  assign _0047_ = \u_regfile.ctrl_q [0] ? _0174_ : \u_regfile.ctrl_q [7];
  assign _0175_ = _0053_ & ~(_0052_);
  assign _0176_ = _0053_ & ~(_0175_);
  assign _0177_ = _0176_ ^ \u_core.prescale_cnt_q [4];
  assign _0178_ = _0058_ ? \u_regfile.ctrl_q [8] : _0177_;
  assign _0048_ = \u_regfile.ctrl_q [0] ? _0178_ : \u_regfile.ctrl_q [8];
  assign _0179_ = _0176_ & ~(\u_core.prescale_cnt_q [4]);
  assign _0180_ = _0179_ ^ \u_core.prescale_cnt_q [5];
  assign _0181_ = _0058_ ? \u_regfile.ctrl_q [9] : _0180_;
  assign _0049_ = \u_regfile.ctrl_q [0] ? _0181_ : \u_regfile.ctrl_q [9];
  assign _0182_ = _0055_ & ~(_0176_);
  assign _0183_ = _0055_ & ~(_0182_);
  assign _0184_ = _0183_ ^ \u_core.prescale_cnt_q [6];
  assign _0185_ = _0058_ ? \u_regfile.ctrl_q [10] : _0184_;
  assign _0050_ = \u_regfile.ctrl_q [0] ? _0185_ : \u_regfile.ctrl_q [10];
  assign _0186_ = _0183_ & ~(\u_core.prescale_cnt_q [6]);
  assign _0187_ = _0186_ ^ \u_core.prescale_cnt_q [7];
  assign _0188_ = _0058_ ? \u_regfile.ctrl_q [11] : _0187_;
  assign _0051_ = \u_regfile.ctrl_q [0] ? _0188_ : \u_regfile.ctrl_q [11];
  assign _0189_ = ~\u_core.count_q [0];
  assign _0190_ = \u_regfile.load_q [0] & ~(\u_regfile.ctrl_q [1]);
  assign _0191_ = _0093_ ? _0190_ : _0189_;
  assign _0012_ = _0062_ ? \u_regfile.load_q [0] : _0191_;
  assign _0192_ = \u_regfile.load_q [1] & ~(\u_regfile.ctrl_q [1]);
  assign _0193_ = ~(\u_core.count_q [0] ^ \u_core.count_q [1]);
  assign _0194_ = _0093_ ? _0192_ : _0193_;
  assign _0023_ = _0062_ ? \u_regfile.load_q [1] : _0194_;
  assign _0195_ = \u_regfile.load_q [2] & ~(\u_regfile.ctrl_q [1]);
  assign _0196_ = _0063_ ^ \u_core.count_q [2];
  assign _0197_ = _0093_ ? _0195_ : _0196_;
  assign _0034_ = _0062_ ? \u_regfile.load_q [2] : _0197_;
  assign _0198_ = \u_regfile.load_q [3] & ~(\u_regfile.ctrl_q [1]);
  assign _0199_ = _0063_ & ~(\u_core.count_q [2]);
  assign _0200_ = _0199_ ^ \u_core.count_q [3];
  assign _0201_ = _0093_ ? _0198_ : _0200_;
  assign _0037_ = _0062_ ? \u_regfile.load_q [3] : _0201_;
  assign _0202_ = \u_regfile.load_q [4] & ~(\u_regfile.ctrl_q [1]);
  assign _0203_ = _0064_ & ~(_0063_);
  assign _0204_ = _0064_ & ~(_0203_);
  assign _0205_ = _0204_ ^ \u_core.count_q [4];
  assign _0206_ = _0093_ ? _0202_ : _0205_;
  assign _0038_ = _0062_ ? \u_regfile.load_q [4] : _0206_;
  assign _0207_ = \u_regfile.load_q [5] & ~(\u_regfile.ctrl_q [1]);
  assign _0208_ = _0204_ & ~(\u_core.count_q [4]);
  assign _0209_ = _0208_ ^ \u_core.count_q [5];
  assign _0210_ = _0093_ ? _0207_ : _0209_;
  assign _0039_ = _0062_ ? \u_regfile.load_q [5] : _0210_;
  assign _0211_ = \u_regfile.load_q [6] & ~(\u_regfile.ctrl_q [1]);
  assign _0212_ = _0066_ & ~(_0204_);
  assign _0213_ = _0066_ & ~(_0212_);
  assign _0214_ = _0213_ ^ \u_core.count_q [6];
  assign _0215_ = _0093_ ? _0211_ : _0214_;
  assign _0040_ = _0062_ ? \u_regfile.load_q [6] : _0215_;
  assign _0216_ = \u_regfile.load_q [7] & ~(\u_regfile.ctrl_q [1]);
  assign _0217_ = _0213_ & ~(\u_core.count_q [6]);
  assign _0218_ = _0217_ ^ \u_core.count_q [7];
  assign _0219_ = _0093_ ? _0216_ : _0218_;
  assign _0041_ = _0062_ ? \u_regfile.load_q [7] : _0219_;
  assign _0220_ = \u_regfile.load_q [8] & ~(\u_regfile.ctrl_q [1]);
  assign _0221_ = _0067_ & ~(_0066_);
  assign _0222_ = _0067_ & ~(_0221_);
  assign _0223_ = _0068_ & ~(_0204_);
  assign _0224_ = _0222_ & ~(_0223_);
  assign _0225_ = _0224_ ^ \u_core.count_q [8];
  assign _0226_ = _0093_ ? _0220_ : _0225_;
  assign _0042_ = _0062_ ? \u_regfile.load_q [8] : _0226_;
  assign _0227_ = \u_regfile.load_q [9] & ~(\u_regfile.ctrl_q [1]);
  assign _0228_ = _0224_ & ~(\u_core.count_q [8]);
  assign _0229_ = _0228_ ^ \u_core.count_q [9];
  assign _0230_ = _0093_ ? _0227_ : _0229_;
  assign _0043_ = _0062_ ? \u_regfile.load_q [9] : _0230_;
  assign _0231_ = \u_regfile.load_q [10] & ~(\u_regfile.ctrl_q [1]);
  assign _0232_ = ~(\u_core.count_q [9] | \u_core.count_q [8]);
  assign _0233_ = ~(_0224_ | _0070_);
  assign _0234_ = _0232_ & ~(_0233_);
  assign _0235_ = _0234_ ^ \u_core.count_q [10];
  assign _0236_ = _0093_ ? _0231_ : _0235_;
  assign _0013_ = _0062_ ? \u_regfile.load_q [10] : _0236_;
  assign _0237_ = \u_regfile.load_q [11] & ~(\u_regfile.ctrl_q [1]);
  assign _0238_ = _0234_ & ~(\u_core.count_q [10]);
  assign _0239_ = _0238_ ^ \u_core.count_q [11];
  assign _0240_ = _0093_ ? _0237_ : _0239_;
  assign _0014_ = _0062_ ? \u_regfile.load_q [11] : _0240_;
  assign _0241_ = \u_regfile.load_q [12] & ~(\u_regfile.ctrl_q [1]);
  assign _0242_ = ~(\u_core.count_q [11] | \u_core.count_q [10]);
  assign _0243_ = ~(_0232_ | _0071_);
  assign _0244_ = _0242_ & ~(_0243_);
  assign _0245_ = ~(_0224_ | _0072_);
  assign _0246_ = _0244_ & ~(_0245_);
  assign _0247_ = _0246_ ^ \u_core.count_q [12];
  assign _0248_ = _0093_ ? _0241_ : _0247_;
  assign _0015_ = _0062_ ? \u_regfile.load_q [12] : _0248_;
  assign _0249_ = \u_regfile.load_q [13] & ~(\u_regfile.ctrl_q [1]);
  assign _0250_ = _0246_ & ~(\u_core.count_q [12]);
  assign _0251_ = _0250_ ^ \u_core.count_q [13];
  assign _0252_ = _0093_ ? _0249_ : _0251_;
  assign _0016_ = _0062_ ? \u_regfile.load_q [13] : _0252_;
  assign _0253_ = \u_regfile.load_q [14] & ~(\u_regfile.ctrl_q [1]);
  assign _0254_ = ~\u_core.count_q [14];
  assign _0255_ = ~(\u_core.count_q [13] | \u_core.count_q [12]);
  assign _0256_ = ~(_0246_ | _0073_);
  assign _0257_ = _0256_ | ~(_0255_);
  assign _0258_ = _0257_ ^ _0254_;
  assign _0259_ = _0093_ ? _0253_ : _0258_;
  assign _0017_ = _0062_ ? \u_regfile.load_q [14] : _0259_;
  assign _0260_ = \u_regfile.load_q [15] & ~(\u_regfile.ctrl_q [1]);
  assign _0261_ = _0254_ & ~(_0257_);
  assign _0262_ = _0261_ ^ \u_core.count_q [15];
  assign _0263_ = _0093_ ? _0260_ : _0262_;
  assign _0018_ = _0062_ ? \u_regfile.load_q [15] : _0263_;
  assign _0264_ = \u_regfile.load_q [16] & ~(\u_regfile.ctrl_q [1]);
  assign _0265_ = _0074_ & ~(_0255_);
  assign _0266_ = _0074_ & ~(_0265_);
  assign _0267_ = ~(_0244_ | _0075_);
  assign _0268_ = _0266_ & ~(_0267_);
  assign _0269_ = ~(_0224_ | _0076_);
  assign _0270_ = _0268_ & ~(_0269_);
  assign _0271_ = _0270_ ^ \u_core.count_q [16];
  assign _0272_ = _0093_ ? _0264_ : _0271_;
  assign _0019_ = _0062_ ? \u_regfile.load_q [16] : _0272_;
  assign _0273_ = \u_regfile.load_q [17] & ~(\u_regfile.ctrl_q [1]);
  assign _0274_ = _0270_ & ~(\u_core.count_q [16]);
  assign _0275_ = _0274_ ^ \u_core.count_q [17];
  assign _0276_ = _0093_ ? _0273_ : _0275_;
  assign _0020_ = _0062_ ? \u_regfile.load_q [17] : _0276_;
  assign _0277_ = \u_regfile.load_q [18] & ~(\u_regfile.ctrl_q [1]);
  assign _0278_ = ~\u_core.count_q [18];
  assign _0279_ = _0078_ & ~(_0270_);
  assign _0280_ = _0279_ | ~(_0078_);
  assign _0281_ = _0280_ ^ _0278_;
  assign _0282_ = _0093_ ? _0277_ : _0281_;
  assign _0021_ = _0062_ ? \u_regfile.load_q [18] : _0282_;
  assign _0283_ = \u_regfile.load_q [19] & ~(\u_regfile.ctrl_q [1]);
  assign _0284_ = _0278_ & ~(_0280_);
  assign _0285_ = _0284_ ^ \u_core.count_q [19];
  assign _0286_ = _0093_ ? _0283_ : _0285_;
  assign _0022_ = _0062_ ? \u_regfile.load_q [19] : _0286_;
  assign _0287_ = \u_regfile.load_q [20] & ~(\u_regfile.ctrl_q [1]);
  assign _0288_ = _0079_ & ~(_0078_);
  assign _0289_ = _0079_ & ~(_0288_);
  assign _0290_ = _0080_ & ~(_0270_);
  assign _0291_ = _0289_ & ~(_0290_);
  assign _0292_ = _0291_ ^ \u_core.count_q [20];
  assign _0293_ = _0093_ ? _0287_ : _0292_;
  assign _0024_ = _0062_ ? \u_regfile.load_q [20] : _0293_;
  assign _0294_ = \u_regfile.load_q [21] & ~(\u_regfile.ctrl_q [1]);
  assign _0295_ = _0291_ & ~(\u_core.count_q [20]);
  assign _0296_ = _0295_ ^ \u_core.count_q [21];
  assign _0297_ = _0093_ ? _0294_ : _0296_;
  assign _0025_ = _0062_ ? \u_regfile.load_q [21] : _0297_;
  assign _0298_ = \u_regfile.load_q [22] & ~(\u_regfile.ctrl_q [1]);
  assign _0299_ = ~\u_core.count_q [22];
  assign _0300_ = ~(\u_core.count_q [21] | \u_core.count_q [20]);
  assign _0301_ = ~(_0291_ | _0081_);
  assign _0302_ = _0301_ | ~(_0300_);
  assign _0303_ = _0302_ ^ _0299_;
  assign _0304_ = _0093_ ? _0298_ : _0303_;
  assign _0026_ = _0062_ ? \u_regfile.load_q [22] : _0304_;
  assign _0305_ = \u_regfile.load_q [23] & ~(\u_regfile.ctrl_q [1]);
  assign _0306_ = _0299_ & ~(_0302_);
  assign _0307_ = _0306_ ^ \u_core.count_q [23];
  assign _0308_ = _0093_ ? _0305_ : _0307_;
  assign _0027_ = _0062_ ? \u_regfile.load_q [23] : _0308_;
  assign _0309_ = \u_regfile.load_q [24] & ~(\u_regfile.ctrl_q [1]);
  assign _0310_ = _0082_ & ~(_0300_);
  assign _0311_ = _0082_ & ~(_0310_);
  assign _0312_ = ~(_0289_ | _0083_);
  assign _0313_ = _0311_ & ~(_0312_);
  assign _0314_ = _0084_ & ~(_0270_);
  assign _0315_ = _0313_ & ~(_0314_);
  assign _0316_ = _0315_ ^ \u_core.count_q [24];
  assign _0317_ = _0093_ ? _0309_ : _0316_;
  assign _0028_ = _0062_ ? \u_regfile.load_q [24] : _0317_;
  assign _0318_ = \u_regfile.load_q [25] & ~(\u_regfile.ctrl_q [1]);
  assign _0319_ = _0315_ & ~(\u_core.count_q [24]);
  assign _0320_ = _0319_ ^ \u_core.count_q [25];
  assign _0321_ = _0093_ ? _0318_ : _0320_;
  assign _0029_ = _0062_ ? \u_regfile.load_q [25] : _0321_;
  assign _0322_ = \u_regfile.load_q [26] & ~(\u_regfile.ctrl_q [1]);
  assign _0323_ = ~\u_core.count_q [26];
  assign _0324_ = _0085_ & ~(_0315_);
  assign _0325_ = _0324_ | ~(_0085_);
  assign _0326_ = _0325_ ^ _0323_;
  assign _0327_ = _0093_ ? _0322_ : _0326_;
  assign _0030_ = _0062_ ? \u_regfile.load_q [26] : _0327_;
  assign _0328_ = \u_regfile.load_q [27] & ~(\u_regfile.ctrl_q [1]);
  assign _0329_ = _0323_ & ~(_0325_);
  assign _0330_ = _0329_ ^ \u_core.count_q [27];
  assign _0331_ = _0093_ ? _0328_ : _0330_;
  assign _0031_ = _0062_ ? \u_regfile.load_q [27] : _0331_;
  assign _0332_ = \u_regfile.load_q [28] & ~(\u_regfile.ctrl_q [1]);
  assign _0333_ = _0086_ & ~(_0085_);
  assign _0334_ = _0086_ & ~(_0333_);
  assign _0335_ = _0087_ & ~(_0315_);
  assign _0336_ = _0334_ & ~(_0335_);
  assign _0337_ = _0336_ ^ \u_core.count_q [28];
  assign _0338_ = _0093_ ? _0332_ : _0337_;
  assign _0032_ = _0062_ ? \u_regfile.load_q [28] : _0338_;
  assign _0339_ = \u_regfile.load_q [29] & ~(\u_regfile.ctrl_q [1]);
  assign _0340_ = _0336_ & ~(\u_core.count_q [28]);
  assign _0341_ = _0340_ ^ \u_core.count_q [29];
  assign _0342_ = _0093_ ? _0339_ : _0341_;
  assign _0033_ = _0062_ ? \u_regfile.load_q [29] : _0342_;
  assign _0343_ = \u_regfile.load_q [30] & ~(\u_regfile.ctrl_q [1]);
  assign _0344_ = ~\u_core.count_q [30];
  assign _0345_ = _0088_ & ~(_0336_);
  assign _0346_ = _0345_ | ~(_0088_);
  assign _0347_ = _0346_ ^ _0344_;
  assign _0348_ = _0093_ ? _0343_ : _0347_;
  assign _0035_ = _0062_ ? \u_regfile.load_q [30] : _0348_;
  assign _0349_ = \u_regfile.load_q [31] & ~(\u_regfile.ctrl_q [1]);
  assign _0350_ = _0344_ & ~(_0346_);
  assign _0351_ = _0350_ ^ \u_core.count_q [31];
  assign _0352_ = _0093_ ? _0349_ : _0351_;
  assign _0036_ = _0062_ ? \u_regfile.load_q [31] : _0352_;
  assign _0353_ = _0114_ | ~(\u_regfile.count_q [0]);
  assign _0354_ = \u_regfile.load_q [0] & ~(_0107_);
  assign _0355_ = _0353_ & ~(_0354_);
  assign _0356_ = _0097_ & \u_regfile.status_q [0];
  assign _0357_ = _0110_ & ~(_0103_);
  assign _0358_ = _0357_ | _0356_;
  assign _0359_ = _0355_ & ~(_0358_);
  assign _0429_[0] = _0120_ & ~(_0359_);
  assign _0360_ = _0114_ | ~(\u_regfile.count_q [1]);
  assign _0361_ = \u_regfile.load_q [1] & ~(_0107_);
  assign _0362_ = _0360_ & ~(_0361_);
  assign _0363_ = _0097_ & \u_regfile.status_q [1];
  assign _0364_ = _0110_ & \u_regfile.ctrl_q [1];
  assign _0365_ = _0364_ | _0363_;
  assign _0366_ = _0362_ & ~(_0365_);
  assign _0429_[1] = _0120_ & ~(_0366_);
  assign _0367_ = _0114_ | ~(\u_regfile.count_q [2]);
  assign _0368_ = \u_regfile.load_q [2] & ~(_0107_);
  assign _0369_ = _0367_ & ~(_0368_);
  assign _0370_ = _0110_ & \u_regfile.ctrl_q [2];
  assign _0371_ = _0369_ & ~(_0370_);
  assign _0429_[2] = _0120_ & ~(_0371_);
  assign _0372_ = _0114_ | ~(\u_regfile.count_q [3]);
  assign _0373_ = \u_regfile.load_q [3] & ~(_0107_);
  assign _0374_ = _0372_ & ~(_0373_);
  assign _0375_ = _0110_ & \u_regfile.ctrl_q [3];
  assign _0376_ = _0374_ & ~(_0375_);
  assign _0429_[3] = _0120_ & ~(_0376_);
  assign _0377_ = _0114_ | ~(\u_regfile.count_q [4]);
  assign _0378_ = \u_regfile.load_q [4] & ~(_0107_);
  assign _0379_ = _0377_ & ~(_0378_);
  assign _0380_ = _0110_ & \u_regfile.ctrl_q [4];
  assign _0381_ = _0379_ & ~(_0380_);
  assign _0429_[4] = _0120_ & ~(_0381_);
  assign _0382_ = _0114_ | ~(\u_regfile.count_q [5]);
  assign _0383_ = \u_regfile.load_q [5] & ~(_0107_);
  assign _0384_ = _0382_ & ~(_0383_);
  assign _0385_ = _0110_ & \u_regfile.ctrl_q [5];
  assign _0386_ = _0384_ & ~(_0385_);
  assign _0429_[5] = _0120_ & ~(_0386_);
  assign _0387_ = _0114_ | ~(\u_regfile.count_q [6]);
  assign _0388_ = \u_regfile.load_q [6] & ~(_0107_);
  assign _0389_ = _0387_ & ~(_0388_);
  assign _0390_ = _0110_ & \u_regfile.ctrl_q [6];
  assign _0391_ = _0389_ & ~(_0390_);
  assign _0429_[6] = _0120_ & ~(_0391_);
  assign _0392_ = _0114_ | ~(\u_regfile.count_q [7]);
  assign _0393_ = \u_regfile.load_q [7] & ~(_0107_);
  assign _0394_ = _0392_ & ~(_0393_);
  assign _0395_ = _0110_ & \u_regfile.ctrl_q [7];
  assign _0396_ = _0394_ & ~(_0395_);
  assign _0429_[7] = _0120_ & ~(_0396_);
  assign _0397_ = _0114_ | ~(\u_regfile.count_q [8]);
  assign _0398_ = \u_regfile.load_q [8] & ~(_0107_);
  assign _0399_ = _0397_ & ~(_0398_);
  assign _0400_ = _0110_ & \u_regfile.ctrl_q [8];
  assign _0401_ = _0399_ & ~(_0400_);
  assign _0429_[8] = _0120_ & ~(_0401_);
  assign _0402_ = _0114_ | ~(\u_regfile.count_q [9]);
  assign _0403_ = \u_regfile.load_q [9] & ~(_0107_);
  assign _0404_ = _0402_ & ~(_0403_);
  assign _0405_ = _0110_ & \u_regfile.ctrl_q [9];
  assign _0406_ = _0404_ & ~(_0405_);
  assign _0429_[9] = _0120_ & ~(_0406_);
  assign _0407_ = _0114_ | ~(\u_regfile.count_q [10]);
  assign _0408_ = \u_regfile.load_q [10] & ~(_0107_);
  assign _0409_ = _0407_ & ~(_0408_);
  assign _0410_ = _0110_ & \u_regfile.ctrl_q [10];
  assign _0411_ = _0409_ & ~(_0410_);
  assign _0429_[10] = _0120_ & ~(_0411_);
  assign _0412_ = _0114_ | ~(\u_regfile.count_q [11]);
  assign _0413_ = \u_regfile.load_q [11] & ~(_0107_);
  assign _0414_ = _0412_ & ~(_0413_);
  assign _0415_ = _0110_ & \u_regfile.ctrl_q [11];
  assign _0416_ = _0414_ & ~(_0415_);
  assign _0429_[11] = _0120_ & ~(_0416_);
  assign _0417_ = _0114_ | ~(\u_regfile.count_q [12]);
  assign _0418_ = \u_regfile.load_q [12] & ~(_0107_);
  assign _0419_ = _0417_ & ~(_0418_);
  assign _0429_[12] = _0120_ & ~(_0419_);
  assign _0420_ = _0114_ | ~(\u_regfile.count_q [13]);
  assign _0421_ = \u_regfile.load_q [13] & ~(_0107_);
  assign _0422_ = _0420_ & ~(_0421_);
  assign _0429_[13] = _0120_ & ~(_0422_);
  assign _0423_ = _0114_ | ~(\u_regfile.count_q [14]);
  assign _0424_ = \u_regfile.load_q [14] & ~(_0107_);
  assign _0425_ = _0423_ & ~(_0424_);
  assign _0429_[14] = _0120_ & ~(_0425_);
  assign _0426_ = _0114_ | ~(\u_regfile.count_q [15]);
  assign _0427_ = \u_regfile.load_q [15] & ~(_0107_);
  assign _0428_ = _0426_ & ~(_0427_);
  assign _0429_[15] = _0120_ & ~(_0428_);
  reg \u_regfile.status_q_reg[1] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.status_q_reg[1]  <= 1'h0;
    else \u_regfile.status_q_reg[1]  <= \u_core.active_q ;
  assign \u_regfile.status_q [1] = \u_regfile.status_q_reg[1] ;
  reg \u_regfile.status_q_reg[0] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.status_q_reg[0]  <= 1'h0;
    else if (_0001_) \u_regfile.status_q_reg[0]  <= \u_core.hw_intr_set ;
  assign \u_regfile.status_q [0] = \u_regfile.status_q_reg[0] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_valid_q  <= 1'h0;
    else \u_ahb_if.dphase_valid_q  <= _0009_;
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_write_q  <= 1'h0;
    else if (_0009_) \u_ahb_if.dphase_write_q  <= HWRITE;
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_addr_q [0] <= 1'h0;
    else if (_0009_) \u_ahb_if.dphase_addr_q [0] <= HADDR[2];
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_addr_q [1] <= 1'h0;
    else if (_0009_) \u_ahb_if.dphase_addr_q [1] <= HADDR[3];
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_addr_q [2] <= 1'h0;
    else if (_0009_) \u_ahb_if.dphase_addr_q [2] <= HADDR[4];
  always @(posedge HCLK)
    if (!HRESETn) \u_ahb_if.dphase_addr_q [3] <= 1'h0;
    else if (_0009_) \u_ahb_if.dphase_addr_q [3] <= HADDR[5];
  always @(posedge HCLK)
    if (!HRESETn) \u_core.trigger_out  <= 1'h0;
    else \u_core.trigger_out  <= _0010_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.hw_intr_set  <= 1'h0;
    else \u_core.hw_intr_set  <= \u_core.underflow ;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [0] <= 1'h0;
    else if (_0000_) \u_core.count_q [0] <= _0012_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [1] <= 1'h0;
    else if (_0000_) \u_core.count_q [1] <= _0023_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [2] <= 1'h0;
    else if (_0000_) \u_core.count_q [2] <= _0034_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [3] <= 1'h0;
    else if (_0000_) \u_core.count_q [3] <= _0037_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [4] <= 1'h0;
    else if (_0000_) \u_core.count_q [4] <= _0038_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [5] <= 1'h0;
    else if (_0000_) \u_core.count_q [5] <= _0039_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [6] <= 1'h0;
    else if (_0000_) \u_core.count_q [6] <= _0040_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [7] <= 1'h0;
    else if (_0000_) \u_core.count_q [7] <= _0041_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [8] <= 1'h0;
    else if (_0000_) \u_core.count_q [8] <= _0042_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [9] <= 1'h0;
    else if (_0000_) \u_core.count_q [9] <= _0043_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [10] <= 1'h0;
    else if (_0000_) \u_core.count_q [10] <= _0013_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [11] <= 1'h0;
    else if (_0000_) \u_core.count_q [11] <= _0014_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [12] <= 1'h0;
    else if (_0000_) \u_core.count_q [12] <= _0015_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [13] <= 1'h0;
    else if (_0000_) \u_core.count_q [13] <= _0016_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [14] <= 1'h0;
    else if (_0000_) \u_core.count_q [14] <= _0017_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [15] <= 1'h0;
    else if (_0000_) \u_core.count_q [15] <= _0018_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [16] <= 1'h0;
    else if (_0000_) \u_core.count_q [16] <= _0019_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [17] <= 1'h0;
    else if (_0000_) \u_core.count_q [17] <= _0020_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [18] <= 1'h0;
    else if (_0000_) \u_core.count_q [18] <= _0021_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [19] <= 1'h0;
    else if (_0000_) \u_core.count_q [19] <= _0022_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [20] <= 1'h0;
    else if (_0000_) \u_core.count_q [20] <= _0024_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [21] <= 1'h0;
    else if (_0000_) \u_core.count_q [21] <= _0025_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [22] <= 1'h0;
    else if (_0000_) \u_core.count_q [22] <= _0026_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [23] <= 1'h0;
    else if (_0000_) \u_core.count_q [23] <= _0027_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [24] <= 1'h0;
    else if (_0000_) \u_core.count_q [24] <= _0028_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [25] <= 1'h0;
    else if (_0000_) \u_core.count_q [25] <= _0029_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [26] <= 1'h0;
    else if (_0000_) \u_core.count_q [26] <= _0030_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [27] <= 1'h0;
    else if (_0000_) \u_core.count_q [27] <= _0031_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [28] <= 1'h0;
    else if (_0000_) \u_core.count_q [28] <= _0032_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [29] <= 1'h0;
    else if (_0000_) \u_core.count_q [29] <= _0033_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [30] <= 1'h0;
    else if (_0000_) \u_core.count_q [30] <= _0035_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.count_q [31] <= 1'h0;
    else if (_0000_) \u_core.count_q [31] <= _0036_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.active_q  <= 1'h0;
    else if (_0008_) \u_core.active_q  <= _0011_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [0] <= 1'h0;
    else \u_core.prescale_cnt_q [0] <= _0044_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [1] <= 1'h0;
    else \u_core.prescale_cnt_q [1] <= _0045_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [2] <= 1'h0;
    else \u_core.prescale_cnt_q [2] <= _0046_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [3] <= 1'h0;
    else \u_core.prescale_cnt_q [3] <= _0047_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [4] <= 1'h0;
    else \u_core.prescale_cnt_q [4] <= _0048_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [5] <= 1'h0;
    else \u_core.prescale_cnt_q [5] <= _0049_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [6] <= 1'h0;
    else \u_core.prescale_cnt_q [6] <= _0050_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.prescale_cnt_q [7] <= 1'h0;
    else \u_core.prescale_cnt_q [7] <= _0051_;
  always @(posedge HCLK)
    if (!HRESETn) \u_core.en_prev_q  <= 1'h0;
    else \u_core.en_prev_q  <= \u_regfile.ctrl_q [0];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [0] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [0] <= _0429_[0];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [1] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [1] <= _0429_[1];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [2] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [2] <= _0429_[2];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [3] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [3] <= _0429_[3];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [4] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [4] <= _0429_[4];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [5] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [5] <= _0429_[5];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [6] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [6] <= _0429_[6];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [7] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [7] <= _0429_[7];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [8] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [8] <= _0429_[8];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [9] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [9] <= _0429_[9];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [10] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [10] <= _0429_[10];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [11] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [11] <= _0429_[11];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [12] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [12] <= _0429_[12];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [13] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [13] <= _0429_[13];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [14] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [14] <= _0429_[14];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [15] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [15] <= _0429_[15];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [16] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [16] <= _0429_[16];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [17] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [17] <= _0429_[17];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [18] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [18] <= _0429_[18];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [19] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [19] <= _0429_[19];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [20] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [20] <= _0429_[20];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [21] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [21] <= _0429_[21];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [22] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [22] <= _0429_[22];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [23] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [23] <= _0429_[23];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [24] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [24] <= _0429_[24];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [25] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [25] <= _0429_[25];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [26] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [26] <= _0429_[26];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [27] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [27] <= _0429_[27];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [28] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [28] <= _0429_[28];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [29] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [29] <= _0429_[29];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [30] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [30] <= _0429_[30];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.rd_data [31] <= 1'h0;
    else if (if_rd_en) \u_regfile.rd_data [31] <= _0429_[31];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [0] <= 1'h0;
    else \u_regfile.count_q [0] <= \u_core.count_q [0];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [1] <= 1'h0;
    else \u_regfile.count_q [1] <= \u_core.count_q [1];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [2] <= 1'h0;
    else \u_regfile.count_q [2] <= \u_core.count_q [2];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [3] <= 1'h0;
    else \u_regfile.count_q [3] <= \u_core.count_q [3];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [4] <= 1'h0;
    else \u_regfile.count_q [4] <= \u_core.count_q [4];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [5] <= 1'h0;
    else \u_regfile.count_q [5] <= \u_core.count_q [5];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [6] <= 1'h0;
    else \u_regfile.count_q [6] <= \u_core.count_q [6];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [7] <= 1'h0;
    else \u_regfile.count_q [7] <= \u_core.count_q [7];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [8] <= 1'h0;
    else \u_regfile.count_q [8] <= \u_core.count_q [8];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [9] <= 1'h0;
    else \u_regfile.count_q [9] <= \u_core.count_q [9];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [10] <= 1'h0;
    else \u_regfile.count_q [10] <= \u_core.count_q [10];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [11] <= 1'h0;
    else \u_regfile.count_q [11] <= \u_core.count_q [11];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [12] <= 1'h0;
    else \u_regfile.count_q [12] <= \u_core.count_q [12];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [13] <= 1'h0;
    else \u_regfile.count_q [13] <= \u_core.count_q [13];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [14] <= 1'h0;
    else \u_regfile.count_q [14] <= \u_core.count_q [14];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [15] <= 1'h0;
    else \u_regfile.count_q [15] <= \u_core.count_q [15];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [16] <= 1'h0;
    else \u_regfile.count_q [16] <= \u_core.count_q [16];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [17] <= 1'h0;
    else \u_regfile.count_q [17] <= \u_core.count_q [17];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [18] <= 1'h0;
    else \u_regfile.count_q [18] <= \u_core.count_q [18];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [19] <= 1'h0;
    else \u_regfile.count_q [19] <= \u_core.count_q [19];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [20] <= 1'h0;
    else \u_regfile.count_q [20] <= \u_core.count_q [20];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [21] <= 1'h0;
    else \u_regfile.count_q [21] <= \u_core.count_q [21];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [22] <= 1'h0;
    else \u_regfile.count_q [22] <= \u_core.count_q [22];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [23] <= 1'h0;
    else \u_regfile.count_q [23] <= \u_core.count_q [23];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [24] <= 1'h0;
    else \u_regfile.count_q [24] <= \u_core.count_q [24];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [25] <= 1'h0;
    else \u_regfile.count_q [25] <= \u_core.count_q [25];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [26] <= 1'h0;
    else \u_regfile.count_q [26] <= \u_core.count_q [26];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [27] <= 1'h0;
    else \u_regfile.count_q [27] <= \u_core.count_q [27];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [28] <= 1'h0;
    else \u_regfile.count_q [28] <= \u_core.count_q [28];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [29] <= 1'h0;
    else \u_regfile.count_q [29] <= \u_core.count_q [29];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [30] <= 1'h0;
    else \u_regfile.count_q [30] <= \u_core.count_q [30];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.count_q [31] <= 1'h0;
    else \u_regfile.count_q [31] <= \u_core.count_q [31];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [24] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [24] <= HWDATA[24];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [25] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [25] <= HWDATA[25];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [26] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [26] <= HWDATA[26];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [27] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [27] <= HWDATA[27];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [28] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [28] <= HWDATA[28];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [29] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [29] <= HWDATA[29];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [30] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [30] <= HWDATA[30];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [31] <= 1'h0;
    else if (_0007_) \u_regfile.load_q [31] <= HWDATA[31];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [16] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [16] <= HWDATA[16];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [17] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [17] <= HWDATA[17];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [18] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [18] <= HWDATA[18];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [19] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [19] <= HWDATA[19];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [20] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [20] <= HWDATA[20];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [21] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [21] <= HWDATA[21];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [22] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [22] <= HWDATA[22];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [23] <= 1'h0;
    else if (_0006_) \u_regfile.load_q [23] <= HWDATA[23];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [8] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [8] <= HWDATA[8];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [9] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [9] <= HWDATA[9];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [10] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [10] <= HWDATA[10];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [11] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [11] <= HWDATA[11];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [12] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [12] <= HWDATA[12];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [13] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [13] <= HWDATA[13];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [14] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [14] <= HWDATA[14];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [15] <= 1'h0;
    else if (_0005_) \u_regfile.load_q [15] <= HWDATA[15];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [0] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [0] <= HWDATA[0];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [1] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [1] <= HWDATA[1];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [2] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [2] <= HWDATA[2];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [3] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [3] <= HWDATA[3];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [4] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [4] <= HWDATA[4];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [5] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [5] <= HWDATA[5];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [6] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [6] <= HWDATA[6];
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.load_q [7] <= 1'h0;
    else if (_0004_) \u_regfile.load_q [7] <= HWDATA[7];
  reg \u_regfile.ctrl_q_reg[8] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[8]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[8]  <= HWDATA[8];
  assign \u_regfile.ctrl_q [8] = \u_regfile.ctrl_q_reg[8] ;
  reg \u_regfile.ctrl_q_reg[9] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[9]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[9]  <= HWDATA[9];
  assign \u_regfile.ctrl_q [9] = \u_regfile.ctrl_q_reg[9] ;
  reg \u_regfile.ctrl_q_reg[10] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[10]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[10]  <= HWDATA[10];
  assign \u_regfile.ctrl_q [10] = \u_regfile.ctrl_q_reg[10] ;
  reg \u_regfile.ctrl_q_reg[11] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[11]  <= 1'h0;
    else if (_0003_) \u_regfile.ctrl_q_reg[11]  <= HWDATA[11];
  assign \u_regfile.ctrl_q [11] = \u_regfile.ctrl_q_reg[11] ;
  reg \u_regfile.ctrl_q_reg[0] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[0]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[0]  <= HWDATA[0];
  assign \u_regfile.ctrl_q [0] = \u_regfile.ctrl_q_reg[0] ;
  reg \u_regfile.ctrl_q_reg[1] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[1]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[1]  <= HWDATA[1];
  assign \u_regfile.ctrl_q [1] = \u_regfile.ctrl_q_reg[1] ;
  reg \u_regfile.ctrl_q_reg[2] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[2]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[2]  <= HWDATA[2];
  assign \u_regfile.ctrl_q [2] = \u_regfile.ctrl_q_reg[2] ;
  reg \u_regfile.ctrl_q_reg[3] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[3]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[3]  <= HWDATA[3];
  assign \u_regfile.ctrl_q [3] = \u_regfile.ctrl_q_reg[3] ;
  reg \u_regfile.ctrl_q_reg[4] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[4]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[4]  <= HWDATA[4];
  assign \u_regfile.ctrl_q [4] = \u_regfile.ctrl_q_reg[4] ;
  reg \u_regfile.ctrl_q_reg[5] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[5]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[5]  <= HWDATA[5];
  assign \u_regfile.ctrl_q [5] = \u_regfile.ctrl_q_reg[5] ;
  reg \u_regfile.ctrl_q_reg[6] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[6]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[6]  <= HWDATA[6];
  assign \u_regfile.ctrl_q [6] = \u_regfile.ctrl_q_reg[6] ;
  reg \u_regfile.ctrl_q_reg[7] ;
  always @(posedge HCLK)
    if (!HRESETn) \u_regfile.ctrl_q_reg[7]  <= 1'h0;
    else if (_0002_) \u_regfile.ctrl_q_reg[7]  <= HWDATA[7];
  assign \u_regfile.ctrl_q [7] = \u_regfile.ctrl_q_reg[7] ;
  assign HRDATA = \u_regfile.rd_data ;
  assign HREADY = 1'h1;
  assign HRESP = 1'h0;
  assign ctrl_en = \u_regfile.ctrl_q [0];
  assign ctrl_intr_en = \u_regfile.ctrl_q [2];
  assign ctrl_mode = \u_regfile.ctrl_q [1];
  assign ctrl_prescale = \u_regfile.ctrl_q [11:4];
  assign ctrl_trig_en = \u_regfile.ctrl_q [3];
  assign hw_active = \u_core.active_q ;
  assign hw_count_val = \u_core.count_q ;
  assign hw_intr_set = \u_core.hw_intr_set ;
  assign if_rd_addr = \u_ahb_if.dphase_addr_q ;
  assign if_rd_data = \u_regfile.rd_data ;
  assign if_wr_addr = \u_ahb_if.dphase_addr_q ;
  assign if_wr_data = HWDATA;
  assign if_wr_strb = HWSTRB;
  assign load_val = \u_regfile.load_q ;
  assign status_intr = \u_regfile.status_q [0];
  assign trigger_out = \u_core.trigger_out ;
  assign \u_ahb_if.HADDR  = HADDR;
  assign \u_ahb_if.HCLK  = HCLK;
  assign \u_ahb_if.HRDATA  = \u_regfile.rd_data ;
  assign \u_ahb_if.HREADY  = 1'h1;
  assign \u_ahb_if.HRESETn  = HRESETn;
  assign \u_ahb_if.HRESP  = 1'h0;
  assign \u_ahb_if.HSEL  = HSEL;
  assign \u_ahb_if.HTRANS  = HTRANS;
  assign \u_ahb_if.HWDATA  = HWDATA;
  assign \u_ahb_if.HWRITE  = HWRITE;
  assign \u_ahb_if.HWSTRB  = HWSTRB;
  assign \u_ahb_if.rd_addr  = \u_ahb_if.dphase_addr_q ;
  assign \u_ahb_if.rd_data  = \u_regfile.rd_data ;
  assign \u_ahb_if.rd_en  = if_rd_en;
  assign \u_ahb_if.wr_addr  = \u_ahb_if.dphase_addr_q ;
  assign \u_ahb_if.wr_data  = HWDATA;
  assign \u_ahb_if.wr_strb  = HWSTRB;
  assign \u_core.clk  = HCLK;
  assign \u_core.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_core.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_core.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_core.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_core.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_core.hw_active  = \u_core.active_q ;
  assign \u_core.hw_count_val  = \u_core.count_q ;
  assign \u_core.irq  = irq;
  assign \u_core.load_val  = \u_regfile.load_q ;
  assign \u_core.rst_n  = HRESETn;
  assign \u_core.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.clk  = HCLK;
  assign \u_regfile.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_regfile.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_regfile.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_regfile.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_regfile.ctrl_q [31:12] = 20'h00000;
  assign \u_regfile.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_regfile.hw_active  = \u_core.active_q ;
  assign \u_regfile.hw_count_val  = \u_core.count_q ;
  assign \u_regfile.hw_intr_set  = \u_core.hw_intr_set ;
  assign \u_regfile.load_val  = \u_regfile.load_q ;
  assign \u_regfile.rd_addr  = \u_ahb_if.dphase_addr_q ;
  assign \u_regfile.rd_en  = if_rd_en;
  assign \u_regfile.rst_n  = HRESETn;
  assign \u_regfile.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.status_q [31:2] = 30'h00000000;
  assign \u_regfile.wr_addr  = \u_ahb_if.dphase_addr_q ;
  assign \u_regfile.wr_data  = HWDATA;
  assign \u_regfile.wr_strb  = HWSTRB;
endmodule
