/* Generated by Yosys 0.60+36 (git sha1 2833a4450, clang++ 18.1.8 -fPIC -O3) */

module timer_axi4l(ACLK, ARESETn, AWVALID, AWREADY, AWADDR, WVALID, WREADY, WDATA, WSTRB, BVALID, BREADY, BRESP, ARVALID, ARREADY, ARADDR, RVALID, RREADY, RDATA, RRESP, irq, trigger_out
);
  input ACLK;
  wire ACLK;
  input ARESETn;
  wire ARESETn;
  input AWVALID;
  wire AWVALID;
  output AWREADY;
  wire AWREADY;
  input [11:0] AWADDR;
  wire [11:0] AWADDR;
  input WVALID;
  wire WVALID;
  output WREADY;
  wire WREADY;
  input [31:0] WDATA;
  wire [31:0] WDATA;
  input [3:0] WSTRB;
  wire [3:0] WSTRB;
  output BVALID;
  wire BVALID;
  input BREADY;
  wire BREADY;
  output [1:0] BRESP;
  wire [1:0] BRESP;
  input ARVALID;
  wire ARVALID;
  output ARREADY;
  wire ARREADY;
  input [11:0] ARADDR;
  wire [11:0] ARADDR;
  output RVALID;
  wire RVALID;
  input RREADY;
  wire RREADY;
  output [31:0] RDATA;
  wire [31:0] RDATA;
  output [1:0] RRESP;
  wire [1:0] RRESP;
  output irq;
  wire irq;
  output trigger_out;
  wire trigger_out;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire [31:0] _0439_;
  wire ctrl_en;
  wire ctrl_intr_en;
  wire ctrl_mode;
  wire [7:0] ctrl_prescale;
  wire ctrl_trig_en;
  wire hw_active;
  wire [31:0] hw_count_val;
  wire hw_intr_set;
  wire [3:0] if_rd_addr;
  wire [31:0] if_rd_data;
  wire if_rd_en;
  wire [3:0] if_wr_addr;
  wire [31:0] if_wr_data;
  wire if_wr_en;
  wire [3:0] if_wr_strb;
  wire [31:0] load_val;
  wire status_intr;
  wire \u_axi4l_if.ACLK ;
  wire [11:0] \u_axi4l_if.ARADDR ;
  wire \u_axi4l_if.ARESETn ;
  wire \u_axi4l_if.ARREADY ;
  wire \u_axi4l_if.ARVALID ;
  wire [11:0] \u_axi4l_if.AWADDR ;
  wire \u_axi4l_if.AWREADY ;
  wire \u_axi4l_if.AWVALID ;
  wire \u_axi4l_if.BREADY ;
  wire [1:0] \u_axi4l_if.BRESP ;
  wire \u_axi4l_if.BVALID ;
  wire [31:0] \u_axi4l_if.RDATA ;
  wire \u_axi4l_if.RREADY ;
  wire [1:0] \u_axi4l_if.RRESP ;
  wire \u_axi4l_if.RVALID ;
  wire [31:0] \u_axi4l_if.WDATA ;
  wire \u_axi4l_if.WREADY ;
  wire [3:0] \u_axi4l_if.WSTRB ;
  wire \u_axi4l_if.WVALID ;
  reg [3:0] \u_axi4l_if.ar_addr_q ;
  reg \u_axi4l_if.ar_captured_q ;
  reg \u_axi4l_if.ar_rd_pending_q ;
  reg [3:0] \u_axi4l_if.aw_addr_q ;
  reg \u_axi4l_if.aw_captured_q ;
  reg \u_axi4l_if.bvalid_q ;
  wire [3:0] \u_axi4l_if.rd_addr ;
  wire [31:0] \u_axi4l_if.rd_data ;
  wire \u_axi4l_if.rd_en ;
  reg [31:0] \u_axi4l_if.rdata_q ;
  reg \u_axi4l_if.rvalid_q ;
  reg \u_axi4l_if.w_captured_q ;
  reg [31:0] \u_axi4l_if.w_data_q ;
  reg [3:0] \u_axi4l_if.w_strb_q ;
  wire [3:0] \u_axi4l_if.wr_addr ;
  wire [31:0] \u_axi4l_if.wr_data ;
  wire \u_axi4l_if.wr_en ;
  wire [3:0] \u_axi4l_if.wr_strb ;
  reg \u_core.active_q ;
  wire \u_core.clk ;
  reg [31:0] \u_core.count_q ;
  wire \u_core.ctrl_en ;
  wire \u_core.ctrl_intr_en ;
  wire \u_core.ctrl_mode ;
  wire [7:0] \u_core.ctrl_prescale ;
  wire \u_core.ctrl_trig_en ;
  reg \u_core.en_prev_q ;
  wire \u_core.hw_active ;
  wire [31:0] \u_core.hw_count_val ;
  reg \u_core.hw_intr_set ;
  wire \u_core.irq ;
  wire [31:0] \u_core.load_val ;
  reg [7:0] \u_core.prescale_cnt_q ;
  wire \u_core.rst_n ;
  wire \u_core.status_intr ;
  reg \u_core.trigger_out ;
  wire \u_core.underflow ;
  wire \u_regfile.clk ;
  reg [31:0] \u_regfile.count_q ;
  wire \u_regfile.ctrl_en ;
  wire \u_regfile.ctrl_intr_en ;
  wire \u_regfile.ctrl_mode ;
  wire [7:0] \u_regfile.ctrl_prescale ;
  wire [31:0] \u_regfile.ctrl_q ;
  wire \u_regfile.ctrl_trig_en ;
  wire \u_regfile.hw_active ;
  wire [31:0] \u_regfile.hw_count_val ;
  wire \u_regfile.hw_intr_set ;
  reg [31:0] \u_regfile.load_q ;
  wire [31:0] \u_regfile.load_val ;
  wire [3:0] \u_regfile.rd_addr ;
  reg [31:0] \u_regfile.rd_data ;
  wire \u_regfile.rd_en ;
  wire \u_regfile.rst_n ;
  wire \u_regfile.status_intr ;
  wire [31:0] \u_regfile.status_q ;
  wire [3:0] \u_regfile.wr_addr ;
  wire [31:0] \u_regfile.wr_data ;
  wire \u_regfile.wr_en ;
  wire [3:0] \u_regfile.wr_strb ;
  assign _0055_ = ~(\u_core.prescale_cnt_q [0] | \u_core.prescale_cnt_q [1]);
  assign _0056_ = ~(\u_core.prescale_cnt_q [2] | \u_core.prescale_cnt_q [3]);
  assign _0057_ = _0056_ & _0055_;
  assign _0058_ = ~(\u_core.prescale_cnt_q [4] | \u_core.prescale_cnt_q [5]);
  assign _0059_ = ~(\u_core.prescale_cnt_q [7] | \u_core.prescale_cnt_q [6]);
  assign _0060_ = ~(_0059_ & _0058_);
  assign _0061_ = _0057_ & ~(_0060_);
  assign _0062_ = ~(_0061_ & \u_regfile.ctrl_q [0]);
  assign _0063_ = \u_core.active_q  & ~(_0062_);
  assign _0064_ = _0063_ & ~(\u_regfile.ctrl_q [1]);
  assign _0065_ = \u_regfile.ctrl_q [0] & ~(\u_core.en_prev_q );
  assign _0014_ = _0065_ | _0064_;
  assign irq = \u_regfile.ctrl_q [2] & \u_regfile.status_q [0];
  assign _0066_ = ~(\u_core.count_q [0] | \u_core.count_q [1]);
  assign _0067_ = ~(\u_core.count_q [3] | \u_core.count_q [2]);
  assign _0068_ = _0067_ & _0066_;
  assign _0069_ = ~(\u_core.count_q [5] | \u_core.count_q [4]);
  assign _0070_ = ~(\u_core.count_q [7] | \u_core.count_q [6]);
  assign _0071_ = _0070_ & _0069_;
  assign _0072_ = _0071_ & _0068_;
  assign _0073_ = \u_core.count_q [9] | \u_core.count_q [8];
  assign _0074_ = \u_core.count_q [11] | \u_core.count_q [10];
  assign _0075_ = _0074_ | _0073_;
  assign _0076_ = \u_core.count_q [13] | \u_core.count_q [12];
  assign _0077_ = ~(\u_core.count_q [15] | \u_core.count_q [14]);
  assign _0078_ = _0076_ | ~(_0077_);
  assign _0079_ = _0078_ | _0075_;
  assign _0080_ = _0072_ & ~(_0079_);
  assign _0081_ = ~(\u_core.count_q [17] | \u_core.count_q [16]);
  assign _0082_ = ~(\u_core.count_q [19] | \u_core.count_q [18]);
  assign _0083_ = _0082_ & _0081_;
  assign _0084_ = \u_core.count_q [21] | \u_core.count_q [20];
  assign _0085_ = ~(\u_core.count_q [23] | \u_core.count_q [22]);
  assign _0086_ = _0084_ | ~(_0085_);
  assign _0087_ = _0083_ & ~(_0086_);
  assign _0088_ = ~(\u_core.count_q [25] | \u_core.count_q [24]);
  assign _0089_ = ~(\u_core.count_q [27] | \u_core.count_q [26]);
  assign _0090_ = _0089_ & _0088_;
  assign _0091_ = ~(\u_core.count_q [29] | \u_core.count_q [28]);
  assign _0092_ = ~(\u_core.count_q [31] | \u_core.count_q [30]);
  assign _0093_ = _0092_ & _0091_;
  assign _0094_ = _0093_ & _0090_;
  assign _0095_ = ~(_0094_ & _0087_);
  assign _0096_ = _0080_ & ~(_0095_);
  assign \u_core.underflow  = _0096_ & _0063_;
  assign _0013_ = \u_core.underflow  & \u_regfile.ctrl_q [3];
  assign \u_regfile.wr_en  = \u_axi4l_if.w_captured_q  & \u_axi4l_if.aw_captured_q ;
  assign _0097_ = \u_axi4l_if.aw_addr_q [1] | ~(\u_axi4l_if.aw_addr_q [0]);
  assign _0098_ = \u_axi4l_if.aw_addr_q [3] | \u_axi4l_if.aw_addr_q [2];
  assign _0099_ = _0098_ | _0097_;
  assign _0100_ = \u_regfile.wr_en  & ~(_0099_);
  assign _0101_ = ~(_0100_ & \u_axi4l_if.w_strb_q [0]);
  assign _0102_ = \u_axi4l_if.w_data_q [0] & ~(_0101_);
  assign _0005_ = _0102_ | \u_core.hw_intr_set ;
  assign _0103_ = \u_axi4l_if.rvalid_q  & RREADY;
  assign _0004_ = _0103_ | \u_axi4l_if.ar_rd_pending_q ;
  assign _0003_ = \u_regfile.wr_en  | AWVALID;
  assign _0002_ = \u_regfile.wr_en  | WVALID;
  assign _0001_ = \u_regfile.wr_en  | BREADY;
  assign _0000_ = _0065_ | _0063_;
  assign _0104_ = _0096_ | ~(_0063_);
  assign _0105_ = _0104_ | _0065_;
  assign _0106_ = ~\u_regfile.ctrl_q [0];
  assign _0107_ = _0063_ | _0106_;
  assign _0108_ = ~(_0107_ | _0065_);
  assign _0012_ = _0105_ & ~(_0108_);
  assign _0109_ = ~\u_regfile.wr_en ;
  assign _0110_ = \u_axi4l_if.aw_addr_q [0] | ~(\u_axi4l_if.aw_addr_q [1]);
  assign _0111_ = _0110_ | _0098_;
  assign _0112_ = _0111_ | _0109_;
  assign _0011_ = \u_axi4l_if.w_strb_q [3] & ~(_0112_);
  assign _0010_ = \u_axi4l_if.w_strb_q [2] & ~(_0112_);
  assign _0009_ = \u_axi4l_if.w_strb_q [1] & ~(_0112_);
  assign _0008_ = \u_axi4l_if.w_strb_q [0] & ~(_0112_);
  assign _0113_ = \u_axi4l_if.aw_addr_q [1] | \u_axi4l_if.aw_addr_q [0];
  assign _0114_ = _0113_ | _0098_;
  assign _0115_ = _0114_ | _0109_;
  assign _0007_ = \u_axi4l_if.w_strb_q [1] & ~(_0115_);
  assign _0006_ = \u_axi4l_if.w_strb_q [0] & ~(_0115_);
  assign _0116_ = ~\u_core.prescale_cnt_q [0];
  assign _0117_ = _0061_ ? \u_regfile.ctrl_q [4] : _0116_;
  assign _0047_ = \u_regfile.ctrl_q [0] ? _0117_ : \u_regfile.ctrl_q [4];
  assign _0118_ = ~(\u_core.prescale_cnt_q [0] ^ \u_core.prescale_cnt_q [1]);
  assign _0119_ = _0061_ ? \u_regfile.ctrl_q [5] : _0118_;
  assign _0048_ = \u_regfile.ctrl_q [0] ? _0119_ : \u_regfile.ctrl_q [5];
  assign _0120_ = _0055_ ^ \u_core.prescale_cnt_q [2];
  assign _0121_ = _0061_ ? \u_regfile.ctrl_q [6] : _0120_;
  assign _0049_ = \u_regfile.ctrl_q [0] ? _0121_ : \u_regfile.ctrl_q [6];
  assign _0122_ = _0055_ & ~(\u_core.prescale_cnt_q [2]);
  assign _0123_ = _0122_ ^ \u_core.prescale_cnt_q [3];
  assign _0124_ = _0061_ ? \u_regfile.ctrl_q [7] : _0123_;
  assign _0050_ = \u_regfile.ctrl_q [0] ? _0124_ : \u_regfile.ctrl_q [7];
  assign _0125_ = _0056_ & ~(_0055_);
  assign _0126_ = _0056_ & ~(_0125_);
  assign _0127_ = _0126_ ^ \u_core.prescale_cnt_q [4];
  assign _0128_ = _0061_ ? \u_regfile.ctrl_q [8] : _0127_;
  assign _0051_ = \u_regfile.ctrl_q [0] ? _0128_ : \u_regfile.ctrl_q [8];
  assign _0129_ = _0126_ & ~(\u_core.prescale_cnt_q [4]);
  assign _0130_ = _0129_ ^ \u_core.prescale_cnt_q [5];
  assign _0131_ = _0061_ ? \u_regfile.ctrl_q [9] : _0130_;
  assign _0052_ = \u_regfile.ctrl_q [0] ? _0131_ : \u_regfile.ctrl_q [9];
  assign _0132_ = _0058_ & ~(_0126_);
  assign _0133_ = _0058_ & ~(_0132_);
  assign _0134_ = _0133_ ^ \u_core.prescale_cnt_q [6];
  assign _0135_ = _0061_ ? \u_regfile.ctrl_q [10] : _0134_;
  assign _0053_ = \u_regfile.ctrl_q [0] ? _0135_ : \u_regfile.ctrl_q [10];
  assign _0136_ = _0133_ & ~(\u_core.prescale_cnt_q [6]);
  assign _0137_ = _0136_ ^ \u_core.prescale_cnt_q [7];
  assign _0138_ = _0061_ ? \u_regfile.ctrl_q [11] : _0137_;
  assign _0054_ = \u_regfile.ctrl_q [0] ? _0138_ : \u_regfile.ctrl_q [11];
  assign _0139_ = ~\u_core.count_q [0];
  assign _0140_ = \u_regfile.load_q [0] & ~(\u_regfile.ctrl_q [1]);
  assign _0141_ = _0096_ ? _0140_ : _0139_;
  assign _0015_ = _0065_ ? \u_regfile.load_q [0] : _0141_;
  assign _0142_ = \u_regfile.load_q [1] & ~(\u_regfile.ctrl_q [1]);
  assign _0143_ = ~(\u_core.count_q [0] ^ \u_core.count_q [1]);
  assign _0144_ = _0096_ ? _0142_ : _0143_;
  assign _0026_ = _0065_ ? \u_regfile.load_q [1] : _0144_;
  assign _0145_ = \u_regfile.load_q [2] & ~(\u_regfile.ctrl_q [1]);
  assign _0146_ = _0066_ ^ \u_core.count_q [2];
  assign _0147_ = _0096_ ? _0145_ : _0146_;
  assign _0037_ = _0065_ ? \u_regfile.load_q [2] : _0147_;
  assign _0148_ = \u_regfile.load_q [3] & ~(\u_regfile.ctrl_q [1]);
  assign _0149_ = _0066_ & ~(\u_core.count_q [2]);
  assign _0150_ = _0149_ ^ \u_core.count_q [3];
  assign _0151_ = _0096_ ? _0148_ : _0150_;
  assign _0040_ = _0065_ ? \u_regfile.load_q [3] : _0151_;
  assign _0152_ = \u_regfile.load_q [4] & ~(\u_regfile.ctrl_q [1]);
  assign _0153_ = _0067_ & ~(_0066_);
  assign _0154_ = _0067_ & ~(_0153_);
  assign _0155_ = _0154_ ^ \u_core.count_q [4];
  assign _0156_ = _0096_ ? _0152_ : _0155_;
  assign _0041_ = _0065_ ? \u_regfile.load_q [4] : _0156_;
  assign _0157_ = \u_regfile.load_q [5] & ~(\u_regfile.ctrl_q [1]);
  assign _0158_ = _0154_ & ~(\u_core.count_q [4]);
  assign _0159_ = _0158_ ^ \u_core.count_q [5];
  assign _0160_ = _0096_ ? _0157_ : _0159_;
  assign _0042_ = _0065_ ? \u_regfile.load_q [5] : _0160_;
  assign _0161_ = \u_regfile.load_q [6] & ~(\u_regfile.ctrl_q [1]);
  assign _0162_ = _0069_ & ~(_0154_);
  assign _0163_ = _0069_ & ~(_0162_);
  assign _0164_ = _0163_ ^ \u_core.count_q [6];
  assign _0165_ = _0096_ ? _0161_ : _0164_;
  assign _0043_ = _0065_ ? \u_regfile.load_q [6] : _0165_;
  assign _0166_ = \u_regfile.load_q [7] & ~(\u_regfile.ctrl_q [1]);
  assign _0167_ = _0163_ & ~(\u_core.count_q [6]);
  assign _0168_ = _0167_ ^ \u_core.count_q [7];
  assign _0169_ = _0096_ ? _0166_ : _0168_;
  assign _0044_ = _0065_ ? \u_regfile.load_q [7] : _0169_;
  assign _0170_ = \u_regfile.load_q [8] & ~(\u_regfile.ctrl_q [1]);
  assign _0171_ = _0070_ & ~(_0069_);
  assign _0172_ = _0070_ & ~(_0171_);
  assign _0173_ = _0071_ & ~(_0154_);
  assign _0174_ = _0172_ & ~(_0173_);
  assign _0175_ = _0174_ ^ \u_core.count_q [8];
  assign _0176_ = _0096_ ? _0170_ : _0175_;
  assign _0045_ = _0065_ ? \u_regfile.load_q [8] : _0176_;
  assign _0177_ = \u_regfile.load_q [9] & ~(\u_regfile.ctrl_q [1]);
  assign _0178_ = _0174_ & ~(\u_core.count_q [8]);
  assign _0179_ = _0178_ ^ \u_core.count_q [9];
  assign _0180_ = _0096_ ? _0177_ : _0179_;
  assign _0046_ = _0065_ ? \u_regfile.load_q [9] : _0180_;
  assign _0181_ = \u_regfile.load_q [10] & ~(\u_regfile.ctrl_q [1]);
  assign _0182_ = ~(\u_core.count_q [9] | \u_core.count_q [8]);
  assign _0183_ = ~(_0174_ | _0073_);
  assign _0184_ = _0182_ & ~(_0183_);
  assign _0185_ = _0184_ ^ \u_core.count_q [10];
  assign _0186_ = _0096_ ? _0181_ : _0185_;
  assign _0016_ = _0065_ ? \u_regfile.load_q [10] : _0186_;
  assign _0187_ = \u_regfile.load_q [11] & ~(\u_regfile.ctrl_q [1]);
  assign _0188_ = _0184_ & ~(\u_core.count_q [10]);
  assign _0189_ = _0188_ ^ \u_core.count_q [11];
  assign _0190_ = _0096_ ? _0187_ : _0189_;
  assign _0017_ = _0065_ ? \u_regfile.load_q [11] : _0190_;
  assign _0191_ = \u_regfile.load_q [12] & ~(\u_regfile.ctrl_q [1]);
  assign _0192_ = ~(\u_core.count_q [11] | \u_core.count_q [10]);
  assign _0193_ = ~(_0182_ | _0074_);
  assign _0194_ = _0192_ & ~(_0193_);
  assign _0195_ = ~(_0174_ | _0075_);
  assign _0196_ = _0194_ & ~(_0195_);
  assign _0197_ = _0196_ ^ \u_core.count_q [12];
  assign _0198_ = _0096_ ? _0191_ : _0197_;
  assign _0018_ = _0065_ ? \u_regfile.load_q [12] : _0198_;
  assign _0199_ = \u_regfile.load_q [13] & ~(\u_regfile.ctrl_q [1]);
  assign _0200_ = _0196_ & ~(\u_core.count_q [12]);
  assign _0201_ = _0200_ ^ \u_core.count_q [13];
  assign _0202_ = _0096_ ? _0199_ : _0201_;
  assign _0019_ = _0065_ ? \u_regfile.load_q [13] : _0202_;
  assign _0203_ = \u_regfile.load_q [14] & ~(\u_regfile.ctrl_q [1]);
  assign _0204_ = ~\u_core.count_q [14];
  assign _0205_ = ~(\u_core.count_q [13] | \u_core.count_q [12]);
  assign _0206_ = ~(_0196_ | _0076_);
  assign _0207_ = _0206_ | ~(_0205_);
  assign _0208_ = _0207_ ^ _0204_;
  assign _0209_ = _0096_ ? _0203_ : _0208_;
  assign _0020_ = _0065_ ? \u_regfile.load_q [14] : _0209_;
  assign _0210_ = \u_regfile.load_q [15] & ~(\u_regfile.ctrl_q [1]);
  assign _0211_ = _0204_ & ~(_0207_);
  assign _0212_ = _0211_ ^ \u_core.count_q [15];
  assign _0213_ = _0096_ ? _0210_ : _0212_;
  assign _0021_ = _0065_ ? \u_regfile.load_q [15] : _0213_;
  assign _0214_ = \u_regfile.load_q [16] & ~(\u_regfile.ctrl_q [1]);
  assign _0215_ = _0077_ & ~(_0205_);
  assign _0216_ = _0077_ & ~(_0215_);
  assign _0217_ = ~(_0194_ | _0078_);
  assign _0218_ = _0216_ & ~(_0217_);
  assign _0219_ = ~(_0174_ | _0079_);
  assign _0220_ = _0218_ & ~(_0219_);
  assign _0221_ = _0220_ ^ \u_core.count_q [16];
  assign _0222_ = _0096_ ? _0214_ : _0221_;
  assign _0022_ = _0065_ ? \u_regfile.load_q [16] : _0222_;
  assign _0223_ = \u_regfile.load_q [17] & ~(\u_regfile.ctrl_q [1]);
  assign _0224_ = _0220_ & ~(\u_core.count_q [16]);
  assign _0225_ = _0224_ ^ \u_core.count_q [17];
  assign _0226_ = _0096_ ? _0223_ : _0225_;
  assign _0023_ = _0065_ ? \u_regfile.load_q [17] : _0226_;
  assign _0227_ = \u_regfile.load_q [18] & ~(\u_regfile.ctrl_q [1]);
  assign _0228_ = ~\u_core.count_q [18];
  assign _0229_ = _0081_ & ~(_0220_);
  assign _0230_ = _0229_ | ~(_0081_);
  assign _0231_ = _0230_ ^ _0228_;
  assign _0232_ = _0096_ ? _0227_ : _0231_;
  assign _0024_ = _0065_ ? \u_regfile.load_q [18] : _0232_;
  assign _0233_ = \u_regfile.load_q [19] & ~(\u_regfile.ctrl_q [1]);
  assign _0234_ = _0228_ & ~(_0230_);
  assign _0235_ = _0234_ ^ \u_core.count_q [19];
  assign _0236_ = _0096_ ? _0233_ : _0235_;
  assign _0025_ = _0065_ ? \u_regfile.load_q [19] : _0236_;
  assign _0237_ = \u_regfile.load_q [20] & ~(\u_regfile.ctrl_q [1]);
  assign _0238_ = _0082_ & ~(_0081_);
  assign _0239_ = _0082_ & ~(_0238_);
  assign _0240_ = _0083_ & ~(_0220_);
  assign _0241_ = _0239_ & ~(_0240_);
  assign _0242_ = _0241_ ^ \u_core.count_q [20];
  assign _0243_ = _0096_ ? _0237_ : _0242_;
  assign _0027_ = _0065_ ? \u_regfile.load_q [20] : _0243_;
  assign _0244_ = \u_regfile.load_q [21] & ~(\u_regfile.ctrl_q [1]);
  assign _0245_ = _0241_ & ~(\u_core.count_q [20]);
  assign _0246_ = _0245_ ^ \u_core.count_q [21];
  assign _0247_ = _0096_ ? _0244_ : _0246_;
  assign _0028_ = _0065_ ? \u_regfile.load_q [21] : _0247_;
  assign _0248_ = \u_regfile.load_q [22] & ~(\u_regfile.ctrl_q [1]);
  assign _0249_ = ~\u_core.count_q [22];
  assign _0250_ = ~(\u_core.count_q [21] | \u_core.count_q [20]);
  assign _0251_ = ~(_0241_ | _0084_);
  assign _0252_ = _0251_ | ~(_0250_);
  assign _0253_ = _0252_ ^ _0249_;
  assign _0254_ = _0096_ ? _0248_ : _0253_;
  assign _0029_ = _0065_ ? \u_regfile.load_q [22] : _0254_;
  assign _0255_ = \u_regfile.load_q [23] & ~(\u_regfile.ctrl_q [1]);
  assign _0256_ = _0249_ & ~(_0252_);
  assign _0257_ = _0256_ ^ \u_core.count_q [23];
  assign _0258_ = _0096_ ? _0255_ : _0257_;
  assign _0030_ = _0065_ ? \u_regfile.load_q [23] : _0258_;
  assign _0259_ = \u_regfile.load_q [24] & ~(\u_regfile.ctrl_q [1]);
  assign _0260_ = _0085_ & ~(_0250_);
  assign _0261_ = _0085_ & ~(_0260_);
  assign _0262_ = ~(_0239_ | _0086_);
  assign _0263_ = _0261_ & ~(_0262_);
  assign _0264_ = _0087_ & ~(_0220_);
  assign _0265_ = _0263_ & ~(_0264_);
  assign _0266_ = _0265_ ^ \u_core.count_q [24];
  assign _0267_ = _0096_ ? _0259_ : _0266_;
  assign _0031_ = _0065_ ? \u_regfile.load_q [24] : _0267_;
  assign _0268_ = \u_regfile.load_q [25] & ~(\u_regfile.ctrl_q [1]);
  assign _0269_ = _0265_ & ~(\u_core.count_q [24]);
  assign _0270_ = _0269_ ^ \u_core.count_q [25];
  assign _0271_ = _0096_ ? _0268_ : _0270_;
  assign _0032_ = _0065_ ? \u_regfile.load_q [25] : _0271_;
  assign _0272_ = \u_regfile.load_q [26] & ~(\u_regfile.ctrl_q [1]);
  assign _0273_ = ~\u_core.count_q [26];
  assign _0274_ = _0088_ & ~(_0265_);
  assign _0275_ = _0274_ | ~(_0088_);
  assign _0276_ = _0275_ ^ _0273_;
  assign _0277_ = _0096_ ? _0272_ : _0276_;
  assign _0033_ = _0065_ ? \u_regfile.load_q [26] : _0277_;
  assign _0278_ = \u_regfile.load_q [27] & ~(\u_regfile.ctrl_q [1]);
  assign _0279_ = _0273_ & ~(_0275_);
  assign _0280_ = _0279_ ^ \u_core.count_q [27];
  assign _0281_ = _0096_ ? _0278_ : _0280_;
  assign _0034_ = _0065_ ? \u_regfile.load_q [27] : _0281_;
  assign _0282_ = \u_regfile.load_q [28] & ~(\u_regfile.ctrl_q [1]);
  assign _0283_ = _0089_ & ~(_0088_);
  assign _0284_ = _0089_ & ~(_0283_);
  assign _0285_ = _0090_ & ~(_0265_);
  assign _0286_ = _0284_ & ~(_0285_);
  assign _0287_ = _0286_ ^ \u_core.count_q [28];
  assign _0288_ = _0096_ ? _0282_ : _0287_;
  assign _0035_ = _0065_ ? \u_regfile.load_q [28] : _0288_;
  assign _0289_ = \u_regfile.load_q [29] & ~(\u_regfile.ctrl_q [1]);
  assign _0290_ = _0286_ & ~(\u_core.count_q [28]);
  assign _0291_ = _0290_ ^ \u_core.count_q [29];
  assign _0292_ = _0096_ ? _0289_ : _0291_;
  assign _0036_ = _0065_ ? \u_regfile.load_q [29] : _0292_;
  assign _0293_ = \u_regfile.load_q [30] & ~(\u_regfile.ctrl_q [1]);
  assign _0294_ = ~\u_core.count_q [30];
  assign _0295_ = _0091_ & ~(_0286_);
  assign _0296_ = _0295_ | ~(_0091_);
  assign _0297_ = _0296_ ^ _0294_;
  assign _0298_ = _0096_ ? _0293_ : _0297_;
  assign _0038_ = _0065_ ? \u_regfile.load_q [30] : _0298_;
  assign _0299_ = \u_regfile.load_q [31] & ~(\u_regfile.ctrl_q [1]);
  assign _0300_ = _0294_ & ~(_0296_);
  assign _0301_ = _0300_ ^ \u_core.count_q [31];
  assign _0302_ = _0096_ ? _0299_ : _0301_;
  assign _0039_ = _0065_ ? \u_regfile.load_q [31] : _0302_;
  assign _0303_ = ~(\u_axi4l_if.ar_addr_q [0] & \u_axi4l_if.ar_addr_q [1]);
  assign _0304_ = \u_axi4l_if.ar_addr_q [3] | \u_axi4l_if.ar_addr_q [2];
  assign _0305_ = _0304_ | _0303_;
  assign _0306_ = \u_regfile.count_q [0] & ~(_0305_);
  assign _0307_ = \u_axi4l_if.ar_addr_q [0] | ~(\u_axi4l_if.ar_addr_q [1]);
  assign _0308_ = _0307_ | _0304_;
  assign _0309_ = \u_regfile.load_q [0] & ~(_0308_);
  assign _0310_ = _0309_ | _0306_;
  assign _0311_ = \u_axi4l_if.ar_addr_q [1] | ~(\u_axi4l_if.ar_addr_q [0]);
  assign _0312_ = _0311_ | _0304_;
  assign _0313_ = \u_regfile.status_q [0] & ~(_0312_);
  assign _0314_ = \u_axi4l_if.ar_addr_q [0] | \u_axi4l_if.ar_addr_q [1];
  assign _0315_ = _0314_ | _0304_;
  assign _0316_ = \u_regfile.ctrl_q [0] & ~(_0315_);
  assign _0317_ = _0316_ | _0313_;
  assign _0318_ = _0317_ | _0310_;
  assign _0319_ = ~(_0308_ & _0305_);
  assign _0320_ = ~(_0315_ & _0312_);
  assign _0321_ = _0320_ | _0319_;
  assign _0439_[0] = _0321_ & _0318_;
  assign _0322_ = _0305_ | ~(\u_regfile.count_q [1]);
  assign _0323_ = \u_regfile.load_q [1] & ~(_0308_);
  assign _0324_ = _0322_ & ~(_0323_);
  assign _0325_ = \u_regfile.status_q [1] & ~(_0312_);
  assign _0326_ = \u_regfile.ctrl_q [1] & ~(_0315_);
  assign _0327_ = _0326_ | _0325_;
  assign _0328_ = _0324_ & ~(_0327_);
  assign _0439_[1] = _0321_ & ~(_0328_);
  assign _0329_ = _0305_ | ~(\u_regfile.count_q [2]);
  assign _0330_ = \u_regfile.load_q [2] & ~(_0308_);
  assign _0331_ = _0329_ & ~(_0330_);
  assign _0332_ = \u_regfile.ctrl_q [2] & ~(_0315_);
  assign _0333_ = _0331_ & ~(_0332_);
  assign _0439_[2] = _0321_ & ~(_0333_);
  assign _0334_ = _0305_ | ~(\u_regfile.count_q [3]);
  assign _0335_ = \u_regfile.load_q [3] & ~(_0308_);
  assign _0336_ = _0334_ & ~(_0335_);
  assign _0337_ = \u_regfile.ctrl_q [3] & ~(_0315_);
  assign _0338_ = _0336_ & ~(_0337_);
  assign _0439_[3] = _0321_ & ~(_0338_);
  assign _0339_ = _0305_ | ~(\u_regfile.count_q [4]);
  assign _0340_ = \u_regfile.load_q [4] & ~(_0308_);
  assign _0341_ = _0339_ & ~(_0340_);
  assign _0342_ = \u_regfile.ctrl_q [4] & ~(_0315_);
  assign _0343_ = _0341_ & ~(_0342_);
  assign _0439_[4] = _0321_ & ~(_0343_);
  assign _0344_ = _0305_ | ~(\u_regfile.count_q [5]);
  assign _0345_ = \u_regfile.load_q [5] & ~(_0308_);
  assign _0346_ = _0344_ & ~(_0345_);
  assign _0347_ = \u_regfile.ctrl_q [5] & ~(_0315_);
  assign _0348_ = _0346_ & ~(_0347_);
  assign _0439_[5] = _0321_ & ~(_0348_);
  assign _0349_ = _0305_ | ~(\u_regfile.count_q [6]);
  assign _0350_ = \u_regfile.load_q [6] & ~(_0308_);
  assign _0351_ = _0349_ & ~(_0350_);
  assign _0352_ = \u_regfile.ctrl_q [6] & ~(_0315_);
  assign _0353_ = _0351_ & ~(_0352_);
  assign _0439_[6] = _0321_ & ~(_0353_);
  assign _0354_ = _0305_ | ~(\u_regfile.count_q [7]);
  assign _0355_ = \u_regfile.load_q [7] & ~(_0308_);
  assign _0356_ = _0354_ & ~(_0355_);
  assign _0357_ = \u_regfile.ctrl_q [7] & ~(_0315_);
  assign _0358_ = _0356_ & ~(_0357_);
  assign _0439_[7] = _0321_ & ~(_0358_);
  assign _0359_ = _0305_ | ~(\u_regfile.count_q [8]);
  assign _0360_ = \u_regfile.load_q [8] & ~(_0308_);
  assign _0361_ = _0359_ & ~(_0360_);
  assign _0362_ = \u_regfile.ctrl_q [8] & ~(_0315_);
  assign _0363_ = _0361_ & ~(_0362_);
  assign _0439_[8] = _0321_ & ~(_0363_);
  assign _0364_ = _0305_ | ~(\u_regfile.count_q [9]);
  assign _0365_ = \u_regfile.load_q [9] & ~(_0308_);
  assign _0366_ = _0364_ & ~(_0365_);
  assign _0367_ = \u_regfile.ctrl_q [9] & ~(_0315_);
  assign _0368_ = _0366_ & ~(_0367_);
  assign _0439_[9] = _0321_ & ~(_0368_);
  assign _0369_ = _0305_ | ~(\u_regfile.count_q [10]);
  assign _0370_ = \u_regfile.load_q [10] & ~(_0308_);
  assign _0371_ = _0369_ & ~(_0370_);
  assign _0372_ = \u_regfile.ctrl_q [10] & ~(_0315_);
  assign _0373_ = _0371_ & ~(_0372_);
  assign _0439_[10] = _0321_ & ~(_0373_);
  assign _0374_ = _0305_ | ~(\u_regfile.count_q [11]);
  assign _0375_ = \u_regfile.load_q [11] & ~(_0308_);
  assign _0376_ = _0374_ & ~(_0375_);
  assign _0377_ = \u_regfile.ctrl_q [11] & ~(_0315_);
  assign _0378_ = _0376_ & ~(_0377_);
  assign _0439_[11] = _0321_ & ~(_0378_);
  assign _0379_ = _0305_ | ~(\u_regfile.count_q [12]);
  assign _0380_ = \u_regfile.load_q [12] & ~(_0308_);
  assign _0381_ = _0379_ & ~(_0380_);
  assign _0439_[12] = _0321_ & ~(_0381_);
  assign _0382_ = _0305_ | ~(\u_regfile.count_q [13]);
  assign _0383_ = \u_regfile.load_q [13] & ~(_0308_);
  assign _0384_ = _0382_ & ~(_0383_);
  assign _0439_[13] = _0321_ & ~(_0384_);
  assign _0385_ = _0305_ | ~(\u_regfile.count_q [14]);
  assign _0386_ = \u_regfile.load_q [14] & ~(_0308_);
  assign _0387_ = _0385_ & ~(_0386_);
  assign _0439_[14] = _0321_ & ~(_0387_);
  assign _0388_ = _0305_ | ~(\u_regfile.count_q [15]);
  assign _0389_ = \u_regfile.load_q [15] & ~(_0308_);
  assign _0390_ = _0388_ & ~(_0389_);
  assign _0439_[15] = _0321_ & ~(_0390_);
  assign _0391_ = _0305_ | ~(\u_regfile.count_q [16]);
  assign _0392_ = \u_regfile.load_q [16] & ~(_0308_);
  assign _0393_ = _0391_ & ~(_0392_);
  assign _0439_[16] = _0321_ & ~(_0393_);
  assign _0394_ = _0305_ | ~(\u_regfile.count_q [17]);
  assign _0395_ = \u_regfile.load_q [17] & ~(_0308_);
  assign _0396_ = _0394_ & ~(_0395_);
  assign _0439_[17] = _0321_ & ~(_0396_);
  assign _0397_ = _0305_ | ~(\u_regfile.count_q [18]);
  assign _0398_ = \u_regfile.load_q [18] & ~(_0308_);
  assign _0399_ = _0397_ & ~(_0398_);
  assign _0439_[18] = _0321_ & ~(_0399_);
  assign _0400_ = _0305_ | ~(\u_regfile.count_q [19]);
  assign _0401_ = \u_regfile.load_q [19] & ~(_0308_);
  assign _0402_ = _0400_ & ~(_0401_);
  assign _0439_[19] = _0321_ & ~(_0402_);
  assign _0403_ = _0305_ | ~(\u_regfile.count_q [20]);
  assign _0404_ = \u_regfile.load_q [20] & ~(_0308_);
  assign _0405_ = _0403_ & ~(_0404_);
  assign _0439_[20] = _0321_ & ~(_0405_);
  assign _0406_ = _0305_ | ~(\u_regfile.count_q [21]);
  assign _0407_ = \u_regfile.load_q [21] & ~(_0308_);
  assign _0408_ = _0406_ & ~(_0407_);
  assign _0439_[21] = _0321_ & ~(_0408_);
  assign _0409_ = _0305_ | ~(\u_regfile.count_q [22]);
  assign _0410_ = \u_regfile.load_q [22] & ~(_0308_);
  assign _0411_ = _0409_ & ~(_0410_);
  assign _0439_[22] = _0321_ & ~(_0411_);
  assign _0412_ = _0305_ | ~(\u_regfile.count_q [23]);
  assign _0413_ = \u_regfile.load_q [23] & ~(_0308_);
  assign _0414_ = _0412_ & ~(_0413_);
  assign _0439_[23] = _0321_ & ~(_0414_);
  assign _0415_ = _0305_ | ~(\u_regfile.count_q [24]);
  assign _0416_ = \u_regfile.load_q [24] & ~(_0308_);
  assign _0417_ = _0415_ & ~(_0416_);
  assign _0439_[24] = _0321_ & ~(_0417_);
  assign _0418_ = _0305_ | ~(\u_regfile.count_q [25]);
  assign _0419_ = \u_regfile.load_q [25] & ~(_0308_);
  assign _0420_ = _0418_ & ~(_0419_);
  assign _0439_[25] = _0321_ & ~(_0420_);
  assign _0421_ = _0305_ | ~(\u_regfile.count_q [26]);
  assign _0422_ = \u_regfile.load_q [26] & ~(_0308_);
  assign _0423_ = _0421_ & ~(_0422_);
  assign _0439_[26] = _0321_ & ~(_0423_);
  assign _0424_ = _0305_ | ~(\u_regfile.count_q [27]);
  assign _0425_ = \u_regfile.load_q [27] & ~(_0308_);
  assign _0426_ = _0424_ & ~(_0425_);
  assign _0439_[27] = _0321_ & ~(_0426_);
  assign _0427_ = _0305_ | ~(\u_regfile.count_q [28]);
  assign _0428_ = \u_regfile.load_q [28] & ~(_0308_);
  assign _0429_ = _0427_ & ~(_0428_);
  assign _0439_[28] = _0321_ & ~(_0429_);
  assign _0430_ = _0305_ | ~(\u_regfile.count_q [29]);
  assign _0431_ = \u_regfile.load_q [29] & ~(_0308_);
  assign _0432_ = _0430_ & ~(_0431_);
  assign _0439_[29] = _0321_ & ~(_0432_);
  assign _0433_ = _0305_ | ~(\u_regfile.count_q [30]);
  assign _0434_ = \u_regfile.load_q [30] & ~(_0308_);
  assign _0435_ = _0433_ & ~(_0434_);
  assign _0439_[30] = _0321_ & ~(_0435_);
  assign _0436_ = _0305_ | ~(\u_regfile.count_q [31]);
  assign _0437_ = \u_regfile.load_q [31] & ~(_0308_);
  assign _0438_ = _0436_ & ~(_0437_);
  assign _0439_[31] = _0321_ & ~(_0438_);
  reg \u_regfile.status_q_reg[1] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.status_q_reg[1]  <= 1'h0;
    else \u_regfile.status_q_reg[1]  <= \u_core.active_q ;
  assign \u_regfile.status_q [1] = \u_regfile.status_q_reg[1] ;
  reg \u_regfile.status_q_reg[0] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.status_q_reg[0]  <= 1'h0;
    else if (_0005_) \u_regfile.status_q_reg[0]  <= \u_core.hw_intr_set ;
  assign \u_regfile.status_q [0] = \u_regfile.status_q_reg[0] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_captured_q  <= 1'h0;
    else \u_axi4l_if.ar_captured_q  <= ARVALID;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_addr_q [0] <= 1'h0;
    else if (ARVALID) \u_axi4l_if.ar_addr_q [0] <= ARADDR[2];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_addr_q [1] <= 1'h0;
    else if (ARVALID) \u_axi4l_if.ar_addr_q [1] <= ARADDR[3];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_addr_q [2] <= 1'h0;
    else if (ARVALID) \u_axi4l_if.ar_addr_q [2] <= ARADDR[4];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_addr_q [3] <= 1'h0;
    else if (ARVALID) \u_axi4l_if.ar_addr_q [3] <= ARADDR[5];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.ar_rd_pending_q  <= 1'h0;
    else \u_axi4l_if.ar_rd_pending_q  <= \u_axi4l_if.ar_captured_q ;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rvalid_q  <= 1'h0;
    else if (_0004_) \u_axi4l_if.rvalid_q  <= \u_axi4l_if.ar_rd_pending_q ;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [0] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [0] <= \u_regfile.rd_data [0];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [1] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [1] <= \u_regfile.rd_data [1];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [2] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [2] <= \u_regfile.rd_data [2];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [3] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [3] <= \u_regfile.rd_data [3];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [4] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [4] <= \u_regfile.rd_data [4];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [5] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [5] <= \u_regfile.rd_data [5];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [6] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [6] <= \u_regfile.rd_data [6];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [7] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [7] <= \u_regfile.rd_data [7];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [8] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [8] <= \u_regfile.rd_data [8];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [9] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [9] <= \u_regfile.rd_data [9];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [10] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [10] <= \u_regfile.rd_data [10];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [11] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [11] <= \u_regfile.rd_data [11];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [12] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [12] <= \u_regfile.rd_data [12];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [13] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [13] <= \u_regfile.rd_data [13];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [14] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [14] <= \u_regfile.rd_data [14];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [15] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [15] <= \u_regfile.rd_data [15];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [16] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [16] <= \u_regfile.rd_data [16];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [17] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [17] <= \u_regfile.rd_data [17];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [18] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [18] <= \u_regfile.rd_data [18];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [19] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [19] <= \u_regfile.rd_data [19];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [20] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [20] <= \u_regfile.rd_data [20];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [21] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [21] <= \u_regfile.rd_data [21];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [22] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [22] <= \u_regfile.rd_data [22];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [23] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [23] <= \u_regfile.rd_data [23];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [24] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [24] <= \u_regfile.rd_data [24];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [25] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [25] <= \u_regfile.rd_data [25];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [26] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [26] <= \u_regfile.rd_data [26];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [27] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [27] <= \u_regfile.rd_data [27];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [28] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [28] <= \u_regfile.rd_data [28];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [29] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [29] <= \u_regfile.rd_data [29];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [30] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [30] <= \u_regfile.rd_data [30];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.rdata_q [31] <= 1'h0;
    else if (\u_axi4l_if.ar_rd_pending_q ) \u_axi4l_if.rdata_q [31] <= \u_regfile.rd_data [31];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.aw_captured_q  <= 1'h0;
    else if (_0003_) \u_axi4l_if.aw_captured_q  <= AWVALID;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.aw_addr_q [0] <= 1'h0;
    else if (AWVALID) \u_axi4l_if.aw_addr_q [0] <= AWADDR[2];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.aw_addr_q [1] <= 1'h0;
    else if (AWVALID) \u_axi4l_if.aw_addr_q [1] <= AWADDR[3];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.aw_addr_q [2] <= 1'h0;
    else if (AWVALID) \u_axi4l_if.aw_addr_q [2] <= AWADDR[4];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.aw_addr_q [3] <= 1'h0;
    else if (AWVALID) \u_axi4l_if.aw_addr_q [3] <= AWADDR[5];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_captured_q  <= 1'h0;
    else if (_0002_) \u_axi4l_if.w_captured_q  <= WVALID;
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [0] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [0] <= WDATA[0];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [1] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [1] <= WDATA[1];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [2] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [2] <= WDATA[2];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [3] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [3] <= WDATA[3];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [4] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [4] <= WDATA[4];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [5] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [5] <= WDATA[5];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [6] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [6] <= WDATA[6];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [7] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [7] <= WDATA[7];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [8] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [8] <= WDATA[8];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [9] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [9] <= WDATA[9];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [10] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [10] <= WDATA[10];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [11] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [11] <= WDATA[11];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [12] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [12] <= WDATA[12];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [13] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [13] <= WDATA[13];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [14] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [14] <= WDATA[14];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [15] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [15] <= WDATA[15];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [16] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [16] <= WDATA[16];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [17] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [17] <= WDATA[17];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [18] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [18] <= WDATA[18];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [19] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [19] <= WDATA[19];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [20] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [20] <= WDATA[20];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [21] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [21] <= WDATA[21];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [22] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [22] <= WDATA[22];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [23] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [23] <= WDATA[23];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [24] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [24] <= WDATA[24];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [25] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [25] <= WDATA[25];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [26] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [26] <= WDATA[26];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [27] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [27] <= WDATA[27];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [28] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [28] <= WDATA[28];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [29] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [29] <= WDATA[29];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [30] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [30] <= WDATA[30];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_data_q [31] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_data_q [31] <= WDATA[31];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_strb_q [0] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_strb_q [0] <= WSTRB[0];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_strb_q [1] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_strb_q [1] <= WSTRB[1];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_strb_q [2] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_strb_q [2] <= WSTRB[2];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.w_strb_q [3] <= 1'h0;
    else if (WVALID) \u_axi4l_if.w_strb_q [3] <= WSTRB[3];
  always @(posedge ACLK)
    if (!ARESETn) \u_axi4l_if.bvalid_q  <= 1'h0;
    else if (_0001_) \u_axi4l_if.bvalid_q  <= \u_regfile.wr_en ;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.trigger_out  <= 1'h0;
    else \u_core.trigger_out  <= _0013_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.hw_intr_set  <= 1'h0;
    else \u_core.hw_intr_set  <= \u_core.underflow ;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [0] <= 1'h0;
    else if (_0000_) \u_core.count_q [0] <= _0015_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [1] <= 1'h0;
    else if (_0000_) \u_core.count_q [1] <= _0026_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [2] <= 1'h0;
    else if (_0000_) \u_core.count_q [2] <= _0037_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [3] <= 1'h0;
    else if (_0000_) \u_core.count_q [3] <= _0040_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [4] <= 1'h0;
    else if (_0000_) \u_core.count_q [4] <= _0041_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [5] <= 1'h0;
    else if (_0000_) \u_core.count_q [5] <= _0042_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [6] <= 1'h0;
    else if (_0000_) \u_core.count_q [6] <= _0043_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [7] <= 1'h0;
    else if (_0000_) \u_core.count_q [7] <= _0044_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [8] <= 1'h0;
    else if (_0000_) \u_core.count_q [8] <= _0045_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [9] <= 1'h0;
    else if (_0000_) \u_core.count_q [9] <= _0046_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [10] <= 1'h0;
    else if (_0000_) \u_core.count_q [10] <= _0016_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [11] <= 1'h0;
    else if (_0000_) \u_core.count_q [11] <= _0017_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [12] <= 1'h0;
    else if (_0000_) \u_core.count_q [12] <= _0018_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [13] <= 1'h0;
    else if (_0000_) \u_core.count_q [13] <= _0019_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [14] <= 1'h0;
    else if (_0000_) \u_core.count_q [14] <= _0020_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [15] <= 1'h0;
    else if (_0000_) \u_core.count_q [15] <= _0021_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [16] <= 1'h0;
    else if (_0000_) \u_core.count_q [16] <= _0022_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [17] <= 1'h0;
    else if (_0000_) \u_core.count_q [17] <= _0023_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [18] <= 1'h0;
    else if (_0000_) \u_core.count_q [18] <= _0024_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [19] <= 1'h0;
    else if (_0000_) \u_core.count_q [19] <= _0025_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [20] <= 1'h0;
    else if (_0000_) \u_core.count_q [20] <= _0027_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [21] <= 1'h0;
    else if (_0000_) \u_core.count_q [21] <= _0028_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [22] <= 1'h0;
    else if (_0000_) \u_core.count_q [22] <= _0029_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [23] <= 1'h0;
    else if (_0000_) \u_core.count_q [23] <= _0030_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [24] <= 1'h0;
    else if (_0000_) \u_core.count_q [24] <= _0031_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [25] <= 1'h0;
    else if (_0000_) \u_core.count_q [25] <= _0032_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [26] <= 1'h0;
    else if (_0000_) \u_core.count_q [26] <= _0033_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [27] <= 1'h0;
    else if (_0000_) \u_core.count_q [27] <= _0034_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [28] <= 1'h0;
    else if (_0000_) \u_core.count_q [28] <= _0035_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [29] <= 1'h0;
    else if (_0000_) \u_core.count_q [29] <= _0036_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [30] <= 1'h0;
    else if (_0000_) \u_core.count_q [30] <= _0038_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.count_q [31] <= 1'h0;
    else if (_0000_) \u_core.count_q [31] <= _0039_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.active_q  <= 1'h0;
    else if (_0012_) \u_core.active_q  <= _0014_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [0] <= 1'h0;
    else \u_core.prescale_cnt_q [0] <= _0047_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [1] <= 1'h0;
    else \u_core.prescale_cnt_q [1] <= _0048_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [2] <= 1'h0;
    else \u_core.prescale_cnt_q [2] <= _0049_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [3] <= 1'h0;
    else \u_core.prescale_cnt_q [3] <= _0050_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [4] <= 1'h0;
    else \u_core.prescale_cnt_q [4] <= _0051_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [5] <= 1'h0;
    else \u_core.prescale_cnt_q [5] <= _0052_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [6] <= 1'h0;
    else \u_core.prescale_cnt_q [6] <= _0053_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.prescale_cnt_q [7] <= 1'h0;
    else \u_core.prescale_cnt_q [7] <= _0054_;
  always @(posedge ACLK)
    if (!ARESETn) \u_core.en_prev_q  <= 1'h0;
    else \u_core.en_prev_q  <= \u_regfile.ctrl_q [0];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [0] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [0] <= _0439_[0];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [1] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [1] <= _0439_[1];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [2] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [2] <= _0439_[2];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [3] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [3] <= _0439_[3];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [4] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [4] <= _0439_[4];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [5] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [5] <= _0439_[5];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [6] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [6] <= _0439_[6];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [7] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [7] <= _0439_[7];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [8] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [8] <= _0439_[8];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [9] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [9] <= _0439_[9];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [10] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [10] <= _0439_[10];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [11] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [11] <= _0439_[11];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [12] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [12] <= _0439_[12];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [13] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [13] <= _0439_[13];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [14] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [14] <= _0439_[14];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [15] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [15] <= _0439_[15];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [16] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [16] <= _0439_[16];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [17] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [17] <= _0439_[17];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [18] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [18] <= _0439_[18];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [19] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [19] <= _0439_[19];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [20] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [20] <= _0439_[20];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [21] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [21] <= _0439_[21];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [22] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [22] <= _0439_[22];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [23] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [23] <= _0439_[23];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [24] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [24] <= _0439_[24];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [25] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [25] <= _0439_[25];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [26] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [26] <= _0439_[26];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [27] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [27] <= _0439_[27];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [28] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [28] <= _0439_[28];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [29] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [29] <= _0439_[29];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [30] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [30] <= _0439_[30];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.rd_data [31] <= 1'h0;
    else if (\u_axi4l_if.ar_captured_q ) \u_regfile.rd_data [31] <= _0439_[31];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [0] <= 1'h0;
    else \u_regfile.count_q [0] <= \u_core.count_q [0];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [1] <= 1'h0;
    else \u_regfile.count_q [1] <= \u_core.count_q [1];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [2] <= 1'h0;
    else \u_regfile.count_q [2] <= \u_core.count_q [2];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [3] <= 1'h0;
    else \u_regfile.count_q [3] <= \u_core.count_q [3];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [4] <= 1'h0;
    else \u_regfile.count_q [4] <= \u_core.count_q [4];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [5] <= 1'h0;
    else \u_regfile.count_q [5] <= \u_core.count_q [5];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [6] <= 1'h0;
    else \u_regfile.count_q [6] <= \u_core.count_q [6];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [7] <= 1'h0;
    else \u_regfile.count_q [7] <= \u_core.count_q [7];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [8] <= 1'h0;
    else \u_regfile.count_q [8] <= \u_core.count_q [8];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [9] <= 1'h0;
    else \u_regfile.count_q [9] <= \u_core.count_q [9];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [10] <= 1'h0;
    else \u_regfile.count_q [10] <= \u_core.count_q [10];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [11] <= 1'h0;
    else \u_regfile.count_q [11] <= \u_core.count_q [11];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [12] <= 1'h0;
    else \u_regfile.count_q [12] <= \u_core.count_q [12];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [13] <= 1'h0;
    else \u_regfile.count_q [13] <= \u_core.count_q [13];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [14] <= 1'h0;
    else \u_regfile.count_q [14] <= \u_core.count_q [14];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [15] <= 1'h0;
    else \u_regfile.count_q [15] <= \u_core.count_q [15];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [16] <= 1'h0;
    else \u_regfile.count_q [16] <= \u_core.count_q [16];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [17] <= 1'h0;
    else \u_regfile.count_q [17] <= \u_core.count_q [17];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [18] <= 1'h0;
    else \u_regfile.count_q [18] <= \u_core.count_q [18];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [19] <= 1'h0;
    else \u_regfile.count_q [19] <= \u_core.count_q [19];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [20] <= 1'h0;
    else \u_regfile.count_q [20] <= \u_core.count_q [20];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [21] <= 1'h0;
    else \u_regfile.count_q [21] <= \u_core.count_q [21];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [22] <= 1'h0;
    else \u_regfile.count_q [22] <= \u_core.count_q [22];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [23] <= 1'h0;
    else \u_regfile.count_q [23] <= \u_core.count_q [23];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [24] <= 1'h0;
    else \u_regfile.count_q [24] <= \u_core.count_q [24];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [25] <= 1'h0;
    else \u_regfile.count_q [25] <= \u_core.count_q [25];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [26] <= 1'h0;
    else \u_regfile.count_q [26] <= \u_core.count_q [26];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [27] <= 1'h0;
    else \u_regfile.count_q [27] <= \u_core.count_q [27];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [28] <= 1'h0;
    else \u_regfile.count_q [28] <= \u_core.count_q [28];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [29] <= 1'h0;
    else \u_regfile.count_q [29] <= \u_core.count_q [29];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [30] <= 1'h0;
    else \u_regfile.count_q [30] <= \u_core.count_q [30];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.count_q [31] <= 1'h0;
    else \u_regfile.count_q [31] <= \u_core.count_q [31];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [24] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [24] <= \u_axi4l_if.w_data_q [24];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [25] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [25] <= \u_axi4l_if.w_data_q [25];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [26] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [26] <= \u_axi4l_if.w_data_q [26];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [27] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [27] <= \u_axi4l_if.w_data_q [27];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [28] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [28] <= \u_axi4l_if.w_data_q [28];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [29] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [29] <= \u_axi4l_if.w_data_q [29];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [30] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [30] <= \u_axi4l_if.w_data_q [30];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [31] <= 1'h0;
    else if (_0011_) \u_regfile.load_q [31] <= \u_axi4l_if.w_data_q [31];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [16] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [16] <= \u_axi4l_if.w_data_q [16];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [17] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [17] <= \u_axi4l_if.w_data_q [17];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [18] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [18] <= \u_axi4l_if.w_data_q [18];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [19] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [19] <= \u_axi4l_if.w_data_q [19];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [20] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [20] <= \u_axi4l_if.w_data_q [20];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [21] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [21] <= \u_axi4l_if.w_data_q [21];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [22] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [22] <= \u_axi4l_if.w_data_q [22];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [23] <= 1'h0;
    else if (_0010_) \u_regfile.load_q [23] <= \u_axi4l_if.w_data_q [23];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [8] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [8] <= \u_axi4l_if.w_data_q [8];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [9] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [9] <= \u_axi4l_if.w_data_q [9];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [10] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [10] <= \u_axi4l_if.w_data_q [10];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [11] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [11] <= \u_axi4l_if.w_data_q [11];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [12] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [12] <= \u_axi4l_if.w_data_q [12];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [13] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [13] <= \u_axi4l_if.w_data_q [13];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [14] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [14] <= \u_axi4l_if.w_data_q [14];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [15] <= 1'h0;
    else if (_0009_) \u_regfile.load_q [15] <= \u_axi4l_if.w_data_q [15];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [0] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [0] <= \u_axi4l_if.w_data_q [0];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [1] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [1] <= \u_axi4l_if.w_data_q [1];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [2] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [2] <= \u_axi4l_if.w_data_q [2];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [3] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [3] <= \u_axi4l_if.w_data_q [3];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [4] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [4] <= \u_axi4l_if.w_data_q [4];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [5] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [5] <= \u_axi4l_if.w_data_q [5];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [6] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [6] <= \u_axi4l_if.w_data_q [6];
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.load_q [7] <= 1'h0;
    else if (_0008_) \u_regfile.load_q [7] <= \u_axi4l_if.w_data_q [7];
  reg \u_regfile.ctrl_q_reg[8] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[8]  <= 1'h0;
    else if (_0007_) \u_regfile.ctrl_q_reg[8]  <= \u_axi4l_if.w_data_q [8];
  assign \u_regfile.ctrl_q [8] = \u_regfile.ctrl_q_reg[8] ;
  reg \u_regfile.ctrl_q_reg[9] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[9]  <= 1'h0;
    else if (_0007_) \u_regfile.ctrl_q_reg[9]  <= \u_axi4l_if.w_data_q [9];
  assign \u_regfile.ctrl_q [9] = \u_regfile.ctrl_q_reg[9] ;
  reg \u_regfile.ctrl_q_reg[10] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[10]  <= 1'h0;
    else if (_0007_) \u_regfile.ctrl_q_reg[10]  <= \u_axi4l_if.w_data_q [10];
  assign \u_regfile.ctrl_q [10] = \u_regfile.ctrl_q_reg[10] ;
  reg \u_regfile.ctrl_q_reg[11] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[11]  <= 1'h0;
    else if (_0007_) \u_regfile.ctrl_q_reg[11]  <= \u_axi4l_if.w_data_q [11];
  assign \u_regfile.ctrl_q [11] = \u_regfile.ctrl_q_reg[11] ;
  reg \u_regfile.ctrl_q_reg[0] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[0]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[0]  <= \u_axi4l_if.w_data_q [0];
  assign \u_regfile.ctrl_q [0] = \u_regfile.ctrl_q_reg[0] ;
  reg \u_regfile.ctrl_q_reg[1] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[1]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[1]  <= \u_axi4l_if.w_data_q [1];
  assign \u_regfile.ctrl_q [1] = \u_regfile.ctrl_q_reg[1] ;
  reg \u_regfile.ctrl_q_reg[2] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[2]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[2]  <= \u_axi4l_if.w_data_q [2];
  assign \u_regfile.ctrl_q [2] = \u_regfile.ctrl_q_reg[2] ;
  reg \u_regfile.ctrl_q_reg[3] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[3]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[3]  <= \u_axi4l_if.w_data_q [3];
  assign \u_regfile.ctrl_q [3] = \u_regfile.ctrl_q_reg[3] ;
  reg \u_regfile.ctrl_q_reg[4] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[4]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[4]  <= \u_axi4l_if.w_data_q [4];
  assign \u_regfile.ctrl_q [4] = \u_regfile.ctrl_q_reg[4] ;
  reg \u_regfile.ctrl_q_reg[5] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[5]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[5]  <= \u_axi4l_if.w_data_q [5];
  assign \u_regfile.ctrl_q [5] = \u_regfile.ctrl_q_reg[5] ;
  reg \u_regfile.ctrl_q_reg[6] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[6]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[6]  <= \u_axi4l_if.w_data_q [6];
  assign \u_regfile.ctrl_q [6] = \u_regfile.ctrl_q_reg[6] ;
  reg \u_regfile.ctrl_q_reg[7] ;
  always @(posedge ACLK)
    if (!ARESETn) \u_regfile.ctrl_q_reg[7]  <= 1'h0;
    else if (_0006_) \u_regfile.ctrl_q_reg[7]  <= \u_axi4l_if.w_data_q [7];
  assign \u_regfile.ctrl_q [7] = \u_regfile.ctrl_q_reg[7] ;
  assign ARREADY = 1'h1;
  assign AWREADY = 1'h1;
  assign BRESP = 2'h0;
  assign BVALID = \u_axi4l_if.bvalid_q ;
  assign RDATA = \u_axi4l_if.rdata_q ;
  assign RRESP = 2'h0;
  assign RVALID = \u_axi4l_if.rvalid_q ;
  assign WREADY = 1'h1;
  assign ctrl_en = \u_regfile.ctrl_q [0];
  assign ctrl_intr_en = \u_regfile.ctrl_q [2];
  assign ctrl_mode = \u_regfile.ctrl_q [1];
  assign ctrl_prescale = \u_regfile.ctrl_q [11:4];
  assign ctrl_trig_en = \u_regfile.ctrl_q [3];
  assign hw_active = \u_core.active_q ;
  assign hw_count_val = \u_core.count_q ;
  assign hw_intr_set = \u_core.hw_intr_set ;
  assign if_rd_addr = \u_axi4l_if.ar_addr_q ;
  assign if_rd_data = \u_regfile.rd_data ;
  assign if_rd_en = \u_axi4l_if.ar_captured_q ;
  assign if_wr_addr = \u_axi4l_if.aw_addr_q ;
  assign if_wr_data = \u_axi4l_if.w_data_q ;
  assign if_wr_en = \u_regfile.wr_en ;
  assign if_wr_strb = \u_axi4l_if.w_strb_q ;
  assign load_val = \u_regfile.load_q ;
  assign status_intr = \u_regfile.status_q [0];
  assign trigger_out = \u_core.trigger_out ;
  assign \u_axi4l_if.ACLK  = ACLK;
  assign \u_axi4l_if.ARADDR  = ARADDR;
  assign \u_axi4l_if.ARESETn  = ARESETn;
  assign \u_axi4l_if.ARREADY  = 1'h1;
  assign \u_axi4l_if.ARVALID  = ARVALID;
  assign \u_axi4l_if.AWADDR  = AWADDR;
  assign \u_axi4l_if.AWREADY  = 1'h1;
  assign \u_axi4l_if.AWVALID  = AWVALID;
  assign \u_axi4l_if.BREADY  = BREADY;
  assign \u_axi4l_if.BRESP  = 2'h0;
  assign \u_axi4l_if.BVALID  = \u_axi4l_if.bvalid_q ;
  assign \u_axi4l_if.RDATA  = \u_axi4l_if.rdata_q ;
  assign \u_axi4l_if.RREADY  = RREADY;
  assign \u_axi4l_if.RRESP  = 2'h0;
  assign \u_axi4l_if.RVALID  = \u_axi4l_if.rvalid_q ;
  assign \u_axi4l_if.WDATA  = WDATA;
  assign \u_axi4l_if.WREADY  = 1'h1;
  assign \u_axi4l_if.WSTRB  = WSTRB;
  assign \u_axi4l_if.WVALID  = WVALID;
  assign \u_axi4l_if.rd_addr  = \u_axi4l_if.ar_addr_q ;
  assign \u_axi4l_if.rd_data  = \u_regfile.rd_data ;
  assign \u_axi4l_if.rd_en  = \u_axi4l_if.ar_captured_q ;
  assign \u_axi4l_if.wr_addr  = \u_axi4l_if.aw_addr_q ;
  assign \u_axi4l_if.wr_data  = \u_axi4l_if.w_data_q ;
  assign \u_axi4l_if.wr_en  = \u_regfile.wr_en ;
  assign \u_axi4l_if.wr_strb  = \u_axi4l_if.w_strb_q ;
  assign \u_core.clk  = ACLK;
  assign \u_core.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_core.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_core.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_core.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_core.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_core.hw_active  = \u_core.active_q ;
  assign \u_core.hw_count_val  = \u_core.count_q ;
  assign \u_core.irq  = irq;
  assign \u_core.load_val  = \u_regfile.load_q ;
  assign \u_core.rst_n  = ARESETn;
  assign \u_core.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.clk  = ACLK;
  assign \u_regfile.ctrl_en  = \u_regfile.ctrl_q [0];
  assign \u_regfile.ctrl_intr_en  = \u_regfile.ctrl_q [2];
  assign \u_regfile.ctrl_mode  = \u_regfile.ctrl_q [1];
  assign \u_regfile.ctrl_prescale  = \u_regfile.ctrl_q [11:4];
  assign \u_regfile.ctrl_q [31:12] = 20'h00000;
  assign \u_regfile.ctrl_trig_en  = \u_regfile.ctrl_q [3];
  assign \u_regfile.hw_active  = \u_core.active_q ;
  assign \u_regfile.hw_count_val  = \u_core.count_q ;
  assign \u_regfile.hw_intr_set  = \u_core.hw_intr_set ;
  assign \u_regfile.load_val  = \u_regfile.load_q ;
  assign \u_regfile.rd_addr  = \u_axi4l_if.ar_addr_q ;
  assign \u_regfile.rd_en  = \u_axi4l_if.ar_captured_q ;
  assign \u_regfile.rst_n  = ARESETn;
  assign \u_regfile.status_intr  = \u_regfile.status_q [0];
  assign \u_regfile.status_q [31:2] = 30'h00000000;
  assign \u_regfile.wr_addr  = \u_axi4l_if.aw_addr_q ;
  assign \u_regfile.wr_data  = \u_axi4l_if.w_data_q ;
  assign \u_regfile.wr_strb  = \u_axi4l_if.w_strb_q ;
endmodule
