/* timer_regs.h - Timer IP register definitions (C99).
 * Auto-generated by generate_timer.py - do not edit by hand.
 * Single source of truth: design/systemrdl/timer.rdl
 */

#ifndef TIMER_REGS_H
#define TIMER_REGS_H

#include <stdint.h>

/* -------------------------------------------------------------------------
 * Base address placeholder - override before including this header.
 * -------------------------------------------------------------------------*/
#ifndef TIMER_BASE_ADDR
#  define TIMER_BASE_ADDR  (0x00000000UL)
#endif

/* -------------------------------------------------------------------------
 * Register byte offsets
 * -------------------------------------------------------------------------*/
#define TIMER_CTRL_OFFSET     (0x00U)
#define TIMER_STATUS_OFFSET   (0x04U)
#define TIMER_LOAD_OFFSET     (0x08U)
#define TIMER_COUNT_OFFSET    (0x0CU)
#define TIMER_CAPTURE_OFFSET  (0x10U)

/* -------------------------------------------------------------------------
 * Register absolute addresses
 * -------------------------------------------------------------------------*/
#define TIMER_CTRL_ADDR     ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_CTRL_OFFSET))
#define TIMER_STATUS_ADDR   ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_STATUS_OFFSET))
#define TIMER_LOAD_ADDR     ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_LOAD_OFFSET))
#define TIMER_COUNT_ADDR    ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_COUNT_OFFSET))
#define TIMER_CAPTURE_ADDR  ((volatile uint32_t *)(TIMER_BASE_ADDR + TIMER_CAPTURE_OFFSET))

/* -------------------------------------------------------------------------
 * CTRL register fields (byte offset 0x00)
 * -------------------------------------------------------------------------*/
#define TIMER_CTRL_RESET           (0x00000000UL)

/** EN - Timer enable (bit 0) */
#define TIMER_CTRL_EN_BIT          (0U)
#define TIMER_CTRL_EN_MASK         (0x00000001UL)
#define TIMER_CTRL_EN_GET(reg)     (((reg) & TIMER_CTRL_EN_MASK) >> TIMER_CTRL_EN_BIT)
#define TIMER_CTRL_EN_SET(reg, v)  (((reg) & ~TIMER_CTRL_EN_MASK) | \
                                    (((uint32_t)(v) << TIMER_CTRL_EN_BIT) & TIMER_CTRL_EN_MASK))

/** MODE - Operating mode (bit 1): 0=repeat/free-run, 1=one-shot */
#define TIMER_CTRL_MODE_BIT        (1U)
#define TIMER_CTRL_MODE_MASK       (0x00000002UL)
#define TIMER_CTRL_MODE_REPEAT     (0U)
#define TIMER_CTRL_MODE_ONESHOT    (1U)
#define TIMER_CTRL_MODE_GET(reg)   (((reg) & TIMER_CTRL_MODE_MASK) >> TIMER_CTRL_MODE_BIT)
#define TIMER_CTRL_MODE_SET(reg, v)(((reg) & ~TIMER_CTRL_MODE_MASK) | \
                                    (((uint32_t)(v) << TIMER_CTRL_MODE_BIT) \
                                      & TIMER_CTRL_MODE_MASK))

/** INTR_EN - Interrupt enable (bit 2) */
#define TIMER_CTRL_INTR_EN_BIT         (2U)
#define TIMER_CTRL_INTR_EN_MASK        (0x00000004UL)
#define TIMER_CTRL_INTR_EN_GET(reg)    (((reg) & TIMER_CTRL_INTR_EN_MASK) \
                                         >> TIMER_CTRL_INTR_EN_BIT)
#define TIMER_CTRL_INTR_EN_SET(reg, v) (((reg) & ~TIMER_CTRL_INTR_EN_MASK) | \
                                        (((uint32_t)(v) << TIMER_CTRL_INTR_EN_BIT) \
                                          & TIMER_CTRL_INTR_EN_MASK))

/** TRIG_EN - Trigger output enable (bit 3) */
#define TIMER_CTRL_TRIG_EN_BIT         (3U)
#define TIMER_CTRL_TRIG_EN_MASK        (0x00000008UL)
#define TIMER_CTRL_TRIG_EN_GET(reg)    (((reg) & TIMER_CTRL_TRIG_EN_MASK) \
                                         >> TIMER_CTRL_TRIG_EN_BIT)
#define TIMER_CTRL_TRIG_EN_SET(reg, v) (((reg) & ~TIMER_CTRL_TRIG_EN_MASK) | \
                                        (((uint32_t)(v) << TIMER_CTRL_TRIG_EN_BIT) \
                                          & TIMER_CTRL_TRIG_EN_MASK))

/** PRESCALE - Clock prescale (bits 11:4); divide ratio = PRESCALE + 1 */
#define TIMER_CTRL_PRESCALE_LSB        (4U)
#define TIMER_CTRL_PRESCALE_MASK       (0x00000FF0UL)
#define TIMER_CTRL_PRESCALE_GET(reg)   (((reg) & TIMER_CTRL_PRESCALE_MASK) \
                                         >> TIMER_CTRL_PRESCALE_LSB)
#define TIMER_CTRL_PRESCALE_SET(reg, v)(((reg) & ~TIMER_CTRL_PRESCALE_MASK) | \
                                        (((uint32_t)(v) << TIMER_CTRL_PRESCALE_LSB) \
                                          & TIMER_CTRL_PRESCALE_MASK))

/** RESTART - Force-reload command (bit 12); self-clearing — write 1 to reload COUNT from LOAD */
#define TIMER_CTRL_RESTART_BIT         (12U)
#define TIMER_CTRL_RESTART_MASK        (0x00001000UL)
#define TIMER_CTRL_RESTART             (TIMER_CTRL_RESTART_MASK)

/** IRQ_MODE - Interrupt output mode (bit 13): 0=level, 1=pulse */
#define TIMER_CTRL_IRQ_MODE_BIT        (13U)
#define TIMER_CTRL_IRQ_MODE_MASK       (0x00002000UL)
#define TIMER_CTRL_IRQ_MODE_LEVEL      (0U)
#define TIMER_CTRL_IRQ_MODE_PULSE      (1U)
#define TIMER_CTRL_IRQ_MODE_GET(reg)   (((reg) & TIMER_CTRL_IRQ_MODE_MASK) \
                                         >> TIMER_CTRL_IRQ_MODE_BIT)
#define TIMER_CTRL_IRQ_MODE_SET(reg, v)(((reg) & ~TIMER_CTRL_IRQ_MODE_MASK) | \
                                        (((uint32_t)(v) << TIMER_CTRL_IRQ_MODE_BIT) \
                                          & TIMER_CTRL_IRQ_MODE_MASK))

/** SNAPSHOT - Race-free COUNT snapshot command (bit 14); self-clearing — write 1 to latch COUNT into CAPTURE */
#define TIMER_CTRL_SNAPSHOT_BIT        (14U)
#define TIMER_CTRL_SNAPSHOT_MASK       (0x00004000UL)
#define TIMER_CTRL_SNAPSHOT            (TIMER_CTRL_SNAPSHOT_MASK)

/* -------------------------------------------------------------------------
 * STATUS register fields (byte offset 0x04)
 * -------------------------------------------------------------------------*/
#define TIMER_STATUS_RESET          (0x00000000UL)

/** INTR - Interrupt pending (bit 0); W1C - write 1 to clear */
#define TIMER_STATUS_INTR_BIT       (0U)
#define TIMER_STATUS_INTR_MASK      (0x00000001UL)
#define TIMER_STATUS_INTR_GET(reg)  (((reg) & TIMER_STATUS_INTR_MASK) \
                                      >> TIMER_STATUS_INTR_BIT)
#define TIMER_STATUS_INTR_CLR       (TIMER_STATUS_INTR_MASK)

/** ACTIVE - Timer running (bit 1); read-only */
#define TIMER_STATUS_ACTIVE_BIT     (1U)
#define TIMER_STATUS_ACTIVE_MASK    (0x00000002UL)
#define TIMER_STATUS_ACTIVE_GET(reg)(((reg) & TIMER_STATUS_ACTIVE_MASK) \
                                      >> TIMER_STATUS_ACTIVE_BIT)

/** OVF - Overrun flag (bit 2); W1C — set when underflow fires while INTR is already pending */
#define TIMER_STATUS_OVF_BIT        (2U)
#define TIMER_STATUS_OVF_MASK       (0x00000004UL)
#define TIMER_STATUS_OVF_GET(reg)   (((reg) & TIMER_STATUS_OVF_MASK) \
                                      >> TIMER_STATUS_OVF_BIT)
#define TIMER_STATUS_OVF_CLR        (TIMER_STATUS_OVF_MASK)

/* -------------------------------------------------------------------------
 * LOAD register (byte offset 0x08) - reload / initial count value
 * -------------------------------------------------------------------------*/
#define TIMER_LOAD_RESET            (0x00000000UL)
#define TIMER_LOAD_VALUE_MASK       (0xFFFFFFFFUL)

/* -------------------------------------------------------------------------
 * COUNT register (byte offset 0x0C) - current counter value (read-only)
 * -------------------------------------------------------------------------*/
#define TIMER_COUNT_RESET           (0x00000000UL)
#define TIMER_COUNT_VALUE_MASK      (0xFFFFFFFFUL)

/* -------------------------------------------------------------------------
 * CAPTURE register (byte offset 0x10) - race-free counter snapshot (read-only)
 * Written by hardware when CTRL.SNAPSHOT is asserted.
 * -------------------------------------------------------------------------*/
#define TIMER_CAPTURE_RESET         (0x00000000UL)
#define TIMER_CAPTURE_VALUE_MASK    (0xFFFFFFFFUL)

/* -------------------------------------------------------------------------
 * Convenience accessor macros (assumes TIMER_BASE_ADDR is defined)
 * -------------------------------------------------------------------------*/
#define TIMER_REG_READ(offset)       \
    (*((volatile uint32_t *)(TIMER_BASE_ADDR + (offset))))
#define TIMER_REG_WRITE(offset, val) \
    (*((volatile uint32_t *)(TIMER_BASE_ADDR + (offset))) = (uint32_t)(val))

#endif /* TIMER_REGS_H */
