// timer_reg_pkg.sv - Timer IP register-file package.
// Auto-generated by generate_timer.py - do not edit by hand.
// Single source of truth: design/systemrdl/timer.rdl

`ifndef TIMER_REG_PKG_SV
`define TIMER_REG_PKG_SV

package timer_reg_pkg;

  // -----------------------------------------------------------------------
  // Address offsets (word address = byte_offset >> 2)
  // -----------------------------------------------------------------------
  parameter logic [3:0] TIMER_CTRL_OFFSET    = 4'h0; // 0x00
  parameter logic [3:0] TIMER_STATUS_OFFSET  = 4'h1; // 0x04
  parameter logic [3:0] TIMER_LOAD_OFFSET    = 4'h2; // 0x08
  parameter logic [3:0] TIMER_COUNT_OFFSET   = 4'h3; // 0x0C
  parameter logic [3:0] TIMER_CAPTURE_OFFSET = 4'h4; // 0x10

  // -----------------------------------------------------------------------
  // CTRL register (byte offset 0x00, word offset 0x0)
  // -----------------------------------------------------------------------
  parameter logic [31:0] TIMER_CTRL_RESET          = 32'h0000_0000;
  // Mask constants are used by firmware and testbenches; not consumed by RTL.
  /* verilator lint_off UNUSEDPARAM */
  parameter logic [31:0] TIMER_CTRL_EN_MASK         = 32'h0000_0001; // bit  0
  parameter logic [31:0] TIMER_CTRL_MODE_MASK        = 32'h0000_0002; // bit  1
  parameter logic [31:0] TIMER_CTRL_INTR_EN_MASK     = 32'h0000_0004; // bit  2
  parameter logic [31:0] TIMER_CTRL_TRIG_EN_MASK     = 32'h0000_0008; // bit  3
  parameter logic [31:0] TIMER_CTRL_PRESCALE_MASK    = 32'h0000_0FF0; // bits 11:4
  parameter logic [31:0] TIMER_CTRL_RESTART_MASK     = 32'h0000_1000; // bit 12
  parameter logic [31:0] TIMER_CTRL_IRQ_MODE_MASK    = 32'h0000_2000; // bit 13
  parameter logic [31:0] TIMER_CTRL_SNAPSHOT_MASK    = 32'h0000_4000; // bit 14
  /* verilator lint_on UNUSEDPARAM */
  parameter int unsigned TIMER_CTRL_EN_BIT          = 0;
  parameter int unsigned TIMER_CTRL_MODE_BIT        = 1;
  parameter int unsigned TIMER_CTRL_INTR_EN_BIT     = 2;
  parameter int unsigned TIMER_CTRL_TRIG_EN_BIT     = 3;
  parameter int unsigned TIMER_CTRL_PRESCALE_LSB    = 4;
  parameter int unsigned TIMER_CTRL_RESTART_BIT     = 12;
  parameter int unsigned TIMER_CTRL_IRQ_MODE_BIT    = 13;
  parameter int unsigned TIMER_CTRL_SNAPSHOT_BIT    = 14;

  // -----------------------------------------------------------------------
  // STATUS register (byte offset 0x04, word offset 0x1)
  // -----------------------------------------------------------------------
  parameter logic [31:0] TIMER_STATUS_RESET        = 32'h0000_0000;
  /* verilator lint_off UNUSEDPARAM */
  parameter logic [31:0] TIMER_STATUS_INTR_MASK    = 32'h0000_0001; // bit  0
  parameter logic [31:0] TIMER_STATUS_ACTIVE_MASK  = 32'h0000_0002; // bit  1
  parameter logic [31:0] TIMER_STATUS_OVF_MASK     = 32'h0000_0004; // bit  2
  /* verilator lint_on UNUSEDPARAM */
  parameter int unsigned TIMER_STATUS_INTR_BIT     = 0;
  parameter int unsigned TIMER_STATUS_ACTIVE_BIT   = 1;
  parameter int unsigned TIMER_STATUS_OVF_BIT      = 2;

  // -----------------------------------------------------------------------
  // LOAD register (byte offset 0x08, word offset 0x2)
  // -----------------------------------------------------------------------
  parameter logic [31:0] TIMER_LOAD_RESET = 32'h0000_0000;

  // -----------------------------------------------------------------------
  // COUNT register (byte offset 0x0C, word offset 0x3)
  // -----------------------------------------------------------------------
  parameter logic [31:0] TIMER_COUNT_RESET = 32'h0000_0000;

  // -----------------------------------------------------------------------
  // CAPTURE register (byte offset 0x10, word offset 0x4)
  // -----------------------------------------------------------------------
  parameter logic [31:0] TIMER_CAPTURE_RESET = 32'h0000_0000;

endpackage : timer_reg_pkg

`endif // TIMER_REG_PKG_SV
