-- timer_reg_pkg.vhd - Timer IP register-file package (VHDL-2008).
-- Auto-generated by generate_timer.py - do not edit by hand.
-- Single source of truth: design/systemrdl/timer.rdl

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package timer_reg_pkg is

  -- -----------------------------------------------------------------------
  -- Address offsets (word address = byte_offset / 4)
  -- -----------------------------------------------------------------------
  constant TIMER_CTRL_OFFSET    : std_ulogic_vector(3 downto 0) := x"0"; -- 0x00
  constant TIMER_STATUS_OFFSET  : std_ulogic_vector(3 downto 0) := x"1"; -- 0x04
  constant TIMER_LOAD_OFFSET    : std_ulogic_vector(3 downto 0) := x"2"; -- 0x08
  constant TIMER_COUNT_OFFSET   : std_ulogic_vector(3 downto 0) := x"3"; -- 0x0C
  constant TIMER_CAPTURE_OFFSET : std_ulogic_vector(3 downto 0) := x"4"; -- 0x10

  -- -----------------------------------------------------------------------
  -- CTRL register (byte offset 0x00)
  -- -----------------------------------------------------------------------
  constant TIMER_CTRL_RESET           : std_ulogic_vector(31 downto 0) := x"00000000";
  constant TIMER_CTRL_EN_MASK         : std_ulogic_vector(31 downto 0) := x"00000001"; -- bit  0
  constant TIMER_CTRL_MODE_MASK       : std_ulogic_vector(31 downto 0) := x"00000002"; -- bit  1
  constant TIMER_CTRL_INTR_EN_MASK    : std_ulogic_vector(31 downto 0) := x"00000004"; -- bit  2
  constant TIMER_CTRL_TRIG_EN_MASK    : std_ulogic_vector(31 downto 0) := x"00000008"; -- bit  3
  constant TIMER_CTRL_PRESCALE_MASK   : std_ulogic_vector(31 downto 0) := x"00000FF0"; -- bits 11:4
  constant TIMER_CTRL_RESTART_MASK    : std_ulogic_vector(31 downto 0) := x"00001000"; -- bit 12
  constant TIMER_CTRL_IRQ_MODE_MASK   : std_ulogic_vector(31 downto 0) := x"00002000"; -- bit 13
  constant TIMER_CTRL_SNAPSHOT_MASK   : std_ulogic_vector(31 downto 0) := x"00004000"; -- bit 14
  constant TIMER_CTRL_EN_BIT          : integer := 0;
  constant TIMER_CTRL_MODE_BIT        : integer := 1;
  constant TIMER_CTRL_INTR_EN_BIT     : integer := 2;
  constant TIMER_CTRL_TRIG_EN_BIT     : integer := 3;
  constant TIMER_CTRL_PRESCALE_LSB    : integer := 4;
  constant TIMER_CTRL_PRESCALE_MSB    : integer := 11;
  constant TIMER_CTRL_RESTART_BIT     : integer := 12;
  constant TIMER_CTRL_IRQ_MODE_BIT    : integer := 13;
  constant TIMER_CTRL_SNAPSHOT_BIT    : integer := 14;

  -- -----------------------------------------------------------------------
  -- STATUS register (byte offset 0x04)
  -- -----------------------------------------------------------------------
  constant TIMER_STATUS_RESET        : std_ulogic_vector(31 downto 0) := x"00000000";
  constant TIMER_STATUS_INTR_MASK    : std_ulogic_vector(31 downto 0) := x"00000001"; -- bit  0
  constant TIMER_STATUS_ACTIVE_MASK  : std_ulogic_vector(31 downto 0) := x"00000002"; -- bit  1
  constant TIMER_STATUS_OVF_MASK     : std_ulogic_vector(31 downto 0) := x"00000004"; -- bit  2
  constant TIMER_STATUS_INTR_BIT     : integer := 0;
  constant TIMER_STATUS_ACTIVE_BIT   : integer := 1;
  constant TIMER_STATUS_OVF_BIT      : integer := 2;

  -- -----------------------------------------------------------------------
  -- LOAD register (byte offset 0x08)
  -- -----------------------------------------------------------------------
  constant TIMER_LOAD_RESET  : std_ulogic_vector(31 downto 0) := x"00000000";

  -- -----------------------------------------------------------------------
  -- COUNT register (byte offset 0x0C)
  -- -----------------------------------------------------------------------
  constant TIMER_COUNT_RESET : std_ulogic_vector(31 downto 0) := x"00000000";

  -- -----------------------------------------------------------------------
  -- CAPTURE register (byte offset 0x10)
  -- -----------------------------------------------------------------------
  constant TIMER_CAPTURE_RESET : std_ulogic_vector(31 downto 0) := x"00000000";

end package timer_reg_pkg;
