#!/usr/bin/env bash
# cleanup.sh — Remove all build and simulation artifacts for timer
# Usage: bash timer/cleanup.sh

# Guard: require CLAUDE_TIMER_PATH
if [ -z "${CLAUDE_TIMER_PATH}" ]; then
    echo "ERROR: CLAUDE_TIMER_PATH is not set."
    echo "       Please run:  source timer/setup.sh"
    exit 1
fi

set -e

echo "Cleaning timer build and simulation artifacts..."

# Simulator working directories (Icarus/GHDL/ModelSim)
rm -rf "${CLAUDE_TIMER_PATH}/verification/work"/*

# Vivado simulation projects (generated by create_project_*.tcl)
rm -rf "${CLAUDE_TIMER_PATH}/verification/vivado/work"

# Firmware build artifacts
rm -rf "${CLAUDE_TIMER_PATH}/firmware/build"/*
rm -rf "${CLAUDE_TIMER_PATH}/firmware/obj"/*
rm -rf "${CLAUDE_TIMER_PATH}/firmware/lib"/*

# Synthesis outputs (Vivado and Quartus reports, logs, and project directories)
python3 "${CLAUDE_TIMER_PATH}/synthesis/run_vendor_synth.py" --clean

# Design Compiler outputs (netlists, reports, VHDL library dirs, DC intermediates)
bash "${CLAUDE_TIMER_PATH}/synthesis/clean.sh"

# PrimeTime STA outputs (csun.edu only; --clean is host-agnostic and a no-op elsewhere)
python3 "${CLAUDE_TIMER_PATH}/synthesis/run_primetime_sta.py" --clean

# Formal verification run dirs and results logs, SymbiYosys and VC Formal
# (keep scripts and properties). Superset of run_formal.sh --clean.
python3 "${CLAUDE_TIMER_PATH}/verification/tools/formal_timer.py" --clean

# Lint logs (keep config and waivers)
rm -f "${CLAUDE_TIMER_PATH}/verification/lint/lint_results.log"

# SpyGlass lint intermediates (csun.edu only — keep the .prj files, remove the scratch workdir)
rm -rf "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/vcst_rtdb" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/vcst_rtdb.bak" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/"*.prj.tcl* \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/vcst_command.log" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/vcst_session.log"* \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/.vcstPref" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/spyglass.out" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/report_hdl.txt" \
       "${CLAUDE_TIMER_PATH}/verification/lint/spyglass/VCSOptFile.txt"

# Files Synopsys tools drop into whatever directory they are launched from
# (dc_shell/pt_shell/lc_shell command logs, fsdb2vcd/Verdi/VCS scratch) — left
# behind when a tool is run by hand from the IP root or the tools directory.
for dir in "${CLAUDE_TIMER_PATH}" "${CLAUDE_TIMER_PATH}/verification/tools"; do
    rm -rf "${dir}/command.log" \
           "${dir}/"*_command.log \
           "${dir}/fsdb2vcdLog" \
           "${dir}/verdiLog" \
           "${dir}/novas_dump.log" \
           "${dir}/ucli.key" \
           "${dir}/DVEfiles" \
           "${dir}/csrc" \
           "${dir}/simv" "${dir}/simv.daidir" \
           "${dir}/vcdplus.vpd" \
           "${dir}/.rce"
done

# Python cache directories
find "${CLAUDE_TIMER_PATH}" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find "${CLAUDE_TIMER_PATH}" -name "*.pyc" -o -name "*.pyo" | xargs rm -f 2>/dev/null || true

echo "Clean complete."
